### ISSUE TITLE
使用了一段时间，产生了一堆数据库，这样正常么？[ 问题咨询 ]

### ISSUE THREAD

**Issue by sudofeng** [hhyo/archer#1182]
### 问题描述
使用了一段时间，产生了一堆数据库，这样正常么？

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
这是用来回滚的备份表, inception 自动创建的

**Comment by sudofeng** [comment]
> 这是用来回滚的备份表, inception 自动创建的

好的 谢谢
