### ISSUE TITLE
[ 问题咨询 ]MySQL数据库大表修改

### ISSUE THREAD

**Issue by jimsoft1000** [hhyo/archer#1187]
### 问题描述
MySQL数据库大表修改，archery是否使用pt-online-schema-change来操作

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by nick2wang** [comment]
可配置使用ptosc或ghost
src/docker-compose/inception/config.toml
[osc]
osc_on = true

[ghost]
ghost_on = false

**Comment by jimsoft1000** [comment]
Thanks，已经配置，测试通过
