### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by g3stone** [hhyo/archer#1190]
### 问题描述

请问archery支持aws的aurora数据库吗？，我可以正常通过archery查询aurora数据，但是在提交sql上线上报错如下：
binlog日志未开启,无法备份!
但实际上我的aurora是已经打开bin-log了的

**Comment by liguopeng-ascendex** [comment]
aws 的aurora可以支持的。 
一个aurora开了binlog，是可以选择备份sql的，
另一个aurora没开启binlog，也报你这个错误。

其实我对数据库的备份的理解是这样的，应该不用管源库有没有开启binlog，都应该可以选择备份。

**Comment by naxiwer** [comment]
aws 的aurora可以支持的。
一个aurora开了binlog，是可以选择备份sql的，
另一个aurora没开启binlog，也报你这个错误。

其实我想选择备份的功能理解是不是可以这样改一下：
不用管源库有没有开启binlog，都应该可以选择备份并成功执行备份。

**Comment by naxiwer** [comment]
<img width="1494" alt="企业微信截图_ae47f781-9b02-436a-ba64-5fb74efb11d8" src="https://user-images.githubusercontent.com/10301387/160735423-d8357ab2-cd35-46dc-8479-f9dbee5e0ddd.png">

<img width="1234" alt="企业微信截图_68275ee6-780c-4bb4-b824-965e058f9e59" src="https://user-images.githubusercontent.com/10301387/160735455-755e7deb-b371-4acd-83c3-e64aba55ff7f.png">


我也希望能解决这个问题

**Comment by naxiwer** [comment]
语句其实挺简单，能提交，没问题，就是一选择“备份”就提示这个错误。

**Comment by nick2wang** [comment]
> aws 的aurora可以支持的。 一个aurora开了binlog，是可以选择备份sql的， 另一个aurora没开启binlog，也报你这个错误。
> 
> 其实我想选择备份的功能理解是不是可以这样改一下： 不用管源库有没有开启binlog，都应该可以选择备份并成功执行备份。

备份依赖binlog，必须开启 https://github.com/hhyo/Archery/issues/854#issuecomment-680578147

**Comment by naxiwer** [comment]
> > aws 的aurora可以支持的。 一个aurora开了binlog，是可以选择备份sql的， 另一个aurora没开启binlog，也报你这个错误。
> > 其实我想选择备份的功能理解是不是可以这样改一下： 不用管源库有没有开启binlog，都应该可以选择备份并成功执行备份。
> 
> 备份依赖binlog，必须开启 [#854 (comment)](https://github.com/hhyo/Archery/issues/854#issuecomment-680578147)

明白了。 多谢回复
