### ISSUE TITLE
[ 功能建议 ]使用 systemd 风格的标准单元管理

### ISSUE THREAD

**Issue by waitspring** [hhyo/archer#1193]
### 目前遇到的问题/使用障碍
1、目前 Archery 使用 supervisord 作为守护单元，但 supervisord 本身并不如 systemd 作为守护来得方便，且 systemd 更加符合普通的单元定义规则
2、目前 Archery 使用的 Inception 数据脱敏，会被子查询击穿规则
### 希望如何解决/实现它
1、添加 archery.service 单元文件，这一做法我已经在本地测试通过，结果如下所示
![捕获](https://user-images.githubusercontent.com/43627142/137430236-2afbd578-ed1e-419f-b017-c02cac9be645.PNG)
如有需要，我这边可以提交 archery.service 单元文件，帮助 Archery 项目改进运维管理
2、我们已经在代码层面直接频闭了子查询，该做法可以作为 bug 修复前的过渡版本，效果如下：
![捕获](https://user-images.githubusercontent.com/43627142/137431770-e1e9b2c5-9dc3-4942-b06e-48f708eed65f.PNG)
是否需要我们提交给社区？

**Comment by LeoQuote** [comment]
第二个可以提pr, 第一个的话仁者见仁吧,  supervisord 只需要 python 不需要系统级的支持. 而且手动部署也没多少人用了, 现在 docker-compose 才是比较方便的部署方式.
