### ISSUE TITLE
[ 功能建议 ]批量导入实例

### ISSUE THREAD

**Issue by linzj3** [hhyo/archer#1196]
### 目前遇到的问题/使用障碍
目前没有接口可以批量导入实例信息
### 希望如何解决/实现它
在前台提供接口，能够批量导入实例信息。
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by 402309718** [comment]
我都是直接插入数据库，( ╯□╰ )

**Comment by nick2wang** [comment]
> 我都是直接插入数据库，( ╯□╰ )

archery已支持实例相关api
https://github.com/hhyo/Archery/wiki/api
