### ISSUE TITLE
[ bug ] mongodb 不支持save语法，改成insert才行

### ISSUE THREAD

**Issue by czxin788** [hhyo/archer#1200]
### 重现步骤
![image](https://user-images.githubusercontent.com/13861904/138207008-b349df0c-22d0-40e4-b9f0-7643acef3ab7.png)
![image](https://user-images.githubusercontent.com/13861904/138207061-a45750c8-4ae2-41e2-897e-e1641bee7003.png)

### 期待结果和实际结果
期待结果：
希望mongodb支持save语法

archery版本：1.8.0

**Comment by fancy-lee** [comment]
这个主要是save方法使用太灵活，很多开发的同学用不好，容易出问题，所以就没有支持

**Comment by czxin788** [comment]
谢谢回复
