### ISSUE TITLE
[ bug ] 在查询页面，mongodb的查询语句后面加分号结尾的话，整个页面都会hang住，永远都查不出来

### ISSUE THREAD

**Issue by czxin788** [hhyo/archer#1201]
在查询页面，mongodb的查询语句后面加分号结尾的话，整个页面都会hang住，永远都查不出来
比如
db.t1.find()
可以查出数据；

但是
db.t1.find();
就不行了，archery整个页面都会hang住，永远查不出来

archery版本：1.8.0

**Comment by weideguo** [comment]
pr #1253 已经处理
