### ISSUE TITLE
[ bug ] 使用模糊条件，批量修改数据时，无法正常生成回滚语句

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1210]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
批量修改数据，使用模糊查询（like）条件时，无法生成回滚语句

### 期待结果和实际结果
期待结果：批量修改数据操作，可正常生成回滚语句

实际结果:

![image](https://user-images.githubusercontent.com/9590209/139805929-ee440e03-1640-43fd-90ab-a38430b5a512.png)

 
### 错误日志

[archery.log](https://github.com/hhyo/Archery/files/7458793/archery.log)
[soar.log](https://github.com/hhyo/Archery/files/7458794/soar.log)

### 版本信息
应用版本/分支：1.8.1
部署方式：Docker

**Comment by peng19832** [comment]
数据库中，也没有相应的记录生成
![image](https://user-images.githubusercontent.com/9590209/139808073-990e7214-2b24-4c33-a35c-aa12def77a4d.png)

**Comment by jimsoft1000** [comment]
公司一般不允许使用like条件做update操作，这种工单，我直接驳回

**Comment by hhyo** [comment]
确认下有影响行数么，执行没有数据受影响不会有备份信息

**Comment by peng19832** [comment]
> 确认下有影响行数么，执行没有数据受影响不会有备份信息

实际update了1行数据，但是没有正常生成回滚语句

**Comment by peng19832** [comment]
> 确认下有影响行数么，执行没有数据受影响不会有备份信息

用主键id做条件，update数据，也生成不了回滚语句，archery.log没有异常日志：
![image](https://user-images.githubusercontent.com/9590209/141880446-9f89bd2b-a9e8-4275-8929-8f2127ff2b10.png)
![image](https://user-images.githubusercontent.com/9590209/141880499-8e38577c-6f4e-4f8c-8507-dc92f2d5befd.png)

**Comment by hhyo** [comment]
确认工单是否开启了备份

**Comment by peng19832** [comment]
> 确认工单是否开启了备份

@hhyo 
开启了，我开启了强制备份，而且奇怪的是貌似只有这一个人的sql，都备份生成回滚sql失败，日志也看不出啥异常。
数据库里，只有执行了的sql，也没有回滚sql。
