### ISSUE TITLE
MSSQL数据库名称，表名称排序[ 功能建议 ]

### ISSUE THREAD

**Issue by jimsoft1000** [hhyo/archer#1212]
### 目前遇到的问题/使用障碍
在1.8.1的版本中，“在线查询”功能中，MSSQL数据库名称，表名称没有排序，建议添加排序

实现方式
修改mssql.py文件

    def get_all_databases(self):
        """获取数据库列表, 返回一个ResultSet"""
        sql = "SELECT name FROM master.sys.databases order by name"
        result = self.query(sql=sql)
        db_list = [row[0] for row in result.rows
                   if row[0] not in ('master', 'msdb', 'tempdb', 'model')]
        result.rows = db_list
        return result

    def get_all_tables(self, db_name, **kwargs):
        """获取table 列表, 返回一个ResultSet"""
        sql = """SELECT TABLE_NAME
        FROM {0}.INFORMATION_SCHEMA.TABLES
        WHERE TABLE_TYPE = 'BASE TABLE' order by TABLE_NAME;""".format(db_name)
        result = self.query(db_name=db_name, sql=sql)
        tb_list = [row[0] for row in result.rows if row[0] not in ['test']]
        result.rows = tb_list
        return result

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
建议提交pr

**Comment by jimsoft1000** [comment]
已提交
