### ISSUE TITLE
[ 问题咨询 ]mongodb SQL审核通过后执行成功，数据没有更新

### ISSUE THREAD

**Issue by calvin2020** [hhyo/archer#1213]
提了个更新mongodb数据的工单，审核通过后，也执行成功了，但是数据没有更新，有人遇到这个问题吗？

archery版本:v1.8.1

**Comment by windyHe2020** [comment]
你解决了吗？我相同版本也碰到这个问题了。

**Comment by calvin2020** [comment]
> 你解决了吗？我相同版本也碰到这个问题了。

没有解决

**Comment by fancy-lee** [comment]
mongo什么版本？执行后的返回的结果是什么？还有日志有没有报错？
