### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by wushuigen** [hhyo/archer#1214]
### 问题描述
使用docker部署，按照文档及命令，部署完成后。SQL在线提交。报需要配置goInception。找到系统配置项，按dome里面的配置，点击测试链接报:
![image](https://user-images.githubusercontent.com/47021825/139826044-eb7bbee5-4e98-4e2a-bf1d-01b398abf6ce.png)

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker

**Comment by hhyo** [comment]
demo配置使用的是host网络模式，使用桥接方式配置容器名即可

**Comment by wushuigen** [comment]
嗯。后面我仔细看文档，有提到配置容器名的说明。已经改成容器名就可以了。非常感谢
