### ISSUE TITLE
[ bug ]用户已授权业务db的读写权限，但是报只读状态的报错。

### ISSUE THREAD

**Issue by linzj3** [hhyo/archer#1215]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1、创建MySQL实例的时候，用普通用户。如test用户对db1有读写权限
2、在SQL上线，任意执行一个DML/DDL操作，如create table db1.t1(id int);insert into db1.t1 values (1),(2);
3、提交SQL执行审核
4、通过审核，并执行SQL
5、报错。
![image](https://user-images.githubusercontent.com/32091009/140022160-1934af38-404e-42d9-99a0-613ff4dd675f.png)
![image](https://user-images.githubusercontent.com/32091009/140022251-58933a8e-ca8e-4b78-b2cd-0da2cdbda712.png)

从后台日志来看，应该是用户对mysql.user表没有select权限导致，而非该实例处于只读模式。

### 期待结果和实际结果
期待结果：

实际结果:

### 版本信息
应用版本/分支：

部署方式：Docker、手工部署

**Comment by peng19832** [comment]
这个报错，看起来像是后端mysql里赔了read_only了吧
