### ISSUE TITLE
[ 功能建议 ] 建议实现DDL和DML语句，可以走不同的审批流程

### ISSUE THREAD

**Issue by czxin788** [hhyo/archer#1218]
### 目前遇到的问题/使用障碍
DML语句主要是业务和开发关注，DBA不需要关注和审批。
只有DDL语句才需要DBA审批

### 希望如何解决/实现它
实现DDL和DML语句，可以走不同的审批流程
### 其他信息
调研其他公司DML DBA不审批，只有DDL DBA才会审批

**Comment by peng19832** [comment]
> ### 目前遇到的问题/使用障碍
> DML语句主要是业务和开发关注，DBA不需要关注和审批。 只有DDL语句才需要DBA审批
> 
> ### 希望如何解决/实现它
> 实现DDL和DML语句，可以走不同的审批流程
> 
> ### 其他信息
> 调研其他公司DML DBA不审批，只有DDL DBA才会审批

有呀，配置自动审批，dml自动通过，其他的语句人工审核
https://github.com/hhyo/archery/wiki/configuration#sql%E4%B8%8A%E7%BA%BF

**Comment by czxin788** [comment]
这个可以做成dml和ddl由两个不同的人工审核吗
比如dml语句由:A--->B--->C人工审核;
ddl语句由：DBA--->A--->B--->C人工审核；

**Comment by peng19832** [comment]
> 这个可以做成dml和ddl由两个不同的人工审核吗 比如dml语句由:A--->B--->C人工审核; ddl语句由：DBA--->A--->B--->C人工审核；

我觉着，其实没啥必要，如果要人工审核，那最终执行的应该是dba。
可以在dba之前，增加一个权限组给，业务审核，或项目主管啥的审核后，再交给dba最终审核执行。
如果语句最终交给其他人审核，要交给谁来执行兜底呢？

**Comment by peng19832** [comment]
dml也就是业务运营人员，修改数据操作，其实dba审核不到什么，可以直接自动通过，业务人员把控执行，平台负责备份回滚。
ddl，研发发起后，可以给项目技术负责人审核是否符合业务需求，最后交给dba审核语句潜在隐患后，执行

**Comment by czxin788** [comment]
嗯，赞同。
不过我们领导让dml也要有人审批确认再执行。
只有ddl才由DBA介入审批

**Comment by peng19832** [comment]
> 嗯，赞同。 不过我们领导让dml也要有人审批确认再执行。 只有ddl才由DBA介入审批

可以建个组，再配一个审核流，走不同的人审核
