### ISSUE TITLE
web界面没有显示ldap相关配置

### ISSUE THREAD

**Issue by Myshiner** [hhyo/archer#1219]
### 问题描述
settings.py的LDAP是开启的，但是没有添加相关具体配置，重启archery后web界面并没有看见LDAP登录选项，且在系统配置中有也没有LDAP的可配置项。
请问LDAP配置是否集成到了web端？文档中只有短短几行说明。

### 版本信息
 - 应用版本/分支：Release v1.8.1  
 - 部署方式：Docker

**Comment by nick2wang** [comment]
直接在settings.py里配置

# LDAP
ENABLE_LDAP = False
if ENABLE_LDAP:
    import ldap
    from django_auth_ldap.config import LDAPSearch

    AUTHENTICATION_BACKENDS = (
        'django_auth_ldap.backend.LDAPBackend',  # 配置为先使用LDAP认证，如通过认证则不再使用后面的认证方式
        'django.contrib.auth.backends.ModelBackend',  # django系统中手动创建的用户也可使用，优先级靠后。注意这2行的顺序
    )

    AUTH_LDAP_SERVER_URI = "ldap://xxx"
    AUTH_LDAP_USER_DN_TEMPLATE = "cn=%(user)s,ou=xxx,dc=xxx,dc=xxx"
    AUTH_LDAP_ALWAYS_UPDATE_USER = True  # 每次登录从ldap同步用户信息
    AUTH_LDAP_USER_ATTR_MAP = {  # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
        "username": "cn",
        "display": "displayname",
        "email": "mail"
    }

**Comment by Myshiner** [comment]
不可以直接在web界面配置吗？

**Comment by FSerKevin** [comment]
建议将LDAP的配置加入到web界面配置 更直观不容易出错

**Comment by LeoQuote** [comment]
ldap 的配置还是比较复杂的, 为了cover 所有可能的清空只能用配置文件配置, 配置文件是 python 写的, 更灵活一些.

另外欢迎 PR

**Comment by Codecaver** [comment]
> ldap 的配置还是比较复杂的, 为了cover 所有可能的清空只能用配置文件配置, 配置文件是 python 写的, 更灵活一些.
> 
> 另外欢迎 PR

请教一下，配置ldap难道不是在.env文件加几个变量就可以了吗？需要写archery/settings.py文件？
