### ISSUE TITLE
sql审核怎么配置

### ISSUE THREAD

**Issue by peixiaoqing** [hhyo/archer#1221]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.8.1  
 - 部署方式：Docker-compose

部署完系统后，在数据库中修改了默认审核参数不生效的问题.
比如： inception_enable_nullable  默认是ON  表示在创建或者新增列时为空则报错，我改成OFF
![image](https://user-images.githubusercontent.com/35130532/140677226-769072f7-506f-43fe-ba14-0a5d3923c1fb.png)
执行Sql 创建表 列可以为空后 报错 列不允许为空，请问这是怎么回事？
![image](https://user-images.githubusercontent.com/35130532/140677395-2ef4aa96-342d-435d-8511-a1629d555cbf.png)

**Comment by peng19832** [comment]
改了以后，要重启一下容器，或进程

**Comment by peixiaoqing** [comment]
![image](https://user-images.githubusercontent.com/35130532/140716535-944b74b6-ac1c-46bc-a309-1ddc2ca7d9b6.png)
你好 我是这种重启的 但是在运行sql时候还是没有生效
![image](https://user-images.githubusercontent.com/35130532/140717322-7f89f001-7071-4276-9f43-64068f35d2c4.png)

**Comment by peixiaoqing** [comment]
你好 我进入的是这个容器，有个goinception容器进不去
`docker exec -it inception /bin/bash `
进入容器后我修改的配置文件
/etc/inc.cnf 
请问我修改的配置文件是否有错
进入数据库我用的是
./opt/inception/debug/mysql/bin/mysql -uroot -h127.0.0.1 -P6669

**Comment by peng19832** [comment]
不是inception，是goninception，配置文件实际是映射的，你一开始部署docker-compose用那个config.toml，你直接改这个配置文件，然后重启就行了

**Comment by peixiaoqing** [comment]
好的，谢谢了 已经解决了这个问题。现在在使用SQl分析时候报错如下：
/bin/sh: -report-type=markdown: command not found
![image](https://user-images.githubusercontent.com/35130532/140910843-0653880d-9e26-4599-ba1f-5223dfede127.png)
这个问题是如何解决呢？

**Comment by peng19832** [comment]
> 好的，谢谢了 已经解决了这个问题。现在在使用SQl分析时候报错如下： /bin/sh: -report-type=markdown: command not found ![image](https://user-images.githubusercontent.com/35130532/140910843-0653880d-9e26-4599-ba1f-5223dfede127.png) 这个问题是如何解决呢？

不支持set参数值吧
![image](https://user-images.githubusercontent.com/9590209/141034964-e73a3f49-dd56-4d3e-9de1-8f442b3a2cb5.png)

**Comment by peixiaoqing** [comment]
你好，谢谢在百忙之中回答问题，我把set值删除了 但是还是报这个错误
![image](https://user-images.githubusercontent.com/35130532/141038292-803b4a0c-9e15-47ca-869b-a77886be8013.png)

**Comment by hhyo** [comment]
参考soar配置，分析依赖soar
