### ISSUE TITLE
MySQL脱敏异常

### ISSUE THREAD

**Issue by zmalyxy** [hhyo/archer#1223]
![image](https://user-images.githubusercontent.com/25155190/140930250-d6b180df-2af9-4266-a508-3b31d025eb6e.png)

![image](https://user-images.githubusercontent.com/25155190/140930321-17a92765-d1b6-4690-a84a-4bc6373a9a6f.png)

请问红框中隐藏的组，是关联哪里的呢，我配置出现了第一个图的报错，大佬指教啊

**Comment by zmalyxy** [comment]
脱敏是无效的，直接查出来原始数据的结果了

**Comment by hhyo** [comment]
配置inception
