### ISSUE TITLE
[ bug ]

### ISSUE THREAD

**Issue by wushuigen** [hhyo/archer#1225]
1、提交表结构增加字段SQL，SQL检查没有问题
2、提交之后报系统自动审核失败，报不允许改变列顺序

![image](https://user-images.githubusercontent.com/47021825/141064123-75483f67-8ac5-4881-bba2-2c5fd9c2b1ed.png)

### 版本信息
应用版本/分支：Release V1.8.1

部署方式：Docker

**Comment by peng19832** [comment]
你开了自动驳回了吧，被命中了，warning不会阻止语句执行，只是提示：
![image](https://user-images.githubusercontent.com/9590209/141086446-93a7f5cd-e810-48f1-9031-4eff82c31356.png)

**Comment by wushuigen** [comment]
经提示，找到配置。确实配置的值为1.警告自动驳回
