### ISSUE TITLE
[ 问题咨询 ] module not found

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1226]
### 问题描述
在学习代码的时候，vsc跑这个错，是改造了，还是移除没用了呢：
![image](https://user-images.githubusercontent.com/9590209/141232118-940cebda-cd89-4cad-9617-66d73939a0d4.png)

### 版本信息
 - 应用版本/分支：Release v1.8.1  
 - 部署方式：Docker

**Comment by hhyo** [comment]
这个是有的依赖的，安装下即可

**Comment by peng19832** [comment]
哦，那关了吧
