### ISSUE TITLE
[ 问题咨询 ]权限级别下拉只有DATABASE权限，没有TABLE权限

### ISSUE THREAD

**Issue by venlentine** [hhyo/archer#1227]
### 问题描述
Postgres库，申请权限的时候，权限级别下拉只有DATABASE权限，没有TABLE权限

后台管理的时候，编辑这条申请记录，又可以看到TABLE权限

试过chrome，firefox，edge浏览器都不显示

是否还有哪里配置的地方没有找到，谢谢指导

### 版本信息
 - Archery (v1.8.1)
 - 部署方式：Docker
 - postgres:13.4

![Dingtalk_20211111143018](https://user-images.githubusercontent.com/3379347/141249328-16fe030e-2060-4615-bfce-ce21f67e1345.jpg)

后台管理

![Dingtalk_20211111143554](https://user-images.githubusercontent.com/3379347/141249740-eed49c3b-c291-4e4f-af80-f25025957dce.jpg)

**Comment by maxianwei** [comment]
pgsql目前只能授权到库一级别。
