### ISSUE TITLE
[ bug ]SQL缩略乱码问题修复

### ISSUE THREAD

**Issue by ocpeng** [hhyo/archer#1231]
### bug现象
v1.8.1版本，缩略SQL/回滚SQL截取会出现乱码，原始转义后截取不完整导致，如图：
![image](https://user-images.githubusercontent.com/43569914/141415713-280a6d37-1d56-44ef-8960-3e607e3bd031.png)

### 代码修复
修复逻辑：缩略SQL不走value，直接走真实的row.sql进行截取
```
vim /data/deploy/Archery-master/sql/templates/detail.html 
                    formatter: function (value, row, index) {
                        var sql=row.sql;
                        if (sql.length > 80) {
                            return sql.substr(0, 80) + '...';
                        } else {
                            return sql
                        }
                    },
```

### 修复效果
![image](https://user-images.githubusercontent.com/43569914/141416017-1ebcdf8a-6513-4318-ac47-fd6c51c4417b.png)

**Comment by hhyo** [comment]
辛苦直接提交pr

**Comment by hhyo** [comment]
fix in #1305
