### ISSUE TITLE
[ 问题咨询 ] 我想实现飞书订阅archery审批流，请求地址怎么写

### ISSUE THREAD

**Issue by czxin788** [hhyo/archer#1232]
### 问题描述
我想在飞书上点击个同意，就能完成archery工单的审批。
避免登录archery再审批的麻烦。
类似这样子：
![image](https://user-images.githubusercontent.com/13861904/141423445-67ef47a8-04a1-47b9-9fe6-c54e1c23b54f.png)

于是我参考
https://open.feishu.cn/document/ukTMukTMukTM/uUTNz4SN1MjL1UzM
但是我填入咱们archery的地址，报错，请问我应该怎么做才对：
![image](https://user-images.githubusercontent.com/13861904/141423882-ecfa3599-9316-4274-8561-0f503a1c5542.png)

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
最近我也正好在做飞书相关的事情, 你要做到这个效果, 目前 archery 的状况是做不到的, 现在 archery 只有单向往飞书推送的功能, 如果你要做到这一点, 需要额外做一个 app 来接两边的消息, 主要两个功能

1. 接收 archery 这边的事件, 然后根据需要发送消息给飞书
2. 接收 飞书这边的互动事件, 然后根据事件调 archery 的接口.

archery 现在没有现成的接口, 也没有现成的配置webhook 的方法, 要做的工作还多着呢

**Comment by czxin788** [comment]
好的，谢谢解答。

**Comment by hhyo** [comment]
感觉至少还是要看下SQL内容和影响范围，不过大多数审批都是流于形式
