### ISSUE TITLE
mongodb执行时出现WARNING的优化

### ISSUE THREAD

**Issue by weideguo** [hhyo/archer#1237]
### 目前遇到的问题/使用障碍
使用mongo命令连接部分mongodb实例时会出现告警，从而导致部分函数执行失败如 [get_slave](https://github.com/hhyo/Archery/blob/v1.8.1/sql/engines/mongo.py#L290)
``` 
WARNING: slaveOk() is deprecated and may be removed in the next major release. Please use secondaryOk() instead.
```

### 希望如何解决/实现它
增加一个补丁 mongo.py.20211117.patch

```
diff --git a/sql/engines/mongo.py b/sql/engines/mongo.py
index 8e7143f..86e7c99 100644
--- a/sql/engines/mongo.py
+++ b/sql/engines/mongo.py
@@ -271,7 +271,18 @@ class MongoEngine(EngineBase):
                 re_msg = []
                 for line in iter(p.stdout.read, ''):
                     re_msg.append(line)
-                msg = '\n'.join(re_msg)
+
+                __msg = '\n'.join(re_msg)
+
+                _re_msg = []
+                for _line in __msg.split('\n'):
+                    if not _re_msg and re.match('WARNING.*', _line):
+                        # 第一行可能是WARNING语句，因此跳过
+                        continue
+                    _re_msg.append(_line)
+
+                msg = '\n'.join(_re_msg)
+
             except Exception as e:
                 logger.warning(f"mongo语句执行报错，语句：{sql}，{e}错误信息{traceback.format_exc()}")
         return msg
 
```
应用补丁
``` shell
patch -p1 < mongo.py.20211117.patch
```

**Comment by weideguo** [comment]
不应该贸然把 `slaveOk()` 改成 `secondaryOk()`，因为有些mongodb实例不支持后者

**Comment by peng19832** [comment]
> ### 目前遇到的问题/使用障碍
> 使用mongo命令连接部分mongodb实例时会出现告警，从而导致部分函数执行失败如 [get_slave](https://github.com/hhyo/Archery/blob/v1.8.1/sql/engines/mongo.py#L290)
> 
> ```
> WARNING: slaveOk() is deprecated and may be removed in the next major release. Please use secondaryOk() instead.
> ```
> 
> ### 希望如何解决/实现它
> 增加一个补丁 mongo.py.20211117.patch
> 
> ```
> diff --git a/sql/engines/mongo.py b/sql/engines/mongo.py
> index 8e7143f..86e7c99 100644
> --- a/sql/engines/mongo.py
> +++ b/sql/engines/mongo.py
> @@ -271,7 +271,18 @@ class MongoEngine(EngineBase):
>                  re_msg = []
>                  for line in iter(p.stdout.read, ''):
>                      re_msg.append(line)
> -                msg = '\n'.join(re_msg)
> +
> +                __msg = '\n'.join(re_msg)
> +
> +                _re_msg = []
> +                for _line in __msg.split('\n'):
> +                    if not _re_msg and re.match('WARNING.*', _line):
> +                        # 第一行可能是WARNING语句，因此跳过
> +                        continue
> +                    _re_msg.append(_line)
> +
> +                msg = '\n'.join(_re_msg)
> +
>              except Exception as e:
>                  logger.warning(f"mongo语句执行报错，语句：{sql}，{e}错误信息{traceback.format_exc()}")
>          return msg
>  
> ```
> 
> 应用补丁
> 
> ```shell
> patch -p1 < mongo.py.20211117.patch
> ```

大佬，能加个版本判断不，老版本用slaveok，新版本用新的命令

**Comment by weideguo** [comment]
执行前加版本判断太不优雅

**Comment by hhyo** [comment]
可提pr，谢谢
