### ISSUE TITLE
redis-cluster 模式报错[ bug ]

### ISSUE THREAD

**Issue by fenglei1230** [hhyo/archer#1238]
<html>
<body>

Error
--
MOVED 5869 ap-test-redis-cluster-02-0001-001.ap-test-redis-cluster-02.nzg8qz.apse1.cache.amazonaws.com:6379

查了下大概意思是客户端连接需要 redis-cli  -p 6379 -c 指定cluster 模式 

</body>
</html>

**Comment by hhyo** [comment]
当前应该不支持集群模式连接

**Comment by fenglei1230** [comment]
能帮着改改么 大神

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月19日(周五) 上午8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hhyo/Archery] redis-cluster 模式报错[ bug ] (Issue #1238)




 
当前应该不支持集群模式连接
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tcgdy0201** [comment]
> 当前应该不支持集群模式连接

求新增特性

**Comment by nick2wang** [comment]
solved by #1392
