### ISSUE TITLE
[ 功能建议 ] 有没有 datagrip 接入方式，生产环境的只读，每次页面查询太痛苦了

### ISSUE THREAD

**Issue by lhsaq2009** [hhyo/archer#1240]
有没有 datagrip 接入方式，生产环境的只读，每次页面查询太痛苦了

**Comment by peng19832** [comment]
工具连接，单独授权一个只读账号，绑定ip，不就可以了哇

**Comment by lhsaq2009** [comment]
问题是上市公司，涉及审计。生产环境连只读都不给开放呀。
页面查询太费劲了，

**Comment by peng19832** [comment]
> 问题是上市公司，涉及审计。生产环境连只读都不给开放呀。 页面查询太费劲了，

我觉着，这种算是开后门，你都说不开放了，又想单独开接口。
你还可以申请一个工作机，装上工具，在工作机查数据。

**Comment by yanstoo** [comment]
> > 问题是上市公司，涉及审计。生产环境连页面都不给开放呀。
> 
> 我觉着，这种诡异的开后门，你都已经不开放了，又想单独开接口。 你还可以申请一个工作机，安装工具，在工作机查数据。
这感觉不算开后门，开发一个datagrip插件，由datagrip通过Archery建立连接，并做查询等操作，所有的操作还是会在Archery中做记录和审计
