### ISSUE TITLE
[ 功能建议 ] 建议页面的表格，列宽可以拖动调整，尤其工单详情页和回滚sql的

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1248]
### 目前遇到的问题/使用障碍
页面上的展示表格，列宽都是固定的，无法调整，遇到比较长的内容，体验很难受

### 希望如何解决/实现它
希望可以拖动调整表格列宽，内容可以自动换行

### 其他信息
![image](https://user-images.githubusercontent.com/9590209/143407406-e42dc1d0-14d8-4696-b48f-bc23a30f48b4.png)

**Comment by hhyo** [comment]
这是特意调整，自动换行后整个页面展示信息量会很有限，大部分的语句都是比较长

**Comment by peng19832** [comment]
> 这是特意调整，自动换行后整个页面展示信息量会很有限，大部分的语句都是比较长

其实，很多情况，只是想对比下回滚sql与执行sql中的值，是否正确，如果自动换行，两个展示列可以并列展示，就比较方便看到sql前后的值了，现在这个固定列宽，就只能，手工粘出来对比，有点不方便
