### ISSUE TITLE
[ bug ] oracle无法生成ddl回滚sql，还会打出不相关的语句

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1249]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：增长生成ddl和dml回滚sql，不打印不相关的语句

实际结果:
![image](https://user-images.githubusercontent.com/9590209/143408172-a2e7bded-d575-4d0c-b4e7-a1ae93e1e90b.png)
![image](https://user-images.githubusercontent.com/9590209/143408295-4f2dc834-ce56-47ef-a4ae-e0638ff26ad5.png)

 
### 版本信息
应用版本/分支：1.8.1

部署方式：Docker

**Comment by peng19832** [comment]
update语句，回滚语句错误：
![image](https://user-images.githubusercontent.com/9590209/144819950-47f336ef-d379-4d31-a9bb-17a9ec481fce.png)
![image](https://user-images.githubusercontent.com/9590209/144819984-60210573-d917-4212-88b7-972e69fe13d8.png)

**Comment by tanglu86** [comment]
请问oracle回滚功能是在哪儿配置的呢
