### ISSUE TITLE
[ bug ] 查询DECIMAL(65, 0)数据前端展示错误

### ISSUE THREAD

**Issue by pythhhon** [hhyo/archer#1250]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1.发现 Archery SQL 数据查询工具对数值类型的字段有显示错误
select * from x where amount = '186322984999999995904'

### 期待结果和实际结果
期待结果：
查出来的amount值应该为186322984999999995904
实际结果:
![image](https://user-images.githubusercontent.com/21304437/143425919-6dea0303-bd79-4134-9d4f-27b5240a9946.png)

### 截图
如上

 
### 版本信息
应用版本/分支：
Release v1.8.1
部署方式：Docker

**Comment by weideguo** [comment]
应该是前端boostrap的处理出现错误，可能需要转成字符串以避免这个错误
![1637926407(1)](https://user-images.githubusercontent.com/3381137/143574901-f70bd10c-6962-4d9f-9a1d-374a724ee75c.jpg)

**Comment by hhyo** [comment]
查询结果中有做bigint_as_string的处理，可以确认下相关逻辑

**Comment by pythhhon** [comment]
> 查询结果中有做bigint_as_string的处理，可以确认下相关逻辑
是说这段代码吗？目前有看到这个逻辑，但实际情况并没起作用？
return HttpResponse(json.dumps(result, cls=ExtendJSONEncoderFTime, bigint_as_string=True),
                            content_type='application/json')
