### ISSUE TITLE
[ 功能建议 ] 用户认证，如果用ldap，那后续修改密码等动作，能否通过接口直接修改ldap端信息

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1256]
### 目前遇到的问题/使用障碍
启用ldap后，虽然可以拉取账号列表，但如果用户修改密码后，就与ldap脱钩了，无法再与ldap联动

### 希望如何解决/实现它
启用ldap后，用户修改个人信息/密码时，通过接口直接更新ldap端信息。

### 其他信息
无

**Comment by hhyo** [comment]
走ldap登录的用户，archery并没有保存密码，修改密码操作仅限于本地认证，其他方式建议调整下，关闭改密入口
