### ISSUE TITLE
binlog2sql生成的反向sql只有20行

### ISSUE THREAD

**Issue by AgsTing** [hhyo/archer#1257]
delete后，范围控制设置为100条，勾选保存到文件（异步操作），生成的反向insert sql只有20条，实际有1000+条，到保存的文件中查看也只有20条，帮看下哪里做了限制，是否可以放开
![image](https://user-images.githubusercontent.com/21080274/144219773-9fba4f0a-295b-4f88-9f00-c9c0212d8ce3.png)

**Comment by peng19832** [comment]
> delete后，范围控制设置为100条，勾选保存到文件（异步操作），生成的反向insert sql只有20条，实际有1000+条，到保存的文件中查看也只有20条，帮看下哪里做了限制，是否可以放开 ![image](https://user-images.githubusercontent.com/21080274/144219773-9fba4f0a-295b-4f88-9f00-c9c0212d8ce3.png)

确实有这个问题，我也遇到了，手工用my2sql、或者美团的myflash可以先解决

**Comment by nick2wang** [comment]
我试了下无法重现问题，另外代码里解析范围控制只控制返回给前端的结果数量，生成sql是通过django_q异步执行的，并没有进行过滤

**Comment by AgsTing** [comment]
> 我试了下无法重现问题，另外代码里解析范围控制只控制返回给前端的结果数量，生成sql是通过django_q异步执行的，并没有进行过滤

**Comment by AgsTing** [comment]
> 我试了下无法重现问题，另外代码里解析范围控制只控制返回给前端的结果数量，生成sql是通过django_q异步执行的，并没有进行过滤

此问题仍然存在，方便的话，可以远程帮看下@nick2wang

**Comment by AgsTing** [comment]
archery目前的binlog2sql无法使用，采用一楼@peng19832的建议，手动解决
