### ISSUE TITLE
[ 问题咨询 ]mongo SQL查询，点击 ‘查看集合字段’ 时报错

### ISSUE THREAD

**Issue by zancers** [hhyo/archer#1258]
### 问题描述
mongo查询失败

web报错截图：

![screenshot1s](https://user-images.githubusercontent.com/39722046/144379862-f964f9bc-9b9b-4954-ba88-302316772dc0.png)

日志截图：
![screenshots](https://user-images.githubusercontent.com/39722046/144379960-54a85435-b6a3-4050-9a21-9b8a54133968.png)

### 版本信息
 - 应用版本/分支：Release v1.8.0 
 - 部署方式：手工部署

**Comment by zancers** [comment]
mongo SQL查询，点击 ‘查看集合字段’ 时报错

**Comment by nick2wang** [comment]
我猜你是用的AWS的DocumentDB 3.6以下版本？DocumentDB只支持部分mongo api（整体更接近mongo3.0或3.2），pymongo获取集合字段用到$natural自然排序，这个feature在最近的docDB 3.6和4.0才得到支持
https://aws.amazon.com/about-aws/whats-new/2021/05/amazon-documentdb-improves-mongodb-compatibility-and-indexing-improvements/?nc1=h_ls

**Comment by feiazifeiazi** [comment]
me,too!
using  Amazon DocumentDB 4.0.0
