### ISSUE TITLE
[ 问题咨询 ]mongodb不支持explain语法

### ISSUE THREAD

**Issue by czxin788** [hhyo/archer#1260]
### 问题描述
mongodb不支持explain语法：
![image](https://user-images.githubusercontent.com/13861904/144552817-d7e51b97-4b80-4650-88f0-491edd4c97a1.png)

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker

**Comment by weideguo** [comment]
底层依赖于pymongo实现，pymongo不支持这样的用法，改成 db.what_you_collection_name.find(...).explain()，或者直接用web界面的“执行计划”

**Comment by czxin788** [comment]
这个是聚合函数aggregate的语法，如果用find就不符合业务需求。

**Comment by weideguo** [comment]
pymongo也确实不支持 db.what_you_collection_name.aggregate(...).explain()

**Comment by czxin788** [comment]
谢谢，明白了，多谢回复
