### ISSUE TITLE
[ bug ] 文档nginx配置更新

### ISSUE THREAD

**Issue by hiflycat** [hhyo/archer#1265]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
新版本1.8.2supervisord.conf
![image](https://user-images.githubusercontent.com/25202901/144781524-b0bacb62-5f69-4dce-849e-3cd04944eaeb.png)
端口改成了8888
但是老版本安装文档nginx还是8000端口
![image](https://user-images.githubusercontent.com/25202901/144781466-d7938eac-984f-42e7-922f-09b2243aa9f9.png)

### 期待结果和实际结果
期待结果：

实际结果:

### 版本信息
应用版本/分支：

部署方式：Docker、手工部署

**Comment by hhyo** [comment]
这个改动比较久远了，可以帮忙更新下wiki
