### ISSUE TITLE
[ 功能建议 ]扩充数据库的host name字段，目前aws数据库提示超长for host name (should be no longer than 60)

### ISSUE THREAD

**Issue by zancers** [hhyo/archer#1268]
### 目前遇到的问题/使用障碍
配置aws数据库实例进行脱敏查询时报，以下为修改源码后调试的日志打印
{'ID': 1, 'stage': 'NONE', 'errlevel': 2, 'stagestatus': 'None', 'errormessage': "String 'dbdbdbdbdbdbdbdbdbdbdb.sxxxxxx.rds.amazonaws.com' is too long for host name (should be no longer than 60).", 'SQL': 'Global environment', 'Affected_rows': 0, 'sequence': 'None', 'backup_dbname': 'None', 'execute_time': '0', 'sqlsha1': 'None'}

### 希望如何解决/实现它
将相关字段加长

**Comment by hhyo** [comment]
更换goinception审核，不会有这个问题
