### ISSUE TITLE
[ 功能建议 ] 是否支持polardb

### ISSUE THREAD

**Issue by Arealm** [hhyo/archer#1271]
### 目前遇到的问题/使用障碍
阿里云polardb现在是否支持啊
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hydgladiator** [comment]
支持的。亲测可行
<img width="312" alt="image" src="https://user-images.githubusercontent.com/13326206/146885018-37159a20-83bf-40d0-8741-146a68ea542e.png">
