### ISSUE TITLE
[ 问题咨询 ] 归档显示成功，但是源数据没有删除

### ISSUE THREAD

**Issue by maxianwei** [hhyo/archer#1273]
### 问题描述
使用归档工具进行归档,归档模式为直接删除，归档条件为id >5 。
但是我执行后显示成功了，实际上id>5的数据还在。

![image](https://user-images.githubusercontent.com/34542869/145369648-552ea09d-9ec0-4cc7-bb9d-f97148299a6b.png)
![image](https://user-images.githubusercontent.com/34542869/145369697-23bbfc97-a4d3-4f46-90bf-91ad8ffc628c.png)

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker

**Comment by maxianwei** [comment]
我试了下归档到文件，实际也没有这个归档文件。
![image](https://user-images.githubusercontent.com/34542869/145372569-87509de8-1a0e-4943-8430-055d453308bb.png)

**Comment by maxianwei** [comment]
又试了几次，这个工具好像是默认会保留一条记录。多插入几条数据，就可以了。（最后一条记录会被保留）

**Comment by maxianwei** [comment]
但是现在又有一个新问题，当我归档到文件的时候，显示执行成功，但是归档目录里没有相应的文件。
![image](https://user-images.githubusercontent.com/34542869/145383757-1dcf996a-1623-417c-84cc-7cd36b0c9dbf.png)
请问有人遇到过这种情况吗？

**Comment by maxianwei** [comment]
这个是不是因为我的数据量太少，我看有个--limit参数，指定每条语句获取表和归档表的行数。没到行数所以没归档。

**Comment by hhyo** [comment]
可以看下pt相关文档，单独运行验证下

**Comment by swords1999** [comment]
这个是pt-archiver工具的bug，网上搜办法

**Comment by maxianwei** [comment]
pt-archiver会保证表内最少保留1条数据，即便这条数据符合归档的条件。

**Comment by maxianwei** [comment]
参考： https://www.jianshu.com/p/21847e46d226

**Comment by maxianwei** [comment]
参考：https://blog.csdn.net/weixin_34195546/article/details/91697893

**Comment by kleinla** [comment]
如何能把参数nosafe-auto-increment 加上去
