### ISSUE TITLE
Archery-1.8.1版本提交DML可以执行，备份报错

### ISSUE THREAD

**Issue by shuaishuai8147** [hhyo/archer#1274]
### 问题描述
DDL可以备份成功，
DML可以成功执行但是备份失败
报错
Backup: io.ReadFull(header) failed. err EOF: connection was bad.
### 版本信息
 - 应用版本/分支：Archery-1.8.1
 - 部署方式：手工部署

**Comment by wushuigen** [comment]
碰到一样的问题，已经执行。在查看回滚SQL时出错
![image](https://user-images.githubusercontent.com/47021825/150301365-03ed6f0c-9e8e-4dc4-901f-d9ef8b36d4e5.png)

应用版本/分支：Release V1.8.1

部署方式：Docker

**Comment by hhyo** [comment]
系统配置中配置正确的goiception信息
