### ISSUE TITLE
[ 问题咨询 ] 查询数据导致服务hang住

### ISSUE THREAD

**Issue by lijie861221** [hhyo/archer#1277]
### 问题描述
高使用率情况下，查询postgresql数据库，有慢sql等待数据库返回的时候，其他人无法查询也无法登陆。

场景再现步骤：
打开一个查询页面，模拟慢sql：执行select pg_sleep(120);
再打开一个查询页面，一直加载不出来，直到超时后才恢复。

### 版本信息
 - 应用版本/分支：Release v1.8.2
 - 部署方式：Docker

**Comment by hhyo** [comment]
目前这块还是阻塞式的，可以调整下worker数
https://github.com/hhyo/Archery/blob/604943cb59ea1149bf6651266bc389b4d965b4bc/src/docker/startup.sh#L26

**Comment by lijie861221** [comment]
> 目前这块还是阻塞式的，可以调整下worker数
> 
> https://github.com/hhyo/Archery/blob/604943cb59ea1149bf6651266bc389b4d965b4bc/src/docker/startup.sh#L26

修改后，试了一下，还是不行。是不是还有其他参数要配合着一起调整？

**Comment by hhyo** [comment]
不需要其他的调整，除非是debug模式起来的
