### ISSUE TITLE
[ 功能建议 ] 建议对在线查询请求参数进行编码

### ISSUE THREAD

**Issue by LB-J** [hhyo/archer#1278]
### 目前遇到的问题/使用障碍
在客户内网环境使用过程中发现无法进行sql 查询操作，经过多方面排查发现 select 关键字被客户的防火墙屏蔽掉了，导致无法提交带有select 关键字的请求。

### 希望如何解决/实现它
目前我是通过在代码中进行关键字replace，前端使用querying 替换select，后端通过replace 进行替换来临时解决。
建议可以在前端对提交的sql 内容进行加密，后端再进行解密操作。

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
试试用urlencode是否可行，可以的话可以提交个pr

**Comment by hhyo** [comment]
单纯识别select字符串应该使用bsae64或hex都可以解决
