### ISSUE TITLE
[ bug ]手动执行完成的工单不会发送通知

### ISSUE THREAD

**Issue by sona-yuan** [hhyo/archer#1284]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：

实际结果:

### 版本信息
应用版本/分支：

部署方式：Docker、手工部署

**Comment by nick2wang** [comment]
手工执行没有进入回调通知
