### ISSUE TITLE
check_identifier_lower 参数设置不生效

### ISSUE THREAD

**Issue by wujianwei11** [hhyo/archer#1286]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
goinception开启参数
##检测表或则字段名称必须为小写,false表示不检查
[root@tidb04 config]# grep check_identifier_lower  config.toml
check_identifier_lower = true

Archery-1.8.0 版本
goInception  版本：
[root@tidb04 soft]# ./goInception  -V
Release Version: v1.2.4-92-g5273274-dirty
Git Commit Hash: 5273274d52babfe9b38537f37c83e95ac4d027d3
Git Branch: master

archery系统DDL建表,指定个别关键字段为大写字符
![Y4J_T 9 KH9Y$ X}Z M`LGW](https://user-images.githubusercontent.com/19167973/146338236-3929b784-9131-4d15-8342-9c3f1e5adde3.png)

具体建表sql如下:
CREATE TABLE `t_class01` (
  `id` int (11) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `SHid` int (11) NOT NULL COMMENT '商店ID',
  `GTID` int (11) NOT NULL COMMENT '物品ID',
  `type1` tinyint (1) NOT NULL COMMENT '支付方式',
  `price` int (10) NOT NULL COMMENT '物品价格',
  `comment1` varchar (200) NOT NULL COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT '1970-01-01' COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_price` (`price`),
  KEY `idx_type` (`type1`)
) ENGINE=InnoDB COMMENT='员工入职关系表';

部署方式：手工部署

**Comment by hhyo** [comment]
#1287
