### ISSUE TITLE
goinception 配置文件审核规则参数不生效问题

### ISSUE THREAD

**Issue by wujianwei11** [hhyo/archer#1287]
goinception 配置文件审核规则参数不生效问题:

##检测表或则字段名称必须为小写,false表示不检查
check_identifier_lower = true

### 期待结果和实际结果
期待结果：

期待结果是直接不允许提交大写字符的字段

实际结果:
### 截图
![Y4J_T 9 KH9Y$ X}Z M`LGW](https://user-images.githubusercontent.com/19167973/146339644-90ade5a2-14ad-47f6-9bd3-21fd704c2047.png)

日志没有报错

应用版本/分支：
Archery-1.8.0 版本

[root@tidb04 soft]# ./goInception  -V
Release Version: v1.2.4-92-g5273274-dirty
Git Commit Hash: 5273274d52babfe9b38537f37c83e95ac4d027d3
Git Branch: master

部署方式：手工部署

**Comment by hhyo** [comment]
可以尝试更新下goinception版本
