### ISSUE TITLE
[ 功能建议 ] 实例排序优化

### ISSUE THREAD

**Issue by RankRao** [hhyo/archer#1290]
在【SQL查询】【慢查日志】【会话管理】等页面的选择主机列表，目前是按照id排序的，可以按照名称排序吗？这样相似名称或者相似项目的主机就会排在一起了，而不是目前的散乱分布

**Comment by nick2wang** [comment]
麻烦在于人为设置的实例名称可能包含数字字母和汉字，而mysql使用utf8字符集时默认对汉字的排序是无效的，django orm又不支持`convert(instance_name using gbk)`语法

**Comment by LeoQuote** [comment]
@nick2wang 前端实现可能会简单一点

**Comment by nick2wang** [comment]
> @nick2wang 前端实现可能会简单一点

找到一个可行的方法修改了下，后面如果有用到汉字排序也方便复用
https://stackoverflow.com/questions/38517743/django-how-to-make-a-query-with-order-by-convert-name-using-gbk-asc
