### ISSUE TITLE
redis不支持hash查询？

### ISSUE THREAD

**Issue by doing-cr7** [hhyo/archer#1295]
![image](https://user-images.githubusercontent.com/63889450/147244007-b616547e-7727-496d-bcd2-8d6f4bf21eb4.png)

**Comment by unknowissue** [comment]
你是哪个版本的？
我测试1.8.2是支持的
![Snipaste_2021-12-25_09-15-35](https://user-images.githubusercontent.com/76696174/147375383-f8ac4671-7838-4e5b-9544-68130ae6a62c.png)

**Comment by doing-cr7** [comment]
> 你是哪个版本的？ 我测试1.8.2是支持的 ![Snipaste_2021-12-25_09-15-35](https://user-images.githubusercontent.com/76696174/147375383-f8ac4671-7838-4e5b-9544-68130ae6a62c.png)

我是1.8.0

**Comment by unknowissue** [comment]
> > 你是哪个版本的？ 我测试1.8.2是支持的 ![Snipaste_2021-12-25_09-15-35](https://user-images.githubusercontent.com/76696174/147375383-f8ac4671-7838-4e5b-9544-68130ae6a62c.png)
> 
> 我是1.8.0

,,,版本有点老啊，升级到最新吧。

**Comment by LT519** [comment]
> ![image](https://user-images.githubusercontent.com/63889450/147244007-b616547e-7727-496d-bcd2-8d6f4bf21eb4.png)

你好 我想问下 archery上查询时redis怎么选择数据库的 实例配置中我设置了默认数据库为0 但是查询的时候 无法选择是怎么回事？
![image](https://user-images.githubusercontent.com/31436779/178430420-dee96a4b-bd90-473a-a443-b98b7f601168.png)

**Comment by LT519** [comment]
archery版本是v1.8.2

**Comment by LeoQuote** [comment]
再升一升, 你升到最新版再说
