### ISSUE TITLE
[ 功能建议 ]希望能有多个窗口查询功能

### ISSUE THREAD

**Issue by flag2018** [hhyo/archer#1296]
### 目前遇到的问题/使用障碍
目前单个窗口不能查询多个表
### 希望如何解决/实现它
目前想要实现单个浏览器页面实现多个窗口查询，实现多个不同的数据库和表查询
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交
目前Yearning运维平台有这个功能
<img width="904" alt="截屏2021-12-24 上午10 05 19" src="https://user-images.githubusercontent.com/96603393/147306847-2e62b790-60ce-4e78-a333-155c60b0c86e.png">

**Comment by hhyo** [comment]
已有增加窗口的功能

**Comment by flagship2018** [comment]
好的，但是我没有找到相关的功能，在那个地方新增窗口的？

**Comment by flagship2018** [comment]
可是我在在线体验上没看到多个窗口的功能
<img width="1402" alt="截屏2021-12-27 上午8 55 41" src="https://user-images.githubusercontent.com/38875288/147424280-3c1dd2d0-47ab-43c8-bf4d-7d2de562b4d4.png">

**Comment by eryajf** [comment]
请问现在这个功能是否支持了呢

**Comment by flagship2018** [comment]
您的邮件我已经收到，祝您生活愉快！
