### ISSUE TITLE
[ 功能建议 ]增加查询窗口或者单窗口查询多条sql

### ISSUE THREAD

**Issue by ihoooooo** [hhyo/archer#1297]

**Comment by flagship2018** [comment]
对的，我之前也提了一个问题，要在sql查询界面可以增加多个tab更好，现在只有一个tab
<img width="1402" alt="截屏2021-12-27 上午8 55 41" src="https://user-images.githubusercontent.com/38875288/147424782-1c71fc33-bf34-415c-ab9c-9af8c6907dd1.png">

**Comment by flagship2018** [comment]
我看另外一个开源组件Yearning是有这个功能的，如下图：
<img width="894" alt="截屏2021-12-27 上午9 12 23" src="https://user-images.githubusercontent.com/38875288/147424840-c84158bc-dbbe-408c-ba66-657048d333d7.png">

**Comment by hhyo** [comment]
看查询结果的右侧，有+  - 对应的就是增删窗口

**Comment by flagship2018** [comment]
您的邮件我已经收到，祝您生活愉快！

**Comment by flagship2018** [comment]
您的邮件我已经收到，祝您生活愉快！

**Comment by lizhiyoumai** [comment]
> 看查询结果的右侧，有+ - 对应的就是增删窗口

但是这个得手动添加，能做到自动开启新窗口么？

**Comment by flagship2018** [comment]
您的邮件我已经收到，祝您生活愉快！
