### ISSUE TITLE
1.8.1版本，执行腾讯云RDS mysql8版本，最基础的查询语句失败！！！！！

### ISSUE THREAD

**Issue by mengerwei** [hhyo/archer#1301]
1.部署方式docker-compose 部署完成。
2.archery:1.8.1版本
3.连接腾讯云的RDS mysql 8版本
4.goInception配置  为docker 容器内ip：4000端口。
5.navicat执行mysql查询完成，复制粘贴到archery查询。
------------------------------------
查询语句：
SELECT * from `swift-app`.market_instruction;

查看容器goinception日志：

time="2021/12/27 18:03:26.536" level=error msg="con:18 解析失败! line 1 column 48 near \"-app.rpa_app\" " file=session_inception.go func=executeInc line=219
time="2021/12/27 18:03:26.536" level=error msg="                            select * from swift-app.rpa_app" file=session_inception.go func=executeInc line=220
time="2021/12/27 18:03:32.254" level=error msg="con:19 解析失败! line 1 column 48 near \"-app.rpa_app\" " file=session_inception.go func=executeInc line=219
time="2021/12/27 18:03:32.254" level=error msg="                            select * from swift-app.rpa_app" file=session_inception.go func=executeInc line=220

**Comment by peng19832** [comment]
对象名里有中划线的，不是要用反撇号引起来吗？你这个报错是语法错误呀

**Comment by mengerwei** [comment]
![image](https://user-images.githubusercontent.com/24802170/147520094-b1a65a99-a607-4860-ba95-acdcaeb22aef.png)

**Comment by mengerwei** [comment]
前后都带引号，测试：

![image](https://user-images.githubusercontent.com/24802170/147520373-58afa041-b1f3-4d8f-9a9d-6a8623bbda3d.png)

**Comment by mengerwei** [comment]
前后都带反引号，带分号；

![image](https://user-images.githubusercontent.com/24802170/147520508-30d0ea25-13ec-4b24-a520-f9049acd681b.png)

**Comment by mengerwei** [comment]
在线查询执行是成功的，但是上线sql就不行，是不是dml语法中不包含select？

![image](https://user-images.githubusercontent.com/24802170/147521624-52f3f28b-6ddf-4142-b676-1a9ce818a31c.png)

**Comment by nick2wang** [comment]
报错写的很清楚了，上线只支持DDL和DML，select属于DQL，要查询直接去在线查询即可

**Comment by mengerwei** [comment]
> 报错写的很清楚了，上线只支持DDL和DML，选择DQL，要直接去在线查询检测

你这说法牵强，我要是不把测试结果发出来看，你就不会这么说了。只是说问题我找到了，但是Archery 这产品设计是怎么划分语句的？

我不敢打保票说100%的DBA，至少从mysql 5.5 过来的80%的dba，传统意识里select 都和dml 绑定在一起。

**Comment by nick2wang** [comment]
> > 报错写的很清楚了，上线只支持DDL和DML，选择DQL，要直接去在线查询检测
> 
> 你这说法牵强，我要是不把测试结果发出来看，你就不会这么说了。只是说问题我找到了，但是Archery 这产品设计是怎么划分语句的？
> 
> 我不敢打保票说100%的DBA，至少从mysql 5.5 过来的80%的dba，传统意识里select 都和dml 绑定在一起。

首先select算不算dml这个确实有争议，但是根据是否修改了数据来看，业内早就把select和insert/update/delete分开对待了；其次archery的设计便是将select排除出dml，代码如下；最后，并不是你不知道别人就不知道。
https://github.com/hhyo/Archery/blob/02c8d8d3f5068e89813997bede36317a57d39520/sql/engines/mysql.py#L268-L273

**Comment by nick2wang** [comment]
[https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_dml](url)

> Data manipulation language, a set of SQL statements for performing INSERT, UPDATE, and DELETE operations. The SELECT statement is sometimes considered as a DML statement, because the SELECT ... FOR UPDATE form is subject to the same considerations for locking as INSERT, UPDATE, and DELETE.

来自mysql官方手册的解释：dml通常包括insert/update/delete，select在select ... for update时才被看作是dml。

**Comment by mengerwei** [comment]
> [https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_dml](url)
> 
> > Data manipulation language, a set of SQL statements for performing INSERT, UPDATE, and DELETE operations. The SELECT statement is sometimes considered as a DML statement, because the SELECT ... FOR UPDATE form is subject to the same considerations for locking as INSERT, UPDATE, and DELETE.
> 
> 来自mysql官方手册的解释：dml通常包括insert/update/delete，select在select ... for update时才被看作是dml。

这个我看过了。

**Comment by mengerwei** [comment]
> > [https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_dml](url)
> > > Data manipulation language, a set of SQL statements for performing INSERT, UPDATE, and DELETE operations. The SELECT statement is sometimes considered as a DML statement, because the SELECT ... FOR UPDATE form is subject to the same considerations for locking as INSERT, UPDATE, and DELETE.
> > 
> > 
> > 来自mysql官方手册的解释：dml通常包括insert/update/delete，select在select ... for update时才被看作是dml。
> 
> 这个我看过了。

给我的感觉，正常navicat客户端能跑的语句,到archery 都得抱着去测试下的心态。

**Comment by nick2wang** [comment]
> > > [https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_dml](url)
> > > > Data manipulation language, a set of SQL statements for performing INSERT, UPDATE, and DELETE operations. The SELECT statement is sometimes considered as a DML statement, because the SELECT ... FOR UPDATE form is subject to the same considerations for locking as INSERT, UPDATE, and DELETE.
> > > 
> > > 
> > > 来自mysql官方手册的解释：dml通常包括insert/update/delete，select在select ... for update时才被看作是dml。
> > 
> > 
> > 这个我看过了。
> 
> 给我的感觉，正常navicat客户端能跑的语句,到archery 都得抱着去测试下的心态。

纯粹业务设计的不同，可能在其他工具那里select会被像dml一样对待，只是archery在这里做了区分，这本身没有对错

**Comment by LeoQuote** [comment]
感谢楼主反馈, 和 @nick2wang 解释 , archery 设计时, 查询和改变数据结构的语句是分开的, 一个是查询, 一个是上线, 查询只需要做备案, 而上线则需要做审核, 这是 archery 的主要设计思路, select 语句走上线这个流程很繁杂的, 是有些舍近求远了
