### ISSUE TITLE
[ 功能建议 ]为各种数据库的连接函数添加超时相关参数

### ISSUE THREAD

**Issue by weideguo** [hhyo/archer#1311]
### 目前遇到的问题/使用障碍
engines目录下部分类型的数据库的get_connection函数没有设置超时语句，如果数据库连接不上，会导致整个系统卡死。

### 希望如何解决/实现它
为所有的get_connection函数添加相应的超时参数
如：
[pg](https://github.com/hhyo/Archery/blob/3f6b517572fdbfff938101c0f1b768c4bf76a300/sql/engines/pgsql.py#L32) connect_timeout=10
[redis](https://github.com/hhyo/Archery/blob/3f6b517572fdbfff938101c0f1b768c4bf76a300/sql/engines/redis.py#L29) socket_connect_timeout=10

**Comment by hhyo** [comment]
实例信息可以增加一个字段，字典格式存储连接初始化的附加参数，在engine初始化时传入

**Comment by weideguo** [comment]
我是想直接写入代码中，简化配置。其他类型的engine也是这么做。

**Comment by hhyo** [comment]
嗯，先把超时加上
