### ISSUE TITLE
v1.8.2 docker-compose 安装报错

### ISSUE THREAD

**Issue by mengerwei** [hhyo/archer#1312]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

# docker-compose -f docker-compose.yml up -d
.......
Pulling goinception (hanchuanchuan/goinception:)...
latest: Pulling from hanchuanchuan/goinception
97518928ae5f: Pull complete
4f8805b5a364: Pull complete
d65dea9a75d6: Pull complete
e3ef8b3b17f0: Pull complete
79d800a22e9b: Pull complete
0309ac38b218: Pull complete
4ecb76a3261e: Pull complete
5f860b9432ed: Pull complete
dcbc02d2d524: Pull complete
Digest: sha256:6d2aa9ced979c54e4d56e55f0dfce745654cf6260901ee0d6ce3c8f61ef9c21a
Status: Downloaded newer image for hanchuanchuan/goinception:latest
Pulling archery (hhyo/archery:1.8.2)...
**ERROR: manifest for hhyo/archery:1.8.2 not found: manifest unknown: manifest unknown**

应该是缺少 hhyo/archery:1.8.2的docker 镜像。
# docker pull  hhyo/archery:1.8.2
Error response from daemon: manifest for hhyo/archery:1.8.2 not found: manifest unknown: manifest unknown
@hhyo

**Comment by LeoQuote** [comment]
Duplicate of #1269

**Comment by woihzh** [comment]
修改docker-compose.yml中hhyo/archery:1.8.2 为hhyo/archery:latest

**Comment by ccjandMSDN** [comment]
如果是1.8.2版本修改如下：
修改docker-compose.yml中的hhyo/archery:1.8.2 为hhyo/archery:v1.8.2
其他版本请到hub.docker.com中找到对应的tag名称自行修改即可
