### ISSUE TITLE
[ 问题咨询 ]请简要描述

### ISSUE THREAD

**Issue by wugh888** [hhyo/archer#1313]
### 问题描述
cd chart
helm dependency update
helm install archery ./

用helm部署提示以下错误
coalesce.go:160: warning: skipped value for configurationFiles: Not a table.
coalesce.go:160: warning: skipped value for configurationFiles: Not a table.
coalesce.go:160: warning: skipped value for configurationFiles: Not a table.
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]

### 版本信息
 - 应用版本/分支：Release v1.8.2
 - 部署方式：Helm 3.2.4，k8s 1.18

**Comment by LeoQuote** [comment]
这个应该是 apiversion 问题, chart 要升级, 最近没时间修复这个, 欢迎pr

**Comment by hhyo** [comment]
#1334
