### ISSUE TITLE
更新my2sql后 binlog2sql和my2sql报错

### ISSUE THREAD

**Issue by SamsonHui** [hhyo/archer#1317]
![image](https://user-images.githubusercontent.com/32662062/148349436-db5b94e8-dabe-4651-80e7-e693e8c117ff.png)

**Comment by nick2wang** [comment]
是docker部署的么？检查下代码更新是否有遗漏，我这边clone最新代码跑起来没问题

**Comment by SamsonHui** [comment]
> 是docker部署的么？检查下代码更新是否有遗漏，我这边clone最新代码跑起来没问题

没，手动部署的。1.8.2在跑了，在1.8.2基础上更新了最近修改的文件

**Comment by nick2wang** [comment]
> > 是docker部署的么？检查下代码更新是否有遗漏，我这边clone最新代码跑起来没问题
> 
> 没，手动部署的。1.8.2在跑了，在1.8.2基础上更新了最近修改的文件

my2sql报什么错？顺便操作选项截图看下

**Comment by SamsonHui** [comment]
> > > 是docker部署的么？检查下代码更新是否有遗漏，我这边clone最新代码跑起来没问题
> > 
> > 
> > 没，手动部署的。1.8.2在跑了，在1.8.2基础上更新了最近修改的文件
> 
> my2sql报什么错？顺便操作选项截图看下

这个
![image](https://user-images.githubusercontent.com/32662062/148354672-e6fadc9b-ba11-4eba-82fc-db6234b09619.png)

**Comment by nick2wang** [comment]
> > > > 是docker部署的么？检查下代码更新是否有遗漏，我这边clone最新代码跑起来没问题
> > > 
> > > 
> > > 没，手动部署的。1.8.2在跑了，在1.8.2基础上更新了最近修改的文件
> > 
> > 
> > my2sql报什么错？顺便操作选项截图看下
> 
> 这个 ![image](https://user-images.githubusercontent.com/32662062/148354672-e6fadc9b-ba11-4eba-82fc-db6234b09619.png)

需要手动安装my2sql，参考一下这里 https://github.com/hhyo/archery/wiki/tools#my2sql
然后在系统管理--配置项管理里配上my2sql的路径

**Comment by SamsonHui** [comment]
> > > > 是docker部署的么？检查下代码更新是否有遗漏，我这边clone最新代码跑起来没问题
> > > 
> > > 
> > > 没，手动部署的。1.8.2在跑了，在1.8.2基础上更新了最近修改的文件
> > 
> > 
> > my2sql报什么错？顺便操作选项截图看下
> 
> 这个 ![image](https://user-images.githubusercontent.com/32662062/148354672-e6fadc9b-ba11-4eba-82fc-db6234b09619.png)

选项都是只选了start-file和end-file
![image](https://user-images.githubusercontent.com/32662062/148355391-154b0e30-8305-4edd-a084-33fd8263ffc9.png)
![image](https://user-images.githubusercontent.com/32662062/148355516-084cae92-a0e1-4978-b738-6adb81b4cb4c.png)

**Comment by SamsonHui** [comment]
问题解决 密码中含有特殊字符 把密码写死就可以了
