### ISSUE TITLE
[ 问题咨询 ]企业微信通知点击工单地址链接访问错误

### ISSUE THREAD

**Issue by xiao116134** [hhyo/archer#1329]
### 问题描述
从企业微信通知点击工单地址链接访问错误

### 版本信息
 - 应用版本/分支：Release v1.81 
 - 部署方式：Docker

![image](https://user-images.githubusercontent.com/42678439/149080058-18919bcb-9d77-4630-b9de-34635993e17a.png)

![image](https://user-images.githubusercontent.com/42678439/149080162-a215db40-6f12-4145-8c24-71bde733f63a.png)

**Comment by hhyo** [comment]
确认下系统配置中的ARCHERY_BASE_URL是否正确

**Comment by xiao116134** [comment]
> 确认下系统配置中的ARCHERY_BASE_URL是否正确

确认过的  没有写错

**Comment by xiao116134** [comment]
有人能正常点击链接吗

**Comment by hhyo** [comment]
默认应该会打开archery自身的地址，但是你的这个错误看起来好像是访问了企业微信的接口

**Comment by xiao116134** [comment]
> 应该会打开archery自己的地址，但是你的这个错误看起来像是访问了企业微信的默认接口

请问这个怎么修改呢
