### ISSUE TITLE
SQL分析问题

### ISSUE THREAD

**Issue by axiaochen** [hhyo/archer#1333]
### 问题描述
使用SQL分析查看报告时报错了
报错信息如下：
```
/bin/sh: line 46: -report-type=markdown: command not found
```
### 版本信息
 - 应用版本/分支：Release v1.8.2  
 - 部署方式：手工部署

**Comment by unknowissue** [comment]
SOAR_PATH
配置填写的啥?
配置路径中有soar这个文件么

**Comment by axiaochen** [comment]
这个SOAR_PATH是在哪里填写的？我在setting.py里边没有找到相关的信息，不知道在哪填写。

**Comment by axiaochen** [comment]
> SOAR_PATH 配置填写的啥? 配置路径中有soar这个文件么

这个SOAR_PATH是在哪里填写的？我在setting.py里边没有找到相关的信息，不知道在哪填写。

**Comment by unknowissue** [comment]
> 

参考下 https://archerydms.com/configuration/ 这个

**Comment by axiaochen** [comment]
我按照需求将soar放入到了目录

>

**Comment by axiaochen** [comment]
> > 
> 
> 参考下 https://archerydms.com/configuration/ 这个

我按照文档将soar放入到了指定的目录/opt/archery/src/plugins/当中，但是还是报这个错

**Comment by axiaochen** [comment]
> > 
> 
> 参考下 https://archerydms.com/configuration/ 这个
好的。谢谢！我是没有配对
