### ISSUE TITLE
[ bug ]docker-compose.yml 中的 hhyo/archery:1.8.2版本号有问题

### ISSUE THREAD

**Issue by wanxianbo** [hhyo/archer#1335]
### 问题描述
docker-compose部署报错
###报错日志：Error response from daemon: manifest for hhyo/archery:1.8.2 not found: manifest unknown: manifest unknown

###报错原因：douck hub上的hhyo/archery版本号为：hhyo/archery:v1.8.2，多了一个v

###目前的解决方案是：修改docker-compose文件中archery镜像的版本号为v1.8.2或者latest

### 版本信息
应用版本/分支：Release v1.8.2
部署方式：docker部署

**Comment by peng19832** [comment]
这个之前已知的问题，线上代码都改了的

**Comment by wanxianbo** [comment]
好的
