### ISSUE TITLE
[ 功能建议 ] SQL上线、在线查询和权限管理支持Clickhouse

### ISSUE THREAD

**Issue by hjweddie** [hhyo/archer#1343]
### 目前遇到的问题/使用障碍
我们公司生产环境上使用Archery和较多Clickhouse实例，但是Clickhouse未能找到个较好的schema流程化管理的工具。

### 希望如何解决/实现它
Clickhouse实例也能和MySQL一样在Archery系统上进行SQL上线、在线查询和权限管理

**Comment by cpzt** [comment]
可以自己模仿mysql写一个查询引擎，参考文件/Archery/sql/engines/mysql.py

**Comment by nick2wang** [comment]
功能已经实现，可用pull最新master代码试试，欢迎反馈
