### ISSUE TITLE
[ 功能建议 ] 慢查询日志支持 平均扫描行数和平均返回行数 进行排序

### ISSUE THREAD

**Issue by hjweddie** [hhyo/archer#1344]
### 目前遇到的问题/使用障碍
当我们想要找到扫描行数比较多的SQL模式去优化慢查询时，总扫描行数多的SQL不一定是我们想要的结果。因为实际上执行次数多的SQL，常常总扫描行数也会多，会把一些查询次数少，但是单次扫描行数更多的SQL给掩盖掉

### 希望如何解决/实现它
期望能有更直观的方式，直接找到单次扫描行数更多的SQL

**Comment by hhyo** [comment]
1.8.1已支持所有表头排序

**Comment by hjweddie** [comment]
> 1.8.1已支持所有表头排序

我表达的意思是按平均扫描行数排序？ 目前我们使用的 v1.8.2 版看起来还没有平均扫描行数、平均返回行数的列。只有累计值

![image](https://user-images.githubusercontent.com/5867477/149861720-9e690ad3-d98f-4283-94bc-c28070c0d860.png)

**Comment by hjweddie** [comment]
> 1.8.1已支持所有表头排序

我表达的意思是按平均扫描行数排序？ 目前最新版看起来还没有平均扫描行数、平均返回行数的列？
