### ISSUE TITLE
inception项目现在是只读模式，抱歉，我在这里提个相关需求

### ISSUE THREAD

**Issue by chaigang0** [hhyo/archer#1345]
### 目前遇到的问题/使用障碍

![image](https://user-images.githubusercontent.com/46520672/149858019-935e0061-bc2b-4bbe-bd40-44f1f9e032a5.png)

在执行工单时，我们有时会遇到这个抱错，
【Data too long for column 'host' at row 1.】

排查发现是备份库下的 $_$inception_backup_information$_$ 表的 host 列长度问题，
host 字段的长度是varchar(64) ,我们使用的AWS数据库，有时候连接地址会超过64个字符，

当然，解决这个问题，也很简单，只修改alter table $_$inception_backup_information$_$ modify host varchar(128) ,加大长度就可以了，

但这并不能从解本上解决，后面添加的新实例，再次执行工单，还是可能会遇到报错问题，虽然这个报错并不影响工单正常执行。

### 希望如何解决/实现它
我建议修改 $_$inception_backup_information$_$ 建表语句，将 host varchar(64) 修改为 varchar(128)

在 inception 项目 /sql/sql_parse.cc 文件中
链接：https://github.com/hhyo/inception/blob/master/sql/sql_parse.cc
第7994行。

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
下个版本会舍弃 goinception, goinception 里没有这个问题

**Comment by chaigang0** [comment]
非常抱歉，我们现在正在使用的正是goInception
我发现也有这个问题，

在 backup.md 文件中，如下所示，希望后期可以将varchar 长度调整为 128

- create backup information table on backup schema ```$_$Inception_backup_information$_$``` to save execute SQL and rollback SQL

    | Column             | Type         | Comment
    --------------------|--------------|------
    opid_time         | varchar(50)  | operation ID, formatting ```{timestamp}_{thread_id}_{operation_id}```
    start_binlog_file | varchar(512) | binlog start filename
    start_binlog_pos  | int(11)      | binlog start position
    end_binlog_file   | varchar(512) | binlog end filename
    end_binlog_pos    | int(11)      | binlog end position
    sql_statement     | text         | SQL execute
    host              | varchar(64)  | which IP address sql execute
    dbname            | varchar(64)  | which schema sql execute
    tablename         | varchar(64)  | which table sql execute
    port              | int(11)      | which port sql execute
    time              | timestamp    | when execute
    type              | varchar(20)  | execution type

**Comment by unknowissue** [comment]
> 非常抱歉，我们现在正在使用的正是goInception 我发现也有这个问题，
> 
> 在 backup.md 文件中，如下所示，希望后期可以将varchar 长度调整为 128
> 
> * create backup information table on backup schema `$_$Inception_backup_information$_$` to save execute SQL and rollback SQL
>   
>   
>   
>   Column
>   Type
>   Comment
>   
>   
>   
>   
>   opid_time
>   varchar(50)
>   operation ID, formatting `{timestamp}_{thread_id}_{operation_id}`
>   
>   
>   start_binlog_file
>   varchar(512)
>   binlog start filename
>   
>   
>   start_binlog_pos
>   int(11)
>   binlog start position
>   
>   
>   end_binlog_file
>   varchar(512)
>   binlog end filename
>   
>   
>   end_binlog_pos
>   int(11)
>   binlog end position
>   
>   
>   sql_statement
>   text
>   SQL execute
>   
>   
>   host
>   varchar(64)
>   which IP address sql execute
>   
>   
>   dbname
>   varchar(64)
>   which schema sql execute
>   
>   
>   tablename
>   varchar(64)
>   which table sql execute
>   
>   
>   port
>   int(11)
>   which port sql execute
>   
>   
>   time
>   timestamp
>   when execute
>   
>   
>   type
>   varchar(20)
>   execution type

亲，goInception 有同学维护呢，这个问题建议到[goInception](https://github.com/hanchuanchuan/goInception)那边提交issue

**Comment by chaigang0** [comment]
@hhyo 好的，谢谢。可以关单了
