### ISSUE TITLE
[ 功能建议 ]为ajax请求的返回错误进行分类报错

### ISSUE THREAD

**Issue by weideguo** [hhyo/archer#1346]
### 目前遇到的问题/使用障碍
ajax请求后端时有一定概率因为权限出现报错，但现在的报错信息会让人困惑
![before](https://user-images.githubusercontent.com/3381137/149868195-81261873-ec76-42a7-a514-ac7cf68c3483.png)

### 希望如何解决/实现它
根据返回状态码，按照分类给出更详细的报错
![after](https://user-images.githubusercontent.com/3381137/149868155-82e86cad-aeab-40a7-8640-4e39ce00357b.png)

即把原来的所有的函数
``` js
onLoadError: function () {
    alert("数据加载失败！请检查接口返回信息和错误日志！");
} 
```
替换成
``` js
onLoadError: function (status, jqXHR) {
    if (status === 403) {
        alert("权限错误，您没有权限查看该数据！");
    } else {
        alert("未知错误，数据加载失败！请检查接口返回信息和错误日志！");
    }
}
```

**Comment by LeoQuote** [comment]
jq 写的就是不好复用, 不如包装一个公用的请求函数, 然后到处都引用这个

**Comment by weideguo** [comment]
在创建文件`sql/static/js/utils.js`存放公共函数？ @LeoQuote

**Comment by LeoQuote** [comment]
可以, 然后在 base 里 include 吧
