### ISSUE TITLE
init_sql中没有1.8.2版本的

### ISSUE THREAD

**Issue by doing-cr7** [hhyo/archer#1347]
![image](https://user-images.githubusercontent.com/63889450/149903686-f381ed61-8290-4581-85d8-2d9592463572.png)

**Comment by unknowissue** [comment]
看起来你的需求是升级？
升级的话，1.8.2是没有升级数据库脚本的
我本地从1.8.1升级到1.8.2没有升级数据库脚本没啥问题。

**Comment by doing-cr7** [comment]
那就是说升级 主要是docker-compose.yaml 和settings.py的 操作吧
