### ISSUE TITLE
新增水印

### ISSUE THREAD

**Issue by cslingjun** [hhyo/archer#1350]
### 目前遇到的问题/使用障碍
防止数据泄露吧
### 希望如何解决/实现它
前端渲染base.html
### 其他信息
![image](https://user-images.githubusercontent.com/24772668/150512646-2854dfc4-5cdf-4a6b-a5e2-a6c1543c154e.png)

**Comment by hhyo** [comment]
提个pr？

**Comment by LeoQuote** [comment]
求pr、以及设置一个开关吧

**Comment by cslingjun** [comment]
> 提个pr？

等空下来后 ，整理下就提
![image](https://user-images.githubusercontent.com/24772668/151095269-43b75016-f191-4550-8cd7-3506adfe15d1.png)

**Comment by cslingjun** [comment]
> 求pr、以及设置一个开关吧

好的哈 ，开关已设置好了

**Comment by nick2wang** [comment]
如果可以的话，建议水印显示范围排除导航栏和菜单栏，只渲染page content部分
https://github.com/hhyo/Archery/blob/34184323a16674cdf9b232f8b06b01259207f850/common/templates/base.html#L277-L290
