### ISSUE TITLE
[ bug ]clone最新到本地，数据库管理中显示不正确

### ISSUE THREAD

**Issue by unknowissue** [hhyo/archer#1355]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

1、实例管理-数据库管理随便查询一个实例的数据库，在授权账号列显示不正确
![image](https://user-images.githubusercontent.com/76696174/150710421-9932a0e8-bccd-4aa7-8112-3b55fee6feb9.png)
&#39;acd&#39;@&#39;%&#39;
看起来是被截断了？
另外 google 说是会有flask 这样的方法防止注入， 我找了下，好像没有flask 的引用？
但是用网上的方法tojson又不对，
不懂js，辛苦帮忙一起调一下，，，，

另外，我增加了console.log
`
}, {
                        title: '排序规则',
                        field: 'collation'
                    }, {
                       title: '授权账号',
                       field: 'grantees',
                       formatter: function (value, row, index) {
                           let grantee = '';
                           //grantees_list =  (value|tojson);
                           //grantees_list = value.toJSON();
                           console.log(value)
                           for (let i = 0; i < value.length; i++) {
                               grantee = grantee + value[i] + '</br>'
                           }
                           return grantee
                       }
                       }, {
`

![image](https://user-images.githubusercontent.com/76696174/150711109-83a9830c-fd0f-48a6-a8e8-6905357ba463.png)

### 版本信息
应用版本/分支：
当前最新分支

部署方式：手工部署

**Comment by unknowissue** [comment]
嗷嗷

`js
 $('#database-list').bootstrapTable('destroy').bootstrapTable({
                escape: true,
                method: 'post',
                contentType: "application/x-www-form-urlencoded",
                url: "/instance/database/list/",
`

是escape这个true，改为false就可以正常显示了
怎么把这个列特殊处理一下呢。。。

**Comment by unknowissue** [comment]
在instance_database.py 中修改了一下传参
`
        # 获取数据库关联用户信息
        rows = []
        for db in dbs:
            db_name = db[0]
            sql_get_bind_users = f"""select group_concat(distinct(GRANTEE)),TABLE_SCHEMA
from information_schema.SCHEMA_PRIVILEGES
where TABLE_SCHEMA='{db_name}'
group by TABLE_SCHEMA;"""
            bind_users = query_engine.query('information_schema', sql_get_bind_users, close_conn=False).rows
            row = {
                'db_name': db_name,
                'charset': db[1],
                'collation': db[2],
                #'grantees': bind_users[0][0].split(',')if bind_users else [] ,
                'grantees': bind_users[0][0].replace("'","").split(',')if bind_users else [] ,
                'saved': False
            }
            # 合并数据
            if db_name in cnf_dbs.keys():
                row = dict(row, **cnf_dbs[db_name])
            rows.append(row)
`
print(result):
{'status': 0, 'msg': 'ok', 'rows': [{'db_name': 'xxxx', 'charset': 'utf8mb4', 'collation': 'utf8mb4_unicode_ci', 'grantees': ["'acd'@'%'"], 'saved': False}, 

变成了
![image](https://user-images.githubusercontent.com/76696174/150714824-645996d3-f99b-407c-b68f-f56cd59beaae.png)

**Comment by unknowissue** [comment]
还有账号管理功能也有这样的问题。

**Comment by nick2wang** [comment]
> 嗷嗷
> 
> `js $('#database-list').bootstrapTable('destroy').bootstrapTable({ escape: true, method: 'post', contentType: "application/x-www-form-urlencoded", url: "/instance/database/list/", `
> 
> 是escape这个true，改为false就可以正常显示了 怎么把这个列特殊处理一下呢。。。

直接全局false吧，有需要escape的字段可以单独设置
```
{
    title: 'xxx',
    field: 'xxx',
    escape: true
}
```

**Comment by weideguo** [comment]
bootstrap-table  升级到了1.9.1, value值获取到的都是字符串，所以有 formatter 函数处理的可能都存在问题

**Comment by unknowissue** [comment]
> bootstrap-table 升级到了1.9.1, value值获取到的都是字符串，所以有 formatter 函数处理的可能都存在问题

那有啥解决方法么，还是改成 escape:false？

**Comment by weideguo** [comment]
> > bootstrap-table 升级到了1.9.1, value值获取到的都是字符串，所以有 formatter 函数处理的可能都存在问题
> 
> 那有啥解决方法么，还是改成 escape:false？

先什么都不搞，我最新的提交降到1.18.3可以修复了，等待合并分支后拉最新代码就可以。

**Comment by weideguo** [comment]
问题已经处理，可以拉取最新代码验证。 @unknowissue

**Comment by unknowissue** [comment]
> 问题已经处理，可以拉取最新代码验证。 @unknowissue

好滴，我试一试。
谢谢

**Comment by unknowissue** [comment]
可以了
