### ISSUE TITLE
[ 问题咨询 ] 如何解除提交的语句限制

### ISSUE THREAD

**Issue by majingpu** [hhyo/archer#1358]
### 问题描述
修改 系统设置-->sql上线 中的`CRITICAL_DDL_REGEX` 为空 `AUTO_REVIEW_WRONG` 为0，保存。

结果:
---
工单执行失败，仍报错：`禁用【DROP】|【TRUNCATE】删除/清空表 'tb_custom_concept_droped', 请改用RENAME重写`
![image](https://user-images.githubusercontent.com/49381462/150755814-d29b6d4d-69ad-4da5-b795-ecda2789216c.png)

### 版本信息
 - 应用版本/分支：Release v1.8.1 
 - 部署方式：Docker

**Comment by majingpu** [comment]
因为我们这个是测试环境，可以下放drop等高危命令的权限。这里修改系统设置之后，没有生效。想问下是我的操作不对，还是配置不是在这里修改。

**Comment by nick2wang** [comment]
goinception改下参数，参考：https://hanchuanchuan.github.io/goInception/options.html
1.vi config.toml
enable_drop_table = true
2.
`inception set enable_drop_table = true;`
