### ISSUE TITLE
[ bug ]导出查询SQL结果里面数字过长会乱码

### ISSUE THREAD

**Issue by xiao116134** [hhyo/archer#1364]
版本信息
应用版本/分支：发布 v1.81
部署方式：Docker
查询结果：
![image](https://user-images.githubusercontent.com/42678439/151303974-d7ac7bb6-a7bb-47c5-89cb-224ad8154200.png)
导出结果：

![image](https://user-images.githubusercontent.com/42678439/151304047-66956f33-0106-4707-b904-6c52a98a8de1.png)

**Comment by LeoQuote** [comment]
excel 的事情, 你自己调一下单元格格式就可以了
