### ISSUE TITLE
请问如何关闭导出功能？

### ISSUE THREAD

**Issue by hbbdgyb** [hhyo/archer#1367]
### 问题描述
请问如何关闭导出功能？
或者针对特定的人关闭导出功能？

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker

**Comment by hbbdgyb** [comment]
用了1个小时研究明白了，这个程序里没有这一项功能。
我改了半天/opt下的文件都不生效，原来是docker没有映射本地文件。-_-||

进入docker容器，找到sqlquery.html。修改showExport相关配置为以下内容。
这个文件一共有两处需要修改。

`{% if request.user.id == 3%}
                    showExport:false,
                {% else %}
                    showExport:true,
                {% endif %}`

**Comment by LeoQuote** [comment]
这个是前端的, 因为关闭导出也意义不大, 数据泄露风险还在, 所以没做相应的开关, 欢迎 pr

**Comment by weideguo** [comment]
> 用了1个小时研究明白了，这个程序里没有这一项功能。 我改了半天/opt下的文件都不生效，原来是docker没有映射本地文件。-_-||
> 
> 进入docker容器，找到sqlquery.html。修改showExport相关配置为以下内容。 这个文件一共有两处需要修改。
> 
> `{% if request.user.id == 3%} showExport:false, {% else %} showExport:true, {% endif %}`

你这写法太死了，[增加个权限](https://github.com/hhyo/Archery/blob/0abcd432ec90fecbe4b6e94ee83629d5cf63771b/sql/models.py#L733)，showExport这个变量的值由[sql/views.py](https://github.com/hhyo/Archery/blob/0abcd432ec90fecbe4b6e94ee83629d5cf63771b/sql/views.py#L223)对用户进行权限判断后传入不是更好？

**Comment by gaoqiang-0327** [comment]
是不是可以做成工单审批那种方式。
