### ISSUE TITLE
[ 问题咨询 ]服务器时区与浏览器时区不一致导致sql上线执行滞后

### ISSUE THREAD

**Issue by zancers** [hhyo/archer#1368]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
服务器时区为UTC-5，浏览器时区为UTC+8，提交sql上线工单时间为服务器时间，执行计划只能选择浏览器当前往后的时间，导致提交工单后至少滞后13个小时才能执行。

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
这个 issue 为何关闭?
