### ISSUE TITLE
[ 问题咨询 ] MySQL的实例账号密码应该授予什么权限

### ISSUE THREAD

**Issue by Martwu** [hhyo/archer#1370]
### 问题描述
[wiki中的数据库管理](https://github.com/hhyo/archery/wiki/instance#%E6%95%B0%E6%8D%AE%E5%BA%93%E7%AE%A1%E7%90%86)中，建议提供下账号权限的说明，目前为空。

### 版本信息
 - 应用版本/分支：Release v1.8.2
 - 部署方式：Docker

**Comment by peng19832** [comment]
> ### 问题描述
> [wiki中的数据库管理](https://github.com/hhyo/archery/wiki/instance#%E6%95%B0%E6%8D%AE%E5%BA%93%E7%AE%A1%E7%90%86)中，建议提供下账号权限的说明，目前为空。
> 
> ### 版本信息
> * 应用版本/分支：Release v1.8.2
> * 部署方式：Docker

我实际使用过程中，觉得最好是专用账号，给all权限，如果要用到archery授权，还要有grant option权限
