### ISSUE TITLE
[ bug ]用的好好的，今天突然登录不了

### ISSUE THREAD

**Issue by wushuigen** [hhyo/archer#1373]
### 重现步骤
1. 之前用的都好好的，今天登录突然报错
2. 错误信息：
服务器错误Traceback (most recent call last): File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection self.connect() File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner return func(*args, **kwargs) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect self.connection = self.get_new_connection(conn_params) File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner return func(*args, **kwargs) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection return Database.connect(**conn_params) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect return Connection(*args, **kwargs) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__ super().__init__(*args, **kwargs2) MySQLdb._exceptions.OperationalError: (1049, "Unknown database 'archery'") The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/opt/archery/common/auth.py", line 61, in authenticate user = Users.objects.get(username=username) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 425, in get num = len(clone) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__ self._fetch_all() File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all self._result_cache = list(self._iterable_class(self)) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__ results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql cursor = self.connection.cursor() File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner return func(*args, **kwargs) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor return self._cursor() File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor self.ensure_connection() File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner return func(*args, **kwargs) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection self.connect() File "/opt/venv4archery/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection self.connect() File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner return func(*args, **kwargs) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect self.connection = self.get_new_connection(conn_params) File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner return func(*args, **kwargs) File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection return Database.connect(**conn_params) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect return Connection(*args, **kwargs) File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__ super().__init__(*args, **kwargs2) django.db.utils.OperationalError: (1049, "Unknown database 'archery'")
### 截图
![image](https://user-images.githubusercontent.com/47021825/153352032-8168cab0-7dd0-495f-8302-383ecd75f359.png)

docker logs archery -f --tail=10
  File "/opt/venv4archery/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1049, "Unknown database 'archery'")

### 版本信息
应用版本/分支：Release V1.8.1

部署方式：Docker

**Comment by unknowissue** [comment]
django.db.utils.OperationalError: (1049, "Unknown database 'archery'")
访问不到数据库了，看看本地的数据库吧。

**Comment by wushuigen** [comment]
> django.db.utils.OperationalError: (1049, "Unknown database 'archery'") 访问不到数据库了，看看本地的数据库吧。

**Comment by wushuigen** [comment]
发现，docker部署的mysql的默认密码被别人利用，直接将库给删了。我现在要修改默认配置，发现一直没有用
