### ISSUE TITLE
[ bug ]明明已经在docker-compose.yml中修改了mysql的密码，但还是使用了默认密码

### ISSUE THREAD

**Issue by wushuigen** [hhyo/archer#1375]
### 重现步骤
1. 已经按照文档，在docker-compose文件夹的docker-compose.yml文件修改了mysql的root密码
2. 但启动容器后，mysql的密码还是默认的123456
3. 设置的密码根本不生效

### 版本信息
应用版本/分支：Release V1.8.1

部署方式：Docker

**Comment by LeoQuote** [comment]
把 mysql 的持久卷删了再重试下看看

**Comment by wushuigen** [comment]
这个持久卷在哪个位置

**Comment by wushuigen** [comment]
我把加压文件整个目录重新删除了。重新来过就可以了
