### ISSUE TITLE
redis查询的时候能不能显示的更加美观 和好看 就比如数据拿到后进行json解析

### ISSUE THREAD

**Issue by doing-cr7** [hhyo/archer#1376]
![image](https://user-images.githubusercontent.com/63889450/153530338-66f9c129-5fcd-434f-aec2-c63464323cc6.png)

**Comment by LeoQuote** [comment]
后端上基本没什么能做, 你看前端这块能不能把 redis 的特别处理一下

**Comment by nick2wang** [comment]
solved by #1382
