### ISSUE TITLE
[ 问题咨询 ] SQL上线，goinception 报 lookup mysql on 127.0.0.11:53: no such host" file=session_inception.go func=parseOptions line=2117

### ISSUE THREAD

**Issue by dmanbu** [hhyo/archer#1380]
### 问题描述
查询数据没有问题，但在执行SQL上线时，提示有异常
![image](https://user-images.githubusercontent.com/10231091/153737728-bffed08f-9d09-4beb-8d09-bd8cd558f862.png)

然后我检查 goinception 容器的报错信息，有如下提示:
```
time="2022/02/13 11:22:07.317" level=error msg="con:11 con:11 dial tcp: lookup mysql on 127.0.0.11:53: no such host" file=session_inception.go func=parseOptions line=2117
time="2022/02/13 11:27:10.755" level=error msg="con:14 con:14 dial tcp: lookup mysql on 127.0.0.11:53: no such host" file=session_inception.go func=parseOptions line=2117
```

archery自己的数据库是用的一个外部数据库，没用docker-compose自带的那个mysql，数据库地址为 192.168.0.200 ，并没有用域名  
进行变更的数据库实例是用的IP:192.168.0.200，也没有用域名  
感觉 goinception 会去连docker-compose自带的那个mysql
请问是缺少什么配置么？  

### 版本信息
 - 应用版本/分支：Release v1.8.2
 - 部署方式：Docker-Compose

**Comment by dmanbu** [comment]
我已经解决了，光在web页面更改goInception的配置没用，还需要更改goInception的config.toml配置文件

**Comment by CorollaD** [comment]
> 我已经解决了，光在web页面更改goInception的配置没用，还需要更改goInception的config.toml配置文件

config.toml 文件怎么配置的，可以贴个模版吗 调试了很久还是没能解决

**Comment by enica** [comment]
config.toml

**Comment by enica** [comment]
config.toml的mysql配置
```
backup_host=
backup_port=
backup_user=
backup_password=
```
另外记得对数据库的账号做授权
参考：https://github.com/hhyo/archery/wiki/sql_check#SQL%E4%B8%8A%E7%BA%BF
