### ISSUE TITLE
[ 问题咨询 ]执行sql的线程只有4个

### ISSUE THREAD

**Issue by oubodan** [hhyo/archer#1386]
### 问题描述
我们在执行sql脚本时，只有4个线程同时进行，其他的都在排队状态
请问如何可以增加同时执行脚本的线程数，我们库比较多
### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：Docker

**Comment by nick2wang** [comment]
增大workers
https://github.com/hhyo/Archery/blob/ca10a8f0d55c9a1662b33deef399d805d2b29399/archery/settings.py#L140-L153

**Comment by LeoQuote** [comment]
建议多开 qcluster 的实例，这样比改配置文件方便
