### ISSUE TITLE
[ 问题咨询 ]goinception报证书问题

### ISSUE THREAD

**Issue by TottyAndBaty** [hhyo/archer#1388]
### 问题描述

我的实例是通过隧道连接。

检查了inception下的config.toml 和inc.cnf,数据库配置都一致，
goInception配置  设置里面测试连接正常

sql检测的时候报这样的问题，

 

>  time="2022/02/16 18:18:43.500" level=error msg="con:3 con:3 dial tcp 127.0.0.1:39690: connect: connection refused" file=session_inception.go func=parseOptions line=2123

看了session_inception.go代码2123

 

> 	rootCertPool := x509.NewCertPool()
		pem, err := ioutil.ReadFile(s.opt.sslCA)
		if err != nil {
			return "", fmt.Errorf("con:%d %v", s.sessionVars.ConnectionID, err)
		}
		if ok := rootCertPool.AppendCertsFromPEM(pem); !ok {
			return "", fmt.Errorf("con:%d Failed to append PEM.", s.sessionVars.ConnectionID)
		}

看样子这里涉及到证书了。。。这个就不知道怎么配置了。。。。

### 版本信息
 - 应用版本/分支：最新版
 - 部署方式：Docker

**Comment by jyworker** [comment]
同样的问题，不知如何解决

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/issues/1362
