### ISSUE TITLE
docker部署archery报错

### ISSUE THREAD

**Issue by Myshiner** [hhyo/archer#1391]
docker-compose -f docker-compose.yml up -d这一步的时候报错了
[+] Running 0/13
 ⠹ inception Pulling                                                                                                                                                  8.2s
   ⠸ 8ba884070f61 Pulling fs layer                                                                                                                                    2.3s
   ⠸ f9c3dffc7be2 Pulling fs layer                                                                                                                                    2.3s
 ⠿ archery Error                                                                                                                                                      8.2s
 ⠹ redis Pulling                                                                                                                                                      8.2s
   ⠋ 5eb5b503b376 Pulling fs layer                                                                                                                                    1.0s
   ⠋ 6530a7ea3479 Waiting                                                                                                                                             1.0s
   ⠋ 91f5202c6d9b Waiting                                                                                                                                             1.0s
   ⠋ 794a1ae80e03 Waiting                                                                                                                                             1.0s
   ⠋ dbfd5af341d5 Waiting                                                                                                                                             1.0s
   ⠋ 90b19def99ff Waiting                                                                                                                                             1.0s
 ⠿ goinception Error                                                                                                                                                  8.2s
 ⠿ mysql Error                                                                                                                                                        8.2s
**Error response from daemon: manifest for hhyo/archery:1.8.2 not found: manifest unknown: manifest unknown**

看起来是镜像没找到？

### 版本信息
 - 应用版本/分支：Release v1.8.2
 - 部署方式：Docker

**Comment by nick2wang** [comment]
重复问题，参考 #1269

**Comment by gitxuzhefeng** [comment]
edit docker-compose.yml
update archery'image to hhyo/archery:v1.8.2

**Comment by Myshiner** [comment]
OK,谢谢
