### ISSUE TITLE
[ 问题咨询 ]SQL上线执行sql语句后就显示一直在排队中，是什么原因？

### ISSUE THREAD

**Issue by charles896** [hhyo/archer#1400]
![image](https://user-images.githubusercontent.com/96164051/155643452-71764bd3-0e2f-4f70-a414-37d9670f3ddd.png)
![image](https://user-images.githubusercontent.com/96164051/155643497-e8062be3-bbc9-4986-9bc7-1029ac68bc83.png)
![image](https://user-images.githubusercontent.com/96164051/155643573-7167ac33-cee2-49d2-a49e-fc28a32e9c7d.png)
![image](https://user-images.githubusercontent.com/96164051/155643637-069e4577-8a2a-4397-850c-94256d70ea13.png)
![image](https://user-images.githubusercontent.com/96164051/155643803-da786024-6b8c-46ab-a749-c318c9c5b009.png)

配置如上，goinception和备份库都已连接成功，但一执行就一直显示排队中，会是什么原因造成的？

**Comment by unknowissue** [comment]
看看这个 
https://archerydms.com/FAQ/?h=%E6%85%A2#_4
