### ISSUE TITLE
[问题咨询]对一张非分区表重建为分区表 会报错 不知道是不是不支持

### ISSUE THREAD

**Issue by ht2324** [hhyo/archer#1404]
手动执行是可以的 原表有数据，执行重建表语句报错
![image](https://user-images.githubusercontent.com/85989237/156122374-a1707b98-0783-4246-af38-59ab3dac840d.png)

![image](https://user-images.githubusercontent.com/85989237/156122436-924daa29-2d29-4295-9765-9ef66a7069e6.png)

**Comment by nick2wang** [comment]
archery使用的审核模块goinception不支持普通表改分区表语法，可以去那边提个issue [goinception](https://github.com/hanchuanchuan/goInception)

**Comment by ht2324** [comment]
> 

好的 谢谢

**Comment by nick2wang** [comment]
最新版goinception已支持分区表转换语法，请更新后再试下 [goInception-linux-v1.2.5-34](https://github.com/hanchuanchuan/goInception/releases/download/v1.2.5/goInception-linux-v1.2.5-34-gf6d55a5.tar.gz)

**Comment by nick2wang** [comment]
最新版goinception已支持分区表转换语法，请更新后再试下 [goInception-linux-v1.2.5-34](https://github.com/hanchuanchuan/goInception/releases/download/v1.2.5/goInception-linux-v1.2.5-34-gf6d55a5.tar.gz)
