### ISSUE TITLE
[ bug ]MYSQL8实例创建索引的SQL检查报error：不支持WITH PARSER ngram

### ISSUE THREAD

**Issue by tcgdy0201** [hhyo/archer#1408]
### 重现步骤
mysql8的实例，在SQL审核-SQL上线中提交创建索引的sql，sql内容如下：
```sql
ALTER TABLE `t_author`
    ADD FULLTEXT INDEX `idx_author_name`(`user_name`, `nick_name`) KEY_BLOCK_SIZE = 2 WITH PARSER ngram;
```

在SQL检查过程中，出现报错，报错信息如下：`line 2 column 91 near "WITH PARSER ngram"`

### 期待结果和实际结果
期待结果：
sql检查不报错

实际结果:
sql检查报error

### 截图
![Snipaste_2022-03-08_17-18-14](https://user-images.githubusercontent.com/5424734/157206296-c80dadfc-42bb-430b-b8b0-c7489e9ec727.jpg)

 
### 版本信息
应用版本/分支：v1.8.2

部署方式：Docker

**Comment by nick2wang** [comment]
archery审核使用的[goinception](https://github.com/hanchuanchuan/goInception)最近才支持with parser语法，可以去拉下最新的goinception代码编译后再运行看看

[update: 添加FULLTEXT INDEX的WITH PARSER option语法支持](https://github.com/hanchuanchuan/goInception/commit/1cc9f31252ead0cc84b2cd375c1f9fa704336867)

**Comment by tcgdy0201** [comment]
> 

感谢感谢！
