### ISSUE TITLE
[ bug ]MongoDB提交SQL审核-SQL上线工单。操作日志，显示执行成功，数据未更新。

### ISSUE THREAD

**Issue by windyHe2020** [hhyo/archer#1409]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1、插入MongoDB数据。//db.test.insert({id:2});
2、工单执行，数据插入MongoDB。
3、工单执行成功，查询不到相关记录。//db.test.find({id:2})
![image](https://user-images.githubusercontent.com/74186888/157790097-1ef1498b-2a5f-4aa4-8c78-e62ce73d0028.png)
![image](https://user-images.githubusercontent.com/74186888/157790336-e37049ee-2e81-4394-9248-2c9f31e9b9d3.png)
![image](https://user-images.githubusercontent.com/74186888/157790355-0df01b1a-b155-4904-aecb-9c06d7d5bd02.png)
![image](https://user-images.githubusercontent.com/74186888/157790505-7e38e527-c7c2-46b4-8bcc-3c0d9c849a22.png)

 
### 错误日志
![image](https://user-images.githubusercontent.com/74186888/157789377-91147090-cda4-4a13-a5a3-8c94e553c7ea.png)

工单执行过程中（截图工单执行时间为3月11日10：24执行），archery.log/qcluster.log/supervisord.log/archery-stdout---supervisor-bdjhytn4.log及数据库中均无错误日志
![image](https://user-images.githubusercontent.com/74186888/157790679-14f1a564-8e5a-4d3e-901b-8318a08425d1.png)

### 版本信息
应用版本/分支：
V1.8.2(mongoDB 3.2.2/MongoDB5.0)
部署方式：手工部署

**Comment by windyHe2020** [comment]
![image](https://user-images.githubusercontent.com/74186888/157420773-b6658101-edad-44d9-a528-38e59399a891.png)

**Comment by nick2wang** [comment]
qcluster日志看下内容

**Comment by windyHe2020** [comment]
> qcluster日志看下内容
只有一条3月9日16：52的记录，这个时间点并没有Mongodb工单提交。
(base) [root@dev.clickhouse.yllgame.local /usr/local/Archery/logs]# cat qcluster.log 
[2022-03-09 16:52:58,807][MainThread:140249347020608][task_id:django-q][cluster.py:390][ERROR]- Failed [sqlreview-pass-219] - 'NoneType' object has no attribute 'audit_id' : Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.8/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/local/Archery/sql/notify.py", line 88, in notify_for_audit
    audit_id = audit_detail.audit_id
AttributeError: 'NoneType' object has no attribute 'audit_id'

**Comment by calvin2020** [comment]
目前archery好像只能配一个mongo实例，对于副本集这种情况，如果配置的Mongo实例变成从节点，可能会出现报错或者工单执行失败

**Comment by windyHe2020** [comment]
> 目前archery好像只能配一个mongo实例，对于副本集这种情况，如果配置的Mongo实例变成从节点，可能会出现报错或者工单执行失败
这个是只配置的主库，工单没有报错。你有验证过 工单执行后，数据是否变化吗？

**Comment by calvin2020** [comment]
> > 目前archery好像只能配一个mongo实例，对于副本集这种情况，如果配置的Mongo实例变成从节点，可能会出现报错或者工单执行失败
> > 这个是只配置的主库，工单没有报错。你有验证过 工单执行后，数据是否变化吗？

有验证过，工单执行功能成功，数据无变化，目前还未解决

**Comment by windyHe2020** [comment]
> qcluster日志看下内容

这个问题，你那边可以复现吗？我看另一位朋友，碰到和我相同的问题。

**Comment by nick2wang** [comment]
> > qcluster日志看下内容
> 
> 这个问题，你那边可以复现吗？我看另一位朋友，碰到和我相同的问题。

不能复现，如果可以的话，麻烦把你本地的代码隐去关键配置信息后打包发我一份，我跑起来调试下

**Comment by windyHe2020** [comment]
> > > qcluster日志看下内容
> > 
> > 
> > 这个问题，你那边可以复现吗？我看另一位朋友，碰到和我相同的问题。
> 
> 不能复现，如果可以的话，麻烦把你本地的代码隐去关键配置信息后打包发我一份，我跑起来调试下

是把Archery目录整个打包吗？之前没有操作过，有200多MB，怎么发给你啊。你本地也是V1.8.2手工部署吗？我是手工拉的git clone https://github.com/hhyo/Archery.git

**Comment by nick2wang** [comment]
> > > > qcluster日志看下内容
> > > 
> > > 
> > > 这个问题，你那边可以复现吗？我看另一位朋友，碰到和我相同的问题。
> > 
> > 
> > 不能复现，如果可以的话，麻烦把你本地的代码隐去关键配置信息后打包发我一份，我跑起来调试下
> 
> 是把Archery目录整个打包吗？之前没有操作过，有200多MB，怎么发给你啊。你本地也是V1.8.2手工部署吗？我是手工拉的git clone https://github.com/hhyo/Archery.git

Archery目录，发我邮箱吧 nick2wang@outlook.com

**Comment by windyHe2020** [comment]
> 



> > > > > qcluster日志看下内容
> > > > 
> > > > 
> > > > 这个问题，你那边可以复现吗？我看另一位朋友，碰到和我相同的问题。
> > > 
> > > 
> > > 不能复现，如果可以的话，麻烦把你本地的代码隐去关键配置信息后打包发我一份，我跑起来调试下
> > 
> > 
> > 是把Archery目录整个打包吗？之前没有操作过，有200多MB，怎么发给你啊。你本地也是V1.8.2手工部署吗？我是手工拉的git clone https://github.com/hhyo/Archery.git
> 
> Archery目录，发我邮箱吧 [nick2wang@outlook.com](mailto:nick2wang@outlook.com)

不好意思啦。公司下发通知，安全这边不让发，私发抓到会被罚款通报……

>

**Comment by windyHe2020** [comment]
> > > > > qcluster日志看下内容
> > > > 
> > > > 
> > > > 这个问题，你那边可以复现吗？我看另一位朋友，碰到和我相同的问题。
> > > 
> > > 
> > > 不能复现，如果可以的话，麻烦把你本地的代码隐去关键配置信息后打包发我一份，我跑起来调试下
> > 
> > 
> > 是把Archery目录整个打包吗？之前没有操作过，有200多MB，怎么发给你啊。你本地也是V1.8.2手工部署吗？我是手工拉的git clone https://github.com/hhyo/Archery.git
> 
> Archery目录，发我邮箱吧 [nick2wang@outlook.com](mailto:nick2wang@outlook.com)

我升级V1.8.3 后，问题解决了，感谢关注！

**Comment by windyHe2020** [comment]
> > > 目前archery好像只能配一个mongo实例，对于副本集这种情况，如果配置的Mongo实例变成从节点，可能会出现报错或者工单执行失败
> > > 这个是只配置的主库，工单没有报错。你有验证过 工单执行后，数据是否变化吗？
> 
> 有验证过，工单执行功能成功，数据无变化，目前还未解决

我升级V1.8.3 后，问题解决了。

**Comment by huangsijun17** [comment]
> > > > > > qcluster日志看下内容
> > > > > 
> > > > > 
> > > > > 这个问题，你那边可以复现吗？我看另一位朋友，碰到和我相同的问题。
> > > > 
> > > > 
> > > > 不能复现，如果可以的话，麻烦把你本地的代码隐去关键配置信息后打包发我一份，我跑起来调试下
> > > 
> > > 
> > > 是把Archery目录整个打包吗？之前没有操作过，有200多MB，怎么发给你啊。你本地也是V1.8.2手工部署吗？我是手工拉的git clone https://github.com/hhyo/Archery.git
> > 
> > 
> > Archery目录，发我邮箱吧 [nick2wang@outlook.com](mailto:nick2wang@outlook.com)
> 
> 我升级V1.8.3 后，问题解决了，感谢关注！

请问一下，最后是怎么配置的？是将所有节点全部加入？还是配置单一节点后，Archery自动漫游到主节点？
