### ISSUE TITLE
[ bug ]Clickhouse实例列表添加实例成功，测试通过。无法执行查询或提交SQL工单

### ISSUE THREAD

**Issue by windyHe2020** [hhyo/archer#1411]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：
可正常创建工单
实际结果:
工单创建报错或无法读取到数据库
### 截图
![image](https://user-images.githubusercontent.com/74186888/157598633-46d14397-fe3b-4998-9683-378279b63b21.png)

![image](https://user-images.githubusercontent.com/74186888/157598575-57d0452d-3403-4ed3-b707-584c90392b38.png)

 
### 错误日志
2022-03-10 11:40:54,438][MainThread:139631774422848][task_id:default][clickhouse.py:123][WARNING]- ClickHouse语句执行报错，语句：show databases，错误信息Code: 102. Unexpected packet from server XXXX:8123 (expected Hello or Exception, got Unknown packet)
[2022-03-10 11:41:07,181][MainThread:139631774422848][task_id:default][clickhouse.py:123][WARNING]- ClickHouse语句执行报错，语句：show databases，错误信息Code: 102. Unexpected packet from server XXXX:8123 (expected Hello or Exception, got Unknown packet)
[2022-03-10 11:46:41,142][MainThread:139631774422848][task_id:default][clickhouse.py:123][WARNING]- ClickHouse语句执行报错，语句：show databases，错误信息Code: 102. Unexpected packet from server XXXX:8123 (expected Hello or Exception, got Unknown packet)
[2022-03-10 11:54:58,761][MainThread:139631774422848][task_id:default][clickhouse.py:123][WARNING]- ClickHouse语句执行报错，语句：show databases，错误信息Code: 102. Unexpected packet from server XXXX:9004 (expected Hello or Exception, got Unknown packet)
[2022-03-10 11:55:03,753][MainThread:139631774422848][task_id:default][clickhouse.py:123][WARNING]- ClickHouse语句执行报错，语句：show databases，错误信息Code: 102. Unexpected packet from server XXXX:9004 (expected Hello or Exception, got Unknown packet)
[2022-03-10 11:55:09,472][MainThread:139631774422848][task_id:default][clickhouse.py:123][WARNING]- ClickHouse语句执行报错，语句：show databases，错误信息Code: 102. Unexpected packet from server XXXX:9004 (expected Hello or Exception, got Unknown packet)
[2022-03-10 11:57:16,051][MainThread:139631774422848][task_id:default][clickhouse.py:123][WARNING]- ClickHouse语句执行报错，语句：show databases，错误信息Code: 516.
DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x879d83a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
1. DB::IAccessStorage::throwCannotAuthenticate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xea8a3df in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
2. DB::IAccessStorage::login(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool) const @ 0xea8a222 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
3. DB::Context::setUser(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0xeec7e19 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
4. DB::TCPHandler::receiveHello() @ 0xfd932ec in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
5. DB::TCPHandler::runImpl() @ 0xfd8c6fa in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
6. DB::TCPHandler::run() @ 0xfd9fd99 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
7. Poco::Net::TCPServerConnection::start() @ 0x1241daef in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
8. Poco::Net::TCPServerDispatcher::run() @ 0x1241f57a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
9. Poco::PooledThread::run() @ 0x12559339 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x1255532a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
11. start_thread @ 0x740b in /usr/lib64/libpthread-2.26.so
12. clone @ 0xed09f in /usr/lib64/libc-2.26.so

### 版本信息
应用版本/分支：
V1.8.2

部署方式：Docker、手工部署
手工部署

**Comment by nick2wang** [comment]
这个测试通过实际是个bug，之前我已经提了pr：#1407
clickhouse实例请配置9000端口，8123端口是走http协议

**Comment by windyHe2020** [comment]
> 这个测试通过实际是个bug，之前我已经提了pr：#1407 clickhouse实例请配置9000端口，8123端口是走http协议
好的，感谢！
我日志最下面这一行就是9000端口的报错。我没有改过密码，但报了个认证错误，我不清楚是不是缓存的原因。现在我把clickhouse的TCP端口改成了9011,可以正常使用了。
[2022-03-10 11:57:16,051][MainThread:139631774422848][task_id:default][clickhouse.py:123][WARNING]- ClickHouse语句执行报错，语句：show databases，错误信息Code: 516.
DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. Stack trace:

DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0x879d83a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
DB::IAccessStorage::throwCannotAuthenticate(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) @ 0xea8a3df in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
DB::IAccessStorage::login(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool) const @ 0xea8a222 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
DB::Context::setUser(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0xeec7e19 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
DB::TCPHandler::receiveHello() @ 0xfd932ec in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
DB::TCPHandler::runImpl() @ 0xfd8c6fa in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
DB::TCPHandler::run() @ 0xfd9fd99 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
Poco::Net::TCPServerConnection::start() @ 0x1241daef in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
Poco::Net::TCPServerDispatcher::run() @ 0x1241f57a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
Poco::PooledThread::run() @ 0x12559339 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
Poco::ThreadImpl::runnableEntry(void*) @ 0x1255532a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug
start_thread @ 0x740b in /usr/lib64/libpthread-2.26.so
clone @ 0xed09f in /usr/lib64/libc-2.26.so

**Comment by nick2wang** [comment]
> > 这个测试通过实际是个bug，之前我已经提了pr：#1407 clickhouse实例请配置9000端口，8123端口是走http协议
> > 好的，感谢！
> > 我日志最下面这一行就是9000端口的报错。我没有改过密码，但报了个认证错误，我不清楚是不是缓存的原因。现在我把clickhouse的TCP端口改成了9011,可以正常使用了。
> > [2022-03-10 11:57:16,051][MainThread:139631774422848][task_id:default][clickhouse.py:123][WARNING]- ClickHouse语句执行报错，语句：show databases，错误信息Code: 516.
> > DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. Stack trace:
> 
> DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0x879d83a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::IAccessStorage::throwCannotAuthenticate(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) @ 0xea8a3df in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::IAccessStorage::login(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool) const @ 0xea8a222 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::Context::setUser(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0xeec7e19 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::TCPHandler::receiveHello() @ 0xfd932ec in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::TCPHandler::runImpl() @ 0xfd8c6fa in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::TCPHandler::run() @ 0xfd9fd99 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug Poco::Net::TCPServerConnection::start() @ 0x1241daef in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug Poco::Net::TCPServerDispatcher::run() @ 0x1241f57a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug Poco::PooledThread::run() @ 0x12559339 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug Poco::ThreadImpl::runnableEntry(void*) @ 0x1255532a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug start_thread @ 0x740b in /usr/lib64/libpthread-2.26.so clone @ 0xed09f in /usr/lib64/libc-2.26.so

实例资源有5分钟的缓存，某些页面上可能没刷新

**Comment by windyHe2020** [comment]
> > > 这个测试通过实际是个bug，之前我已经提了pr：#1407 clickhouse实例请配置9000端口，8123端口是走http协议
> > > 好的，感谢！
> > > 我日志最下面这一行就是9000端口的报错。我没有改过密码，但报了个认证错误，我不清楚是不是缓存的原因。现在我把clickhouse的TCP端口改成了9011,可以正常使用了。
> > > [2022-03-10 11:57:16,051][MainThread:139631774422848][task_id:default][clickhouse.py:123][WARNING]- ClickHouse语句执行报错，语句：show databases，错误信息Code: 516.
> > > DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. Stack trace:
> > 
> > 
> > DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0x879d83a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::IAccessStorage::throwCannotAuthenticate(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) @ 0xea8a3df in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::IAccessStorage::login(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool) const @ 0xea8a222 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::Context::setUser(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0xeec7e19 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::TCPHandler::receiveHello() @ 0xfd932ec in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::TCPHandler::runImpl() @ 0xfd8c6fa in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug DB::TCPHandler::run() @ 0xfd9fd99 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug Poco::Net::TCPServerConnection::start() @ 0x1241daef in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug Poco::Net::TCPServerDispatcher::run() @ 0x1241f57a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug Poco::PooledThread::run() @ 0x12559339 in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug Poco::ThreadImpl::runnableEntry(void*) @ 0x1255532a in /usr/lib/debug/.build-id/dd/2413bfffaaa33da8eaacc81543328caeec4a3e.debug start_thread @ 0x740b in /usr/lib64/libpthread-2.26.so clone @ 0xed09f in /usr/lib64/libc-2.26.so
> 
> 实例资源有5分钟的缓存，某些页面上可能没刷新

好的，感谢耐心解答！
