### ISSUE TITLE
[ 功能建议 ]表修改的版本记录，形如git版本分支

### ISSUE THREAD

**Issue by xmabul** [hhyo/archer#1412]
### 目前遇到的问题/使用障碍
【SQL上线】有记录所有DDL、DML记录，但想要查询某张表被谁修改过似乎做不到

### 希望如何解决/实现它
建议能将库表展示为一个目录形式，点击表名能查看最近修改的版本记录，还能diff前后版本区别

![image](https://user-images.githubusercontent.com/25163530/158299998-1f3203f6-da2e-4580-bc84-e24e8038b39e.png)

**Comment by LeoQuote** [comment]
archery没这个能力啊，这个一般是项目里有scheme，项目有版本记录，这样实现的
