### ISSUE TITLE
数据库不显示问题

### ISSUE THREAD

**Issue by cn-hew** [hhyo/archer#1413]
### 实例管理/数据库管理创建数据库按钮是灰色
使用了admin账号也无法创建数据库
![image](https://user-images.githubusercontent.com/31717413/158330518-1fdf826d-b8f0-45a9-86d3-8cc73713a521.png)
如上图所示，实例添加成功了 
但是无法创建新的数据库
![image](https://user-images.githubusercontent.com/31717413/158331312-edae7f93-214e-4565-b57b-680d27b1add1.png)
是否是因为bu不支持mongo以这样的方式创建
### 版本信息
 - 应用版本/分支：Release v1.8.2  
 - 部署方式：Docker

**Comment by nick2wang** [comment]
目前创建数据库只支持mysql

**Comment by cn-hew** [comment]
好的，谢谢
