### ISSUE TITLE
mongo权限管理

### ISSUE THREAD

**Issue by cn-hew** [hhyo/archer#1414]
请问mongo是否支持权限申请，目前的状况是用户只要关联了资源组中的实例 这个实例下所有的库都能进行在线查询

**Comment by nick2wang** [comment]
mongo查询是支持库级别权限控制的，你的用户是否为超级管理员？超级管理员默认拥有所有的查询权限

**Comment by cn-hew** [comment]
使用的是非超级管理员账户
![image](https://user-images.githubusercontent.com/31717413/158506863-ad4e77d6-3c2d-4053-a582-28356050e71e.png)
但是只要给予了对应的资源组后，在线查询页面选择数据库时能看到所有的库
![image](https://user-images.githubusercontent.com/31717413/158507089-bb9338be-c661-4bb2-b773-1975be277d1b.png)
它的逻辑本来就是这样 还是需要权限申请后才能看到呢？

**Comment by cn-hew** [comment]
**PS：上面那个问题我找到了，能看到但执行的时候会提示没有权限，这样也行。**
但是现在有个新的问题，如图所示我已经分配了对应库的权限
![image](https://user-images.githubusercontent.com/31717413/158510222-4a1bc917-e067-4a24-902c-3968fa672f18.png)
但是在执行查询时会权限错误
![image](https://user-images.githubusercontent.com/31717413/158510407-e2ba5f33-acd4-434b-9855-37a9c1550e6f.png)
这个是分配的权限
![image](https://user-images.githubusercontent.com/31717413/158510453-f05741ae-4352-4123-a086-f7e26774c0ea.png)
请问只是我哪里设置有问题吗
