### ISSUE TITLE
[ 问题咨询 ]sql上线功能 可以连接上实例，但检测sql时提示没有找到mysql服务

### ISSUE THREAD

**Issue by 5273727wyz** [hhyo/archer#1415]
### 问题描述
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/68524020/158749533-fc581043-7a4d-44a0-bcc7-6f42bb9d7d8e.png">
这个是我哪里没有配置好么？

### 版本信息
 - 应用版本/分支：Release v:latest 
 - 部署方式：Docker

**Comment by nick2wang** [comment]
检查一下goInception配置的备份库host

**Comment by 5273727wyz** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/68524020/158976396-7b7a7231-a7e3-4984-91df-1199d1eac796.png">
备份库的配置完全是默认的，没有过改动

**Comment by nick2wang** [comment]
> <img width="766" alt="image" src="https://user-images.githubusercontent.com/68524020/158976396-7b7a7231-a7e3-4984-91df-1199d1eac796.png">
> 备份库的配置完全是默认的，没有过改动

archery自身数据库是用的docker mysql么？

**Comment by 5273727wyz** [comment]
是的

**Comment by nick2wang** [comment]
还有goinception配置文件里的host配置
参考下配置
https://github.com/hhyo/archery/wiki/configuration#inception%E9%85%8D%E7%BD%AE

**Comment by nick2wang** [comment]
GO_INCEPTION_HOST和GO_INCEPTION_PORT不要配置成inception，目前inception只用于数据脱敏，审核一律使用goinception

**Comment by 5273727wyz** [comment]
好的，谢谢您
