### ISSUE TITLE
sql优化模块-优化工具报错：命令执行失败，失败原因:'ascii' codec

### ISSUE THREAD

**Issue by anchen418857063** [hhyo/archer#1416]
sql优化模块-优化工具报错：
命令执行失败，失败原因:'ascii' codec can't encode characters in position 224-225: ordinal not in range(128)

问题描述：
当需要优化的sql 中包含 中文 时 就报错，两个工具：soar和sqladvisor都会报错
![image](https://user-images.githubusercontent.com/45680060/158943662-e3b62ab7-501f-44e2-b826-3db2ac18ee11.png)

**Comment by hhyo** [comment]
确认一下部署环境，需要支持中文字符集，可参考dockerfire处理
