### ISSUE TITLE
[ bug ]查询审核在申请资源过多的情况下没有审核按钮了

### ISSUE THREAD

**Issue by xiaohinata** [hhyo/archer#1417]
### 重现步骤
使用人一次申请了几十个数据库查询权限，点开申请单以后，没有审核按钮，如果申请个位数数据库资源是正常的
<img width="729" alt="image" src="https://user-images.githubusercontent.com/11013971/158965689-9539bdaa-3bbb-409d-af60-bbdb55911666.png">

### 期待结果和实际结果
可以在底部看到正常的审核按钮
<img width="702" alt="image" src="https://user-images.githubusercontent.com/11013971/158965835-d8bbfa0c-d085-4341-93d9-080db04530ae.png">

### 错误日志
没有错误日志

### 版本信息
应用版本/分支：v1.8.2

部署方式：Docker

**Comment by nick2wang** [comment]
使用的什么浏览器？chrome没发现问题

**Comment by xiaohinata** [comment]
> 使用的什么浏览器？chrome没发现问题

chrome和safari都是这个问题，都是最新版本，但是我重新测试了另外一个mysql实例几百个数据库的申请，并没有问题，换个帐号重新申请也没有复现，可能是我频繁修改帐号和权限导致的bug。
