### ISSUE TITLE
大佬，能不能开放系统审计功能模块，目前来看，官方的demo演示上，有这个系统审计功能，下载部署的v1.8.2版本，没有这个功能。

### ISSUE THREAD

**Issue by vcdog** [hhyo/archer#1418]
-- 系统审计
     -| 通用审计
     -| sql上线审计
     -| 查询审计

大佬，能不能开放系统审计功能模块，目前来看，官方的demo演示上，有这个系统审计功能，下载部署的v1.8.2版本，没有这个功能。
感觉这个功能有审计功能需求的，还是很有用的。希望早日开放这个系统审计功能。感谢！

**Comment by nick2wang** [comment]
1.8.3版本会支持

**Comment by nick2wang** [comment]
1.8.3版本会支持

**Comment by vcdog** [comment]
期待v1.8.3版本

**Comment by vcdog** [comment]
另外，工具插件，demo里已经有MY2SQL，会不会一起在v1.8.3版本释放出来。那样，就完美了。

**Comment by vcdog** [comment]
产品性能对比
binlog2sql当前是业界使用最广泛的MySQL回滚工具，下面对my2sql和binlog2sql做个性能对比。

                                                my2sql	     binlog2sql
1.1G binlog生成回滚SQL	                        1分40秒	     65分钟
1.1G binlog生成原始SQL	                        1分30秒	     50分钟
1.1G binlog生成表DML统计信息、以及事务统计信息	40秒	       不支持

**Comment by nick2wang** [comment]
> 另外，工具插件，demo里已经有MY2SQL，会不会一起在v1.8.3版本释放出来。那样，就完美了。

1.8.3版本更新内容比较多，会包含my2sql模块

**Comment by LeoQuote** [comment]
最新版发布了，尝试下最新版吧
