### ISSUE TITLE
SQL查询-在线查询报错

### ISSUE THREAD

**Issue by yzb420** [hhyo/archer#1419]
### 问题描述
刚开始好着，用了一周后SQL在线查询除了select 字段1 字段2 from 表名可以使用，select * from 和select count（*） from [都无法使用，查看表结构正常，麻烦问下大佬这个是为什么，日志也没有报错
![image](https://user-images.githubusercontent.com/102197195/159604355-0264f002-af43-40d6-ad57-c7af1c6cd78e.png)

### 版本信息
 - 应用版本/分支：Release v1.8.2  
 - 部署方式：Docker、手工部署

**Comment by unknowissue** [comment]
要是没有日志的话，能再给点信息么?
比如所有表都这样么？
还是有特点的表？
这样子说一下具体的场景。

**Comment by yzb420** [comment]
感谢大佬，SQL在线查询比如：select cm.id, cm.account_group, cm.supplier_mark, cm.mdm_code, cm.classify, cm.industry, cm.full_zh, cm.area_id, cm.contact, cm.phone, cm.unit_property, cm.tax_reg_num, cm.indcom_reg_num, cm.org_num, cm.usc_num, cm.other_cer_num, cm.state, cm.dept_id, cm.company_id, cm.trading_partners_code, cm.trading_partners_name, cm.versions, cm.create_by, cm.create_date, cm.update_by, cm.update_date, cm.del_flag, cm.remarks from vms_customer_main cm WHERE cm.full_zh like CONCAT('%',
'xxx','%') and cm.del_flag = '0' and cm.state!='6' order by cm.create_date desc limit 5;这种就可以查询，这种select * from cm_basic_info limit 100;     select  count（*） from cm_basic_info；就无法查询，在所有表和所有数据库都无法查询

**Comment by unknowissue** [comment]
有没有一种可能，
我是说一种可能啊，你是使用的中文输入法的括号？
select count(*) from cm_basic_info; ?

**Comment by yzb420** [comment]
非常感谢大佬对我这个问题的解答，这个问题不是因为中英文导致，原因是因为服务器防火墙上面网络通讯问题导致

**Comment by hiflycat** [comment]
> 非常感谢大佬对我这个问题的回答，这个问题不是因为中文导致，原因是因为服务器故障导致网络通讯问题

大佬我也遇到跟你一样的情况，请问怎么解决的？
