### ISSUE TITLE
[ 问题咨询 ]请问大佬Archery运行所需的内存和cpu最低为多少？以及是否支持阿里云polardb？

### ISSUE THREAD

**Issue by jamene** [hhyo/archer#1422]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by unknowissue** [comment]
支持polardb
https://github.com/hhyo/Archery/issues/1271
