### ISSUE TITLE
[ 问题咨询 ]v1.8.3版本，oracle 工单，执行create table报错

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1425]
### 问题描述
重新初始化1.8.3版本。
在提交oracle工单，create table测试语句时，执行报错：
异常信息：local variable 'conn' referenced before assignment
![image](https://user-images.githubusercontent.com/9590209/160340861-cd729291-4b35-4f32-bd07-fb8d491cfaf1.png)

日志error：
![image](https://user-images.githubusercontent.com/9590209/160341089-7f65bd5b-a1b2-4e46-b0ae-d6b173e08591.png)

### 版本信息
 - 应用版本/分支：Release v1.8.3
 - 部署方式：Docker

**Comment by Mxiaoxiaoxiami** [comment]
遇到相同问题了，请问有解决办法吗？看样子是权限不够导致的，但是文档没有建议的账号权限

**Comment by MQMMMQM** [comment]
> 遇到相同问题了，请问有解决办法吗？看样子是权限不够导致的，但是文档没有建议的账号权限

我也遇到一样问题，后来在系统管理，配置项管理里配置了BACKUP_相关信息后，该问题解决。
