### ISSUE TITLE
[ bug ] Oracle工单，上线检测时，双引号引起的对象，检测错误

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1427]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1. 提交一个create table检测，表名（任意已存在表）用双引号引起，就可以通过检测，不报已存在；

### 期待结果和实际结果
期待结果：
执行前检测，可以检测双引号引起的对象

实际结果:
已存在表T0328：
![image](https://user-images.githubusercontent.com/9590209/160353340-27944468-fd6a-40e5-99cb-2bd57ae73081.png)

尝试提交一个create table检测：
检测通过，未发现已存在表
![image](https://user-images.githubusercontent.com/9590209/160353496-493c66cf-93ad-49e3-9ba3-2be4f9e91631.png)

### 版本信息
应用版本/分支：1.8.3
部署方式：Docker

**Comment by peng19832** [comment]
@jan-song 大佬，空了看下呢，我之前提交过pr，但不知道卡哪了，测试不通过

**Comment by peng19832** [comment]
有这几种情况：
1. dbname.table
2. "dbName".table
3. dbname."Table"
4. "dbName"."Table"
5. table
6. "Table"

**Comment by peng19832** [comment]
if '.' in object_name:
    schema_name = object_name.split('.')[0]
    object_name = object_name.split('.')[1]
    if '"' in schema_name:
        schema_name = schema_name
        if '"' not in object_name:
            object_name = object_name.upper()
    else:
        schema_name = schema_name.upper()
        if '"' not in object_name:
            object_name = object_name.upper()
else:
    schema_name = ( '"' + db_name + '"' )
    if '"' not in object_name:
        object_name = object_name.upper()

object_name = f"""{schema_name}.{object_name}"""

**Comment by nick2wang** [comment]
#1217 这个pr分支麻烦pull最新代码，然后处理下单元测试的error，如果有新的提交可以继续push上去

**Comment by peng19832** [comment]
> #1217 这个pr分支麻烦pull最新代码，然后处理下单元测试的error，如果有新的提交可以继续push上去

@nick2wang 
大佬，我就if判断了几下变量，怎么写单元测试呢？
我看以前的tests.py里，都没有这两个方法的测试的嘛
