### ISSUE TITLE
查询odps报错：查询异常报错，错误信息：NoneType object has no attribute get

### ISSUE THREAD

**Issue by lijie861221** [hhyo/archer#1430]
### 问题描述
查询odps报错：查询异常报错，错误信息：NoneType object has no attribute get
当前odps查询是这样配置的，点击测试也能通：
     实例连接：endpoint
     端口：这里要填什么？
     用户名：accesskey id
     密码：access secret

### 版本信息
 - 应用版本/分支：Release v1.8.3
 - 部署方式：Docker

**Comment by hhyo** [comment]
@cpzt 可以看一下

**Comment by cpzt** [comment]
![image](https://user-images.githubusercontent.com/20849658/162359974-7879d63e-64b2-4bc6-9a32-afc683845785.png)
实例连接: http://service.odps.aliyun.com/api
数据库一定要填
