### ISSUE TITLE
[ bug ]1.8.3 SQL查询的 js 中缺失函数

### ISSUE THREAD

**Issue by unknowissue** [hhyo/archer#1433]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1.8.3 SQL查询 不显示数据库，包括关联的实例
![image](https://user-images.githubusercontent.com/76696174/160585753-53cabb03-af5a-415a-bc54-5ef5d9645bfd.png)
控制台报错
![image](https://user-images.githubusercontent.com/76696174/160586094-2a5e1d41-6c97-4560-a2fa-d03f5dc1bb78.png)
看调用了这个函数
https://github.com/hhyo/Archery/blob/8d4b4a66f269e5e77d9c199a6b6a6c1c5b63076e/sql/templates/sqlquery.html#L389-L393
但是我又在sqlquery.html搜不到这个函数的定义
我不懂js，请问符合预期么？
还是浏览器的问题？

### 期待结果和实际结果
期待结果：

实际结果:

### 版本信息
应用版本/分支：
Release 1.8.3

部署方式：
手工部署
1.8.2升级至1.8.3

**Comment by unknowissue** [comment]
以及实例列表、会话管理、数据库管理、账号管理、参数管理 也有这个问题呢

**Comment by nick2wang** [comment]
看错了，是在这里 #1365 [common/static/dist/js/utils.js](https://github.com/hhyo/Archery/pull/1365/files#diff-524eb4052b502fbcfdcf22f6958a7a4738ca15501971c62613fb4ea85ca2263c)
是不是base.html没更新引用？
https://github.com/hhyo/Archery/blob/a8967be4a31b68f42ee3fde34cf776c4bb525bf5/common/templates/base.html#L304

**Comment by unknowissue** [comment]
嗷嗷，我sb了，忘记更新nginx的配置文件了
```bash
location /static {
          alias /archery/Archery-1.8.3/static; #此处指向settings.py配置项STATIC_ROOT目录的绝对路径，用于nginx收集静态资源
        }
```
