### ISSUE TITLE
[bug]升级1.8.3后，普通用户页面上下载按钮出不来

### ISSUE THREAD

**Issue by lijie861221** [hhyo/archer#1434]
升级1.8.3后，普通用户页面上下载按钮出不来
演示demo里也是这样的。
![image](https://user-images.githubusercontent.com/33362111/160734568-912268b2-0dff-479e-84a8-b111dbe94347.png)

**Comment by nick2wang** [comment]
新版本下载做了权限控制 #1369
![image](https://user-images.githubusercontent.com/33473924/160735169-9ef66cc3-6a21-4169-90ad-a2cb5e89a611.png)

**Comment by lijie861221** [comment]
在demo里怎么没找到？https://demo.archerydms.com/  ![image](https://user-images.githubusercontent.com/33362111/160735702-324fbec8-9794-4a97-935a-adef4bcaa0ed.png)

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/blob/a8967be4a31b68f42ee3fde34cf776c4bb525bf5/src/init_sql/v1.8.3.sql#L30
 
定义和判断存在问题，需要fix一下

**Comment by lijie861221** [comment]
明白了，谢谢！
