### ISSUE TITLE
[ LDAP认证失败 ]1.8.3版本开启LDAP后日志报连接不上ldap服务器

### ISSUE THREAD

**Issue by JCchenxiang** [hhyo/archer#1435]
### 问题描述
开启LDAP后登录失败，查看日志报
[2022-03-30 13:44:30,759][DummyThread-1:139977528105544][task_id:django_auth_ldap][backend.py:368][WARNING]- Caught LDAPError while authenticating 25391: SERVER_DOWN({'desc': "Can't contact LDAP server", 'errno': 107, 'info': 'Transport endpoint is not connected'},)
下面是IDAP配置
![Uploading 63E5764FDEE82995FBF53C6127CB3B7C.jpg…]()

### 版本信息
 - 应用版本/分支：Release 1.8.3
 - 部署方式：Docker K8S

**Comment by unknowissue** [comment]
？图裂了？

**Comment by CorollaD** [comment]
我也遇到这个问题了

**Comment by unknowissue** [comment]
啥配置呢？
先在宿主机上用[ ldapsearch]( https://blog.csdn.net/weiguang1017/article/details/79234623)方法看看能查询到么？

**Comment by JCchenxiang** [comment]
已解决，ldap服务器白名单加错了，nc命令测试端口能通不代表能连接idap服务，最好用opensearch命令测试一下
ldapsearch -H ldap://***:389 -D "CN=,CN=Users,DC=,DC=com" -U "" -w "***" -v -d 1
安装：yum install -y openldap openldap-servers openldap-clients

**Comment by JCchenxiang** [comment]
感谢各位🙏

**Comment by CorollaD** [comment]
> 已解决，ldap服务器白名单加错了，nc命令测试端口能通不代表能连接idap服务，最好用opensearch命令测试一下 ldapsearch -H ldap://_**:389 -D "CN=,CN=Users,DC=,DC=com" -U "" -w "**_" -v -d 1 安装：yum install -y openldap openldap-servers openldap-clients

哥们儿，可以把你的settings模版分享一下吗
