### ISSUE TITLE
高危DDL限制失效

### ISSUE THREAD

**Issue by TonSimpson** [hhyo/archer#1437]
### 问题描述
研发提交了如下SQL，里面包含了drop语句，但是archery直接审核通过，没有驳回。相当于直接绕过了配置项的DDL限制
ALTER TABLE
  `my_tables` DROP INDEX `IND_UNIQUE`,
ADD
  UNIQUE INDEX `UNIQ_INDEX`(
    `YM`,
    `PID`,
    `PGID`,
    `ACCOUNTINT_TYPE`,
    `SHARE_COMPANY`,
    `ACTUAL_RECONCILIATION_TYPE`
  ) USING BTREE

高危DDL设置：
![image](https://user-images.githubusercontent.com/97860418/160958872-a9d0b053-0dd1-4b77-a7b8-abd5b388d95d.png)

### 版本信息
 - 应用版本/分支：Release v1.8.2
 - 部署方式：手工部署

**Comment by nick2wang** [comment]
`^drop`只能匹配drop开头的语句，可以这样改下
`^truncate|^rename|^drop|^alter\s+table\s+(.+?)\s+drop`

**Comment by peng19832** [comment]
alter语句不是就应该人工审核么？为什么会自动审核通过，如果ddl都自动放行，感觉没必要审核了，平台只充当了备份和留痕的角色
