### ISSUE TITLE
建议同一个资源组可以配置多个流程

### ISSUE THREAD

**Issue by anchen418857063** [hhyo/archer#1441]
### 目前遇到的问题/使用障碍
公司日常业务修改数据dml 特别多，DBA操作操作工单的工作非常繁重，并且经常有深夜需要协助执行工单的情况
### 希望如何解决/实现它
建议同一资源组可以配置多个流程按数据库操作类型来区分：提交工单界面新增下拉选择流程downlist，由发起人选择需要走哪个流程。这样我的dml 操作可以配置一个流程，审批流程里面就到开发leader就可以执行，不需要到DBA。而只要包含ddl操作的工单必须选择到DBA才能执行。

**Comment by nick2wang** [comment]
由发起人选择不可靠且繁琐，倒不如把审批流程细分为ddl和dml分开配置

**Comment by anchen418857063** [comment]
这个也行
