### ISSUE TITLE
archery sql慢查询配置

### ISSUE THREAD

**Issue by super-dx** [hhyo/archer#1445]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
archery部署慢sql，手动执行analysis_slow_query.sh脚本时，报错。
报错信息如下：
DBI connect(';host=/home/mysql/mysql-slow-2022-04-01.log;mysql_read_default_group=client','',...) failed: Unknown MySQL server host '/home/mysql/mysql-slow-2022-04-01.log' (2) at /usr/bin/pt-query-digest line 1001.
failed
### 版本信息
我是使用docker部署的archery、安装的pt工具是pt-query-digest 3.3.1版本、

**Comment by nick2wang** [comment]
应该是配置问题，脚本analysis_slow_query.sh贴出来看下

**Comment by super-dx** [comment]
#!/bin/bash
DIR="$( cd "$( dirname "$0"  )" && pwd  )"
cd ${DIR}

#配置Archery数据库的连接地址
archery_db_host="10.105.23.162"   ###我的archery数据库与实例数据库是同一台机器，端口不同
archery_db_port=3306
archery_db_user="root"
archery_db_password="123456"
archery_db_database="archery"

#被分析实例的慢日志位置，建议定期清理日志文件，否则会影响分析效率
slowquery_file="/home/mysql/log_slow.log"


#pt-query-digest可执行文件路径
pt_query_digest="/usr/bin/pt-query-digest"

#被分析实例的连接信息
hostname="10.105.23.162:33333" # 需要和Archery实例配置中的内容保持一致，用于筛选，配置错误会导致数据无法展示

#获取上次分析时间，初始化时请删除last_analysis_time_$hostname文件，可分析全部日志数据
if [[ -s last_analysis_time_${hostname} ]]; then
    last_analysis_time=`cat last_analysis_time_${hostname}`
else
    last_analysis_time='1000-01-01 00:00:00'
fi

#收集日志
#RDS需要增加--no-version-check选项
${pt_query_digest} \
--user=${archery_db_user} --password=${archery_db_password} --port=${archery_db_port} \
--review h=${archery_db_host},D=${archery_db_database},t=mysql_slow_query_review  \
--history h=${archery_db_host},D=${archery_db_database},t=mysql_slow_query_review_history  \
--no-report --limit=100% --charset=utf8 \
--since "$last_analysis_time" \
--filter="\$event->{Bytes} = length(\$event->{arg}) and \$event->{hostname}=\"$hostname\"  and \$event->{client}=\$event->{ip} " \
${slowquery_file} > /var/log/analysis_slow_query.log

if [[ $? -ne 0 ]]; then
echo "failed"
else
echo `date +"%Y-%m-%d %H:%M:%S"`>last_analysis_time_${hostname}
fi

**Comment by super-dx** [comment]
@nick2wang

**Comment by nick2wang** [comment]
是否使用的是云数据库？

**Comment by super-dx** [comment]
不是，是本地数据库

**Comment by nick2wang** [comment]
慢日志路径和文件名是正确的么？slowquery_file="/home/mysql/log_slow.log"

**Comment by super-dx** [comment]
是否需要实例数据库首先开启慢sql，然后脚本中的慢日志路径和文件名（slowquery_file的值）就是实例数据库慢sql的路径和文件名？

**Comment by nick2wang** [comment]
> 是否需要实例数据库首先开启慢sql，然后脚本中的慢日志路径和文件名（slowquery_file的值）就是实例数据库慢sql的路径和文件名？

是的

**Comment by super-dx** [comment]
我更改过后，手动执行脚本没有报错了，但是我手动执行后，去查看archery库里的两张表，并无数据，web端也无数据。
mysql实例的慢日志文件也没有数据，我后来有测试了下这个脚本，首次执行会出现
![image](https://user-images.githubusercontent.com/102796903/162143391-c74eab31-8d39-4e7c-8fad-0016249a8c1f.png)
这种情况，再次执行就没有输出信息了

**Comment by super-dx** [comment]
@nick2wang

**Comment by hhyo** [comment]
不用脚本，直接执行分析操作试试，前提是慢日志文件里面有内容

**Comment by super-dx** [comment]
已经解决，非常感谢 @hhyo @nick2wang

**Comment by catsun26** [comment]
> 已经解决，非常感谢 @hhyo @nick2wang

这个问题是怎么解决的，也遇到一样的问题
