### ISSUE TITLE
如何通过archery创建库呢

### ISSUE THREAD

**Issue by cn-hew** [hhyo/archer#1447]
在archery中如何创建库呢，use命令好像用不了 show也不行，
我通过Navicat创建一个新库并添加一些内容后archery看不到这些新建的库

**Comment by nick2wang** [comment]
1. sql上线提交create database，或实例管理-数据库管理-创建数据库
2. 实例资源有5分钟缓存

**Comment by cn-hew** [comment]
mongo实例如何创建呢

**Comment by nick2wang** [comment]
> mongo实例如何创建呢

mongo还不支持

**Comment by cn-hew** [comment]
我通过navicat在一个mongo实例下创建了库，并且插入了数据，在Archery中没有这个库，这种情况是我操作问题吗

**Comment by nick2wang** [comment]
> 我通过navicat在一个mongo实例下创建了库，并且插入了数据，在Archery中没有这个库，这种情况是我操作问题吗

过了5分钟还是看不到么？

**Comment by cn-hew** [comment]
> > 我通过navicat在一个mongo实例下创建了库，并且插入了数据，在Archery中没有这个库，这种情况是我操作问题吗
> 
> 过了5分钟还是看不到么？
是的，看不到
