### ISSUE TITLE
测试一个普通用户申请sql查询权限报错

### ISSUE THREAD

**Issue by super-dx** [hhyo/archer#1450]
### 问题描述
新创建一个普通用户test,
![企业微信截图_1649217455303](https://user-images.githubusercontent.com/102796903/161902968-f14739b0-b4d2-4390-b6db-7f0918a2b7fa.png)
上图是我给这个test用户分配的权限，然后登录test用户，如果直接去查询sql提示不被允许。
申请sql查询权限，
![企业微信截图_16492175451677](https://user-images.githubusercontent.com/102796903/161904068-3b85fa8d-5dac-434d-87d5-c8ed9e71c11b.png)
审批流程是我自己创建的用户，权限都是全分配的，
![企业微信截图_16492241748531](https://user-images.githubusercontent.com/102796903/161904441-82887441-b174-4351-8874-5788f2f9e00c.png)
审批通过后，我去测试查询申请的数据库查询权限
![企业微信截图_16492242788715](https://user-images.githubusercontent.com/102796903/161904631-8e28fa21-7832-41f2-b990-46d81741d3bd.png)
如上图，提示我不被允许查询的，与未申请查询权限时做查询操作是一样的提示。
请问，是我的test用户分配的权限不对吗？

**Comment by super-dx** [comment]
哪位大佬帮忙看看

**Comment by nick2wang** [comment]
把这个权限加上
![image](https://user-images.githubusercontent.com/33473924/162860844-93d19623-ec8b-4c93-b335-917c0b01debb.png)

**Comment by super-dx** [comment]
解决了 ，非常感谢
