### ISSUE TITLE
普通用户看不到下载按钮，把所有权限给它也不行

### ISSUE THREAD

**Issue by wqbbs911** [hhyo/archer#1453]
新建一个用户，给他所有权限，除了超级用户。但是在在线查询页看不到导出数据按钮。
![图片](https://user-images.githubusercontent.com/30170870/162415137-fdaaf2ba-89e6-4a2a-a1ce-d5a7bfaf60e3.png)

**Comment by wqbbs911** [comment]
数据库里查看已经有：
![图片](https://user-images.githubusercontent.com/30170870/162415350-e2d7edcc-369a-432b-b28d-0dc2a80f879c.png)

![图片](https://user-images.githubusercontent.com/30170870/162415499-114795fa-7bd5-4329-82e1-67c81a83f926.png)

**Comment by nick2wang** [comment]
最新代码已修复该问题 #1440

**Comment by wqbbs911** [comment]
> 最新代码已修复该问题 #1440

现在能手动应用到1.8.3上吗？还是要等下个版本？
我是通过docker方式安装的

**Comment by nick2wang** [comment]
> > 最新代码已修复该问题 #1440
> 
> 现在能手动应用到1.8.3上吗？还是要等下个版本？ 我是通过docker方式安装的

最简单的办法：下载最新变更文件 [views.py](https://github.com/hhyo/Archery/blob/master/sql/views.py)，然后用docker cp命令覆盖docker archery里的/opt/archery/sql/views.py

**Comment by wqbbs911** [comment]
好的，已解决，谢谢！
