### ISSUE TITLE
数据库表数据导出功能

### ISSUE THREAD

**Issue by yzb420** [hhyo/archer#1458]
首先感谢楼主分享这个SQL审核系统，楼主是否可以加一个表全量数据导出功能

**Comment by michael-liumh** [comment]
全量导出一般耗时都是相当久的，而且从安全角度上考虑，也不建议直接从平台导出，都是提申请，让DBA协助导出的

**Comment by yzb420** [comment]
感谢大佬回答，还是大佬考虑周全

**Comment by weideguo** [comment]
数据量不大的化可以直接在`SQL查询` -> `在线查询`查询然后导出，但这个导出只是前端功能，性能不高，对超过几万以上记录的支持不好，可能会出现页面卡住。

**Comment by michael-liumh** [comment]
有哪个性能好的导出框架推荐一下吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月4日(周六) 凌晨2:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hhyo/Archery] 数据库表数据导出功能 (Issue #1458)




 
数据量不大的化可以直接在SQL查询 -&gt; 在线查询查询然后导出，但这个导出只是前端功能，性能不高，对超过几万以上记录的支持不好，可能会出现页面卡住。

**Comment by hhyo** [comment]
相关issue也有几个，后续看是否确实要做异步导出，即使真要做，数据也需要存储在类似对象存储的存储系统中，此issue先关闭
