### ISSUE TITLE
[ 问题咨询 ]oracle DML工单状态卡在确认中

### ISSUE THREAD

**Issue by zhxleon** [hhyo/archer#1459]
### 问题描述
工单状态：
![G3(85(4Z1WKH5@P}R(7{` I](https://user-images.githubusercontent.com/83218770/163082306-8990c5e6-ce3d-43c5-9fdc-ce6a76e87b56.png)

![(X 1I8SM{ KT)YC Y_@5S~M](https://user-images.githubusercontent.com/83218770/163084651-fb3cb378-8ef5-43d6-84a9-95705f60e2b8.png)

qmonitor：
![A3U}SI`{%9_ N$VOJPVAHFL](https://user-images.githubusercontent.com/83218770/163084019-78a63355-5b6a-4d79-8835-dbbdf264a60e.png)

如上图
目标是oracle数据库，12号10点34分开始执行工单，由于影响行数有600W，并且勾选了备份，现在工单状态异常，卡在确认中无法继续往下走，但是SQL实际已经执行完了，这种情况可能是因为做备份时间太久导致异常，但是现在备份肯定也已经无法完成了

1. 请问这种情况如何排查问题和解决异常？

2. 重启archery会不会有重复执行的风险？

### 版本信息
 - 应用版本/分支：Release v1.8.3  
 - 部署方式：Docker

**Comment by thcoffee** [comment]
你这个数据量也太大了。是不是logminer一直在抓undo 的sql啊。看看oracle的会话中是否有在做相关作业的。实话实说我都不建议这么大数据量还用这种自动上线的备份功能。不如expdp一类的工具划算。

**Comment by zhxleon** [comment]
有和同事说过大数据量不要备份，但是也有失误的时候，虽然日志没打印备份失败，但是备份肯定是失败的，session中也没有查到相应会话，根据结果查询，第三条sql是已经执行完成了的，说明工单卡住是因为备份导致的，现在希望知道的是：
1.有什么补救措施
2.有什么未知的风险

**Comment by hhyo** [comment]
手动调整状态就行，可以看下qcluster log是否有相关错误信息，以及数据库相关工单任务的执行结果，https://demo.archerydms.com/admin/django_q/failure/

并不会有其他风险

**Comment by thcoffee** [comment]
我昨天也挑战了一下，oracle一百多万行吧，也是卡主了，卡了几个小时没结束。以后大修改看来确实要人工做了。
