### ISSUE TITLE
[ bug ]SQL上线和查询均不支持有emoji的数据

### ISSUE THREAD

**Issue by michael-liumh** [hhyo/archer#1460]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 截图
![image](https://user-images.githubusercontent.com/40595864/163133484-7736e92f-0431-49de-9254-daabfda0ab03.png)
如图

**Comment by nick2wang** [comment]
确认下archery数据库query_log表字符集是否为utf8mb4，不然不支持存储emoji

**Comment by michael-liumh** [comment]
ok，确实是字符集的问题，谢谢

**Comment by zxf-shine** [comment]
求详解

**Comment by zxf-shine** [comment]
我是查询能看到emoji数据，但是插入数据报错
