### ISSUE TITLE
系统设置，AUTO_REVIEW_WRONG失效的问题。

### ISSUE THREAD

**Issue by thcoffee** [hhyo/archer#1462]
### 问题描述
系统设置 AUTO_REVIEW_WRONG =1 ，告警就上线自动驳回，mysql是可以的。 但是oracle就不行。oracle已经告警了。也不自动驳回。
请问大家知道怎么回事么。

### 版本信息
 - 应用版本/分支：Release v1.8.3
 - 部署方式：Docker

**Comment by hhyo** [comment]
#1452

**Comment by thcoffee** [comment]
> #1452

十分感谢 ，不是一件事 ，您发的这个AUTO_REVIEW_DB_TYPE支持oracle是针对AUTO_REVIEW这个的辅助选项。  我说的这个是AUTO_REVIEW_WRONG，这个就算不开自动审核，只要sql审查告警就自动驳回了。    

我根据您的提示打开了AUTO_REVIEW选项，设置了AUTO_REVIEW_DB_TYPE支持mysql和oracle。删除行数超过设置的值，仍然不自动驳回。
![image](https://user-images.githubusercontent.com/26478684/163698962-37a2eebb-e182-4eba-a021-5fa4594c7b88.png)

**Comment by thcoffee** [comment]
> #1452

![image](https://user-images.githubusercontent.com/26478684/163699086-c05583bf-bc2f-4c66-9617-1cfca3f7f64b.png)
这里其实我不开sql上线自动审批，只要sql检查告警了。就会自动驳回。

**Comment by thcoffee** [comment]
![image](https://user-images.githubusercontent.com/26478684/163699129-ffb1bfda-f4eb-4c7c-9f10-2731d318b3cf.png)
这里就算我把AUTO_REVIEW关闭掉，仍然会自动驳回。只要我将AUTO_REVIEW_WRONG =1 就可以。

**Comment by hhyo** [comment]
看了下这个是非MySQL的审核结果没有注入error和warning数量导致，后面可以修复一下

**Comment by thcoffee** [comment]
> 看了下这个是非MySQL的审核结果没有注入error和warning数量导致，后面可以修复一下

十分感谢
