### ISSUE TITLE
[ bug ]oracle的sql上线，备份的sql异常。

### ISSUE THREAD

**Issue by thcoffee** [hhyo/archer#1467]
oracle 的sql上线的时候，备份用logminer去抓undo的sql 。如果sql巨长会自动变成2行。  archery获取回退sql的时候就会发现串行了，一个完整的sql被拆分成了2个sql。希望能进行修复。谢谢。
### 版本信息
应用版本/分支：v1.8.3

部署方式：Docker

**Comment by unknowissue** [comment]
能举例说明一下么？
给个测试demo？

**Comment by thcoffee** [comment]
> 能举例说明一下么？ 给个测试demo？

![image](https://user-images.githubusercontent.com/26478684/163698037-88b42a70-fe78-44df-8763-c312af1acf77.png)

**Comment by thcoffee** [comment]
> 能举例说明一下么？ 给个测试demo？

logminer分析redo的时候生成的字典对超长的sql会截成2行。查V$LOGMNR_CONTENTS的时候需要多行才能拼成一个完整的sql。表很多字段、内容又特别长的就容易这样。

**Comment by thcoffee** [comment]
![image](https://user-images.githubusercontent.com/26478684/163737300-c6e91854-52ef-4faa-8872-7ed6d7eb8cdd.png)
V$LOGMNR_CONTENTS确定唯一行
1、rs_id,ssn确定唯一行，Order by t.scn,t.rs_id,t.ssn基本可以确定sql在redo里的执行顺序
2、csf是sql_redo过长（超过4000字节）其值就为1，从第一个csf=1到最后一个cdf=0代表完整的一行。

**Comment by peng19832** [comment]
> 能举例说明一下么？ 给个测试demo？

这个问题，我也遇到了#1249
不止长sql有问题，还会打印出不相关的语句

**Comment by thcoffee** [comment]
select 
xmlagg(xmlparse(content sql_redo)  order by  scn,rs_id,ssn,rownum).getclobval() ,
xmlagg(xmlparse(content sql_undo)  order by  scn,rs_id,ssn,rownum).getclobval() 
from v$logmnr_contents
where  SEG_OWNER not in ('SYS','SYSTEM')
and session# = (select sid from v$mystat where rownum = 1)
and serial# = (select serial# from v$session s where s.sid = (select sid from v$mystat where rownum = 1 ))  
group by  scn,rs_id,ssn  order by scn desc;

我把获取undo的那个语句改了一下，这样写的话就可以获取完整的超长sql了。
之前
![image](https://user-images.githubusercontent.com/26478684/165711578-174015f7-9552-4a84-8d0a-114bb10d3199.png)
之后
![image](https://user-images.githubusercontent.com/26478684/165711510-8a6d132a-722d-4e5c-a7dc-a0531757572a.png)

**Comment by unknowissue** [comment]
> select xmlagg(xmlparse(content sql_redo) order by scn,rs_id,ssn,rownum).getclobval() , xmlagg(xmlparse(content sql_undo) order by scn,rs_id,ssn,rownum).getclobval() from v$logmnr_contents where SEG_OWNER not in ('SYS','SYSTEM') and session# = (select sid from v$mystat where rownum = 1) and serial# = (select serial# from v$session s where s.sid = (select sid from v$mystat where rownum = 1 )) group by scn,rs_id,ssn order by scn desc;
> 
> 我把获取undo的那个语句改了一下，这样写的话就可以获取完整的超长sql了。 之前 ![image](https://user-images.githubusercontent.com/26478684/165711578-174015f7-9552-4a84-8d0a-114bb10d3199.png) 之后 ![image](https://user-images.githubusercontent.com/26478684/165711510-8a6d132a-722d-4e5c-a7dc-a0531757572a.png)

麻烦提交一个pr呗！
非常感谢！

我最近辞职了，我本地没环境

**Comment by thcoffee** [comment]
> > select xmlagg(xmlparse(content sql_redo) order by scn,rs_id,ssn,rownum).getclobval() , xmlagg(xmlparse(content sql_undo) order by scn,rs_id,ssn,rownum).getclobval() from v$logmnr_contents where SEG_OWNER not in ('SYS','SYSTEM') and session# = (select sid from v$mystat where rownum = 1) and serial# = (select serial# from v$session s where s.sid = (select sid from v$mystat where rownum = 1 )) group by scn,rs_id,ssn order by scn desc;
> > 我把获取undo的那个语句改了一下，这样写的话就可以获取完整的超长sql了。 之前 ![image](https://user-images.githubusercontent.com/26478684/165711578-174015f7-9552-4a84-8d0a-114bb10d3199.png) 之后 ![image](https://user-images.githubusercontent.com/26478684/165711510-8a6d132a-722d-4e5c-a7dc-a0531757572a.png)
> 
> 麻烦提交一个pr呗！ 非常感谢！
> 
> 我最近辞职了，我本地没环境

哦了，我头一次提pr，我尝试一下。
