### ISSUE TITLE
archery上配置TiDB后，无法执行工单

### ISSUE THREAD

**Issue by Hank-Yoon** [hhyo/archer#1468]
### 问题描述
在archery上配置TiDB数据库后，工单可以正常提交，但是审核通过后，在执行工单时，会提示read_only=1，导致在archery无法执行工单。

### 版本信息
 v1.7.1

**Comment by hydgladiator** [comment]
你确定配置的是读写节点么？

**Comment by Hank-Yoon** [comment]
> 

确定啊

**Comment by hydgladiator** [comment]
应该不会的，我之前接入过TiDB，都是可执行的。
TiDB用的是4000端口，不是3306.

**Comment by Hank-Yoon** [comment]
> 应该不会的，我之前接入过TiDB，都是可执行的。 TiDB用的是4000端口，不是3306.

当然是4000端口啊。
<img width="276" alt="image" src="https://user-images.githubusercontent.com/16020101/163803253-ef870d2a-0780-48ba-a8b9-0d73e6f3f876.png">

**Comment by hydgladiator** [comment]
正常JDBC协议，都是可以用的。
显示的read_only为真，表示主机或者账号为只读范畴

**Comment by Hank-Yoon** [comment]
> 正常JDBC协议，都是可以用的。 显示的read_only为真，表示主机或者账号为只读范畴

账号是root。实例read_only=0
<img width="356" alt="image" src="https://user-images.githubusercontent.com/16020101/163803526-367a149f-8556-4420-8c89-0c3cc5553f97.png">
但是在archery上执行就提示read_Only=1

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/issues/537

**Comment by Hank-Yoon** [comment]
> #537

我去试试，非常感谢。

**Comment by Hank-Yoon** [comment]
> #537

已解决，非常感谢。
