### ISSUE TITLE
[ 需求 ]能否单独提供一个权限，让工单发起人在没有工单执行权限的前提下，可手动终止自己提交的工单

### ISSUE THREAD

**Issue by michael-liumh** [hhyo/archer#1470]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

1. 工单发起人，提交了一张工单，但并没有执行权限，需要等leader审核并执行，这种情况下，工单发起人是没有SQL工单执行权限的；
2. 此时，工单发起人要终止这张工单的话，要么由leader终止，要么赋予工单发起人SQL工单执行权限；
3. 需求：在不赋予发起人工单执行权限的前提下，单独将终止工单的权限分离出来，方便工单发起人自己终止工单

**Comment by hhyo** [comment]
调整为任何状态提交人都可以终止应该就可以了

**Comment by michael-liumh** [comment]
怎么调整呢？我看权限那里没有对应的权限



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月29日(周五) 晚上8:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hhyo/Archery] [ 需求 ]能否单独提供一个权限，让工单发起人在没有工单执行权限的前提下，可手动终止自己提交的工单 (Issue #1470)




 
调整为任何状态提交人都可以终止应该就可以了
