### ISSUE TITLE
[ 功能建议 ]对于分表的查询能否优化？

### ISSUE THREAD

**Issue by irwinai** [hhyo/archer#1471]
分表的话查询太麻烦，需要知道在哪张表select xx from user_0 这样
能否优化查询方式，只需要逻辑表名查询，如select * from user

**Comment by nick2wang** [comment]
如果是用例如mycat的中间件做的分表直接查询中间件就好了，archery来做这个事的话效率太低，定位也不同

**Comment by irwinai** [comment]
请问整合有相关文档吗？

**Comment by nick2wang** [comment]
> 请问整合有相关文档吗？

你说的整合是指？
