### ISSUE TITLE
sql回滚语句报错

### ISSUE THREAD

**Issue by super-dx** [hhyo/archer#1473]
### 问题描述
sql上线回滚语句报错
(1146, "Table '10.0.0.1_33333_test_01.$_$inception_backup_information$_$' doesn't exist")
参考一些解决文档，确定
![image](https://user-images.githubusercontent.com/102796903/163954017-94663556-a96d-438f-9b9c-cb9355e4a636.png)
![image](https://user-images.githubusercontent.com/102796903/163954095-07c66844-e182-44af-9b91-7054831f0873.png)
以上内容都是没问题的，下图是我的inception和备份库的连接信息
![image](https://user-images.githubusercontent.com/102796903/163954247-29c89b3b-2292-4ef9-b554-5009961c7202.png)
目前没找到问题原因，望解答
### 版本信息
 - 应用版本/分支：Archery1.8.0
 - 部署方式：Docker部署

**Comment by michael-liumh** [comment]
升级一下版本吧，目前新版本没发现这个问题，是能正常备份的

**Comment by super-dx** [comment]
升级archery的版本吗？ @michael-liumh

**Comment by michael-liumh** [comment]
是的

**Comment by super-dx** [comment]
@请问还有别的解决办法吗？除了升级版本 @michael-liumh

**Comment by super-dx** [comment]
我重新部署了archery1.8.3，但还是这个问题 @michael-liumh
