### ISSUE TITLE
[ 功能建议 ]可否建个QQ交流群，方便大家沟通

### ISSUE THREAD

**Issue by MrAndyMing** [hhyo/archer#1474]
希望可以建个QQ群，方便大家沟通

**Comment by nick2wang** [comment]
issues可以在网络上被搜索到，覆盖范围更广，目前有问题还是在issue上沟通吧

**Comment by MrAndyMing** [comment]
哦，好的，请问后续平台可否支持pgsql的备份，回滚功能？

**Comment by nick2wang** [comment]
> 哦，好的，请问后续平台可否支持pgsql的备份，回滚功能？

目前没有计划，如果你有这方面可行的方法或思路可以提出来，欢迎pr

**Comment by bardyang** [comment]
> 你好!感谢你反馈的问题/bug，但是你的描述好像是空的，我们需要你完整的信息，这样才能帮你解决问题 如果不知道怎么写，在新建issue的时候有若干个模板可供选择，祝好！



> > 哦，好的，请问后续平台可否支持pgsql的备份，回滚功能？
> 
> 目前没有计划，如果你有这方面可行的方法或思路可以提出来，欢迎pr

archery 有没有QQ交流群，如果有请拉我一下
