### ISSUE TITLE
oracle ddl上线执行卡住

### ISSUE THREAD

**Issue by thcoffee** [hhyo/archer#1476]
### 问题描述
昨天上oracle  DDL语句  差不多80多条，包含建表 加索引  加字段描述。上线审批执行后就迟迟不完。  从oracle里看gv$session ，没有相关的会话。但是在应用端netstat 能看到连接oracle数据库的网络连接。连续上了3次都这样。  最后吧语句复制到数据库里直接执行几秒钟就完事了。oracle版本是11.2.0.3  rac 

 - 应用版本/分支：Release v1.8.3  
 - 部署方式：Docker

**Comment by thcoffee** [comment]
今天上了3个oracle的ddl，一个建表，一个加字段  ，一个加主键。  又卡主了。手工做2-3秒就完事了。

**Comment by thcoffee** [comment]
今天上线了1个oracle的ddl，新增一个表的字段。一个也卡住了。手工1秒完事。

**Comment by nick2wang** [comment]
看下qcluster同时间的日志有没有报错，以及qcluster任务执行情况http://host:9123/admin/django_q/failure/

**Comment by thcoffee** [comment]
![image](https://user-images.githubusercontent.com/26478684/167337229-be793e5f-6417-4b02-847a-20df14c1233c.png)
![image](https://user-images.githubusercontent.com/26478684/167337273-743aa424-bf88-4e8f-9c08-ea693cc0372b.png)
![image](https://user-images.githubusercontent.com/26478684/167337301-ffe8752e-1e23-4dce-a096-00fa22a3a3aa.png)
Failed tasks里没有内容 只有ddl会这样卡住，dml没事。

**Comment by thcoffee** [comment]
![image](https://user-images.githubusercontent.com/26478684/167337541-f8dec6f6-ed20-4814-a63a-7c99f413f92c.png)
我发现其他的流程  启动后都会加入ALTER SESSION SET CURRENT_SCHEMA =xxx  卡主的没有这句。

**Comment by nick2wang** [comment]
看日志有没有报错；取消备份再执行试下

**Comment by thcoffee** [comment]
抛出异常了。15分钟后报了cx_Oracle.OperationalError: ORA-03114: not connected to ORACLE。 应该是数据库或者防火墙方面的问题。连接被强制中断了。
![image](https://user-images.githubusercontent.com/26478684/167356342-f9b40c1b-8287-4861-b2a3-83e9bb18b7ef.png)
我分析一下原因，有结果后续更新。

**Comment by thcoffee** [comment]
绕过防火墙就没事了。这事我也挺好奇，dml就啥事没有，ddl就过不去。难道防火墙还能识别出来语句类型。

**Comment by thcoffee** [comment]
我排查到了 
select dbms_metadata.get_ddl(object_type,object_name,owner)
                    from all_objects where (object_name=upper( '{object_name}' ) or OBJECT_NAME = '{sqlitem.object_name}')
                    and owner='{workflow.db_name}'
执行这句的时候会卡住，我用cx_oracle   pyodbc都试过，都会卡住。不用防火墙不会卡住，用防火墙普通的oracle客户端软件，java程序也不会卡住。

**Comment by thcoffee** [comment]
我换成python3.6，这个查询就不会卡住了。  docker里的3.9.10   我本地的3.10.4 都会卡住。

**Comment by thcoffee** [comment]
水落石出了，是防火墙认为那个请求有危险给拦截了。厂家给调整了一下策略就好了。

**Comment by arron-6z** [comment]
> 水落石出了，是防火墙认为那个请求有危险给拦截了。厂家给调整了一下策略就好了。

能说一下具体调整哪里了吗，我也遇到了这个问题，感谢
