### ISSUE TITLE
[ 问题咨询 ]执行SQL查询提示有SQL攻击行为

### ISSUE THREAD

**Issue by solon-liu** [hhyo/archer#1477]
我在执行一条SQL查询，提示有SQL攻击行为不能返回结果，可以帮忙看下吗

SQL语句：
SELECT
test
FROM
  db1.t1 ot1
  LEFT JOIN db2.t2 bp ON ot1.project_sys_no = bp.sys_no
  LIMIT 10

F12返回数据：
{
	 "Code":"Internal_Error",
	 "Message": "检测到攻击行为，事件ID{7038995208496152083}，如有疑问，请联系：400-151-8800"
}

**Comment by nick2wang** [comment]
这个拦截行为不是来自archery，查了下这个电话号码是平安金融云？大概是误触了云服务商的风控策略（可能是语句被误认为sql注入payload）

**Comment by solon-liu** [comment]
好的，非常感谢，我们已经找到原因了。
