### ISSUE TITLE
[ 功能建议 ]允许多个alter操作

### ISSUE THREAD

**Issue by yzb420** [hhyo/archer#1482]
### 目前遇到的问题/使用障碍
![image](https://user-images.githubusercontent.com/102197195/165872385-8c6e2e7a-f427-4a50-9ff0-169388933520.png)

### 希望如何解决/实现它
允许多个alter操作

**Comment by 402309718** [comment]
检查goinception config.toml 配置merge_alter_table 应该是merge_alter_table影响

**Comment by yzb420** [comment]
已修改，非常感谢大佬支撑。
