### ISSUE TITLE
[ 功能建议 ]换成goinception脱敏后不能支持select * from XXX union select * from XXX;

### ISSUE THREAD

**Issue by liujiashun0520** [hhyo/archer#1495]
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
确认下goinception版本，同时看能否在 https://demo.archerydms.com/ 重现？

**Comment by liujiashun0520** [comment]
> 确认下goinception版本，同时看能否在 https://demo.archerydms.com/ 重现？

goinception 版本为：v1.2.5-34；
我是注释了以下代码：
 (因为发现inception其实可以注释掉以支持union select * 和select 具体字段；当前换成goinception注释掉后发现只支持select具体字段不支持select *）
       if  SysConfig().get('query_check'):
            # 解析查询语句，禁用部分Inception无法解析关键词
            p = sqlparse.parse(sql)[0]
            for token in p.tokens:
                if token.ttype is Keyword and token.value.upper() in ['UNION', 'UNION ALL'] :
                    logger.warning(f'数据脱敏异常，错误信息：不支持该查询语句脱敏！请联系管理员')
                    sql_result.error = '不支持该查询语句脱敏！请联系管理员'
                    sql_result.status = 1
                    return sql_result

**Comment by hhyo** [comment]
最新工程已经没有相关代码，请确认更新是否正确，是否存在解决冲突过程中造成代码混乱

**Comment by liujiashun0520** [comment]
> 最新工程已经没有相关代码，请确认更新是否正确，是否存在解决冲突过程中造成代码混乱

好的，我看了最新archery版本，我升级archery 再测试下

**Comment by liujiashun0520** [comment]
现在用了archery 1.8.4,确实可以支持union/union all,但是 union /union all 两张不同的表时（都有一样的打标敏感字段），掩码会失效，同一个表没问题
