### ISSUE TITLE
[ bug ] 1.8.3 在打开配置项页面时，报错：not found

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1496]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

使用超管用户，登录，打开配置项页面报错：
![image](https://user-images.githubusercontent.com/9590209/167112476-6dfaddfa-1fb7-4293-bed9-5367bd861263.png)
![image](https://user-images.githubusercontent.com/9590209/167112600-4942b4a8-391d-4d62-91cc-8ef17b72bf58.png)
![image](https://user-images.githubusercontent.com/9590209/167112698-48a431fa-d3ff-47f6-b2a8-b44091b3a9f4.png)

双击打开后，是这个页面：
![image](https://user-images.githubusercontent.com/9590209/167112785-1e45fdcd-14b4-4b99-9177-62fd2cbe35a9.png)

### 期待结果和实际结果
期待结果：不报错

 
### 错误日志
Nginx 日志
![image](https://user-images.githubusercontent.com/9590209/167112968-5687edd7-f158-4089-98e4-39c3b5e7d4c8.png)

archery日志里，无报错记录

### 版本信息
应用版本/分支：1.8.3

部署方式：Docker

**Comment by nick2wang** [comment]
/user/list是1.8.4版本新增的，先检查下有没有完整更新

**Comment by peng19832** [comment]
> /user/list是1.8.4版本新增的，先检查下有没有完整更新

噢，那我也没更新这个config文件内容呀，怎么屏蔽这个呢，在1.8.3里

**Comment by nick2wang** [comment]
> > /user/list是1.8.4版本新增的，先检查下有没有完整更新
> 
> 噢，那我也没更新这个config文件内容呀，怎么屏蔽这个呢，在1.8.3里

下载1.8.3版本的config.html覆盖回去

**Comment by peng19832** [comment]
ok，谢谢大佬
