### ISSUE TITLE
api swagger页面没有互联网不能打开

### ISSUE THREAD

**Issue by lijie861221** [hhyo/archer#1498]
- 应用版本/分支：Release v1.8.4  
 - 部署方式：Docker

![0af694b4d19e3db9b839b5429324bdb](https://user-images.githubusercontent.com/33362111/167132675-7b1b1e87-908c-4e01-b8e3-de257f971350.jpg)

**Comment by nick2wang** [comment]
drf-spectacular默认是从CDN加载静态文件，有两个办法修改为本地：
1. 修改settings.py
```
    SPECTACULAR_SETTINGS = {
            ....
            # CDNs for swagger and redoc. You can change the version or even host your
            # own depending on your requirements.
            'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest',
            'SWAGGER_UI_FAVICON_HREF': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/favicon-32x32.png',
            'REDOC_DIST': 'https://cdn.jsdelivr.net/npm/redoc@latest',
            ....
    }

```
2. 使用drf-spectacular-sidecar然后python manage.py collectstatic（未来可以考虑为archery默认安装）
https://github.com/tfranzel/drf-spectacular/commit/aeda9697382029cf160031748636c6cbe9991ad2

**Comment by lijie861221** [comment]
> 1. 修改settings.py
> 
> ```
>     SPECTACULAR_SETTINGS = {
>             ....
>             # CDNs for swagger and redoc. You can change the version or even host your
>             # own depending on your requirements.
>             'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest',
>             'SWAGGER_UI_FAVICON_HREF': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/favicon-32x32.png',
>             'REDOC_DIST': 'https://cdn.jsdelivr.net/npm/redoc@latest',
>             ....
>     }
> ```


在settings.py里没找到这个配置项呀，可以自己手动添加上去吗？

**Comment by nick2wang** [comment]
在这个基础上添加
https://github.com/hhyo/Archery/blob/f5ec82c1c27fba6fdabe1d08e8e606c08993bb01/archery/settings.py#L206-L211
