### ISSUE TITLE
mysql8对包含JSON字段的无法通过

### ISSUE THREAD

**Issue by hydgladiator** [hhyo/archer#1503]
### 问题描述
接入mysql8.0的实例，在做SQL检测的时候，始终对包含JSON字段的无法通过

### 版本信息
 - 应用版本/分支：Release v1.7.7
 - 部署方式：Docker、手工部署

 

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/13326206/167373393-083afbbc-a8ba-4b9a-a7c1-052badfec844.png">

**Comment by nick2wang** [comment]
goinception，enable_json_type设置为true来启用json类型
参考：https://hanchuanchuan.github.io/goInception/zh/options.html

**Comment by hydgladiator** [comment]
默认是开启的
[cid:9CB3A19C-AAE4-4D45-A19E-30F2F8950A6A]
但是我这边没看到有切换goinception的配置
[cid:F81D968A-4E6D-4BBE-9147-AE6D9043A2E4]

在 2022年5月9日，下午5:58，Nick Wang ***@***.******@***.***>> 写道：

enable_json_type

**Comment by hhyo** [comment]
这个是语法错误，和审核策略无关

**Comment by hydgladiator** [comment]
好的
