### ISSUE TITLE
提示goInception和备份库测试连接成功，提交工单时，总是报密码错误

### ISSUE THREAD

**Issue by xuanzhi201111** [hhyo/archer#1506]
1、系统设置里---》goInception配置---点测试，会提示以下信息
goInception和备份库测试连接成功，请点击页面下方的保存按钮生效

然后点最下方保存

2、然后提交插入工单后总是报：
<html>
<body>

inception_magic_start | error | con:64 Error 1045: Access denied for user 'root'@'172.18.0.2' (using password: YES).
-- | -- | --

</body>
</html>

3、手动测试登录备份数据库是没有问题的

**Comment by xuanzhi201111** [comment]
备份用户换了账号后，例如：backup_user，执行工单时，也还是报root密码错误，跟上面错误一样的，这是为什么呢，1.8.3 1.8.4都是这样，我哪里配置有问题吗

**Comment by xuanzhi201111** [comment]
修改 inception/config.toml的账号密码正常了，但是为什么页面上配置的没什么作用呢，没生效，要手动修改配置文件

**Comment by hhyo** [comment]
两个服务独立，不会同步变更，文档和页面都有相关说明
