### ISSUE TITLE
[ bug ] 手工执行工单后，查看回滚语句，弹窗报错

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1507]
### 重现步骤
1. 提交ddl
2. 手工执行
3. 点击工单查看回滚语句

### 期待结果和实际结果
期待结果：
屏蔽掉，或者正常打印回滚语句

实际结果:
![image](https://user-images.githubusercontent.com/9590209/167781889-f0775c89-0c5a-44fa-a35a-b202fbfcf694.png)
 
### 错误日志
archery.log中，无错误记录

### 版本信息
应用版本/分支：1.8.3

部署方式：Docker

**Comment by thcoffee** [comment]
mysql还是oracle

**Comment by peng19832** [comment]
> mysql还是oracle

mysql

**Comment by hhyo** [comment]
手工确认只是标记工单状态，什么都不会做。包括执行

**Comment by peng19832** [comment]
> 手工确认只是标记工单状态，什么都不会做。包括执行

@hhyo 
是的，但是最好把这个错误屏蔽掉，是不是友好
