### ISSUE TITLE
水印功能如何调透明一些？

### ISSUE THREAD

**Issue by xuanzhi201111** [hhyo/archer#1508]
1.8.4开启水印功能后，水印有点让人眼花，但是水印功能是挺好的，如果变淡一些 ，也就是浅颜色一些，不影响开发人员观感呢，在哪个文件可以调呢

**Comment by LeoQuote** [comment]
应该是调 css, 得看水印的 pr 怎么实现的, 改这里就行 https://github.com/hhyo/Archery/pull/1466/files#diff-48efb209c470629081c568c61f9fe1575e68b2c6367731fb00a2b585d792b572R24

**Comment by xuanzhi201111** [comment]
改这里就行 https://github.com/hhyo/Archery/pull/1466/files#diff-48efb209c470629081c568c61f9fe1575e68b2c6367731fb00a2b585d792b572R24    已经解决，谢谢
