### ISSUE TITLE
[ bug ] v1.8.3，开启脱敏检查后，没有配置脱敏的实例，也会阻止查询，并报错：list index out of range

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1511]
### 重现步骤
1. 配置项开启脱敏检验；
2. 在没配置脱敏的实例中查询；

### 期待结果和实际结果
期待结果：
没有配置脱敏的实例，正常查询

实际结果:
![image](https://user-images.githubusercontent.com/9590209/168194841-fa76abd9-c8ec-419b-a07e-ebed57728096.png)

 
![image](https://user-images.githubusercontent.com/9590209/168194992-fc52d96b-1566-421a-b23e-fc00a339a55f.png)

### 版本信息
应用版本/分支：1.8.3
部署方式：Docker

**Comment by peng19832** [comment]
新版本1.8.4中，没有这个问题

**Comment by hhyo** [comment]
应该是未配置inception，只有解析语法才知道有没有命中脱敏规则

**Comment by peng19832** [comment]
> 应该是未配置inception，只有解析语法才知道有没有命中脱敏规则

@hhyo 
大佬，什么意思呢？inception是配置了的，这个报错，是一个不相干的实例，点查询时候报出来的

**Comment by hhyo** [comment]
> > 应该是未配置inception，只有解析语法才知道有没有命中脱敏规则
> 
> @hhyo 大佬，什么意思呢？inception是配置了的，这个报错，是一个不相干的实例，点查询时候报出来的

开启脱敏后，所有的MySQL查询都会调用inception做语法解析（因为只有解析完拿到语法树，才能去和现有的脱敏规则去匹配），注意是Inception不是goinception，上面的错误就是调用Inception异常

**Comment by peng19832** [comment]
> > > 应该是未配置inception，只有解析语法才知道有没有命中脱敏规则
> > 
> > 
> > @hhyo 大佬，什么意思呢？inception是配置了的，这个报错，是一个不相干的实例，点查询时候报出来的
> 
> 开启脱敏后，所有的MySQL查询都会调用inception做语法解析（因为只有解析完拿到语法树，才能去和现有的脱敏规则去匹配），注意是Inception不是goinception，上面的错误就是调用Inception异常

那我找时间，升级到新版本吧，不用inception了
