### ISSUE TITLE
[ 问题咨询 ]菜单栏细节问题

### ISSUE THREAD

**Issue by MrAndyMing** [hhyo/archer#1512]
版本：v1.8.4
菜单栏这块，当点击了子菜单，图片勾选的箭头，可否也向下指向，用户体验更好点，演示版本也存在这个问题。
![image](https://user-images.githubusercontent.com/49541483/168201470-b66c3e7f-6809-40c5-bab3-1de10318e167.png)

**Comment by nick2wang** [comment]
使用chrome没发现该问题
![image](https://user-images.githubusercontent.com/33473924/168217052-e0b81ee0-48fe-48d8-88ea-693423db19ed.png)

**Comment by MrAndyMing** [comment]
mac系统，谷歌版本：101.0.4951.64
