### ISSUE TITLE
[ bug ]select * from a union select * from b 导致脱敏失效

### ISSUE THREAD

**Issue by liujiashun0520** [hhyo/archer#1516]
archery为1.8.4，gocention 为v1.2.5-34
select * from unsen
union
select * from unsen2 limit 100;

其中unsen和unsen2数据结构一样，敏感字段一样，但是union会使脱敏查询失效；如果只是union同一张表，可以正常脱敏。

**Comment by hhyo** [comment]
#1483

**Comment by liujiashun0520** [comment]
已验证，太棒了
