### ISSUE TITLE
[ bug ]1.8.4初始化失败

### ISSUE THREAD

**Issue by LazySongQ** [hhyo/archer#1527]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 错误日志
![Uploading image.png…]()

### 版本信息
应用版本/分支：
1.8.4
部署方式：
Docker

**Comment by nick2wang** [comment]
图片挂了

**Comment by LazySongQ** [comment]
AttributeError: 'Settings' object has no attribute 'REST_FRAMEWORK'

**Comment by LazySongQ** [comment]
![image](https://user-images.githubusercontent.com/83281049/169283432-2eac5228-735e-41db-a7bd-513cefc5a161.png)

**Comment by LazySongQ** [comment]
![image](https://user-images.githubusercontent.com/83281049/169283507-f25a78ac-752e-40f1-924c-671971dbbe58.png)

**Comment by LazySongQ** [comment]
docker里面手动连接mysql、Redis都是正常
![image](https://user-images.githubusercontent.com/83281049/169283705-1f7c0c31-cffb-4fdf-bebc-4979a33eeb2e.png)

**Comment by nick2wang** [comment]
参考 #1502
