### ISSUE TITLE
[ 问题咨询 ]mongodb如何查询json格式字段

### ISSUE THREAD

**Issue by mrliang97** [hhyo/archer#1536]
### 问题描述
Mondodb 查询结果中，某个字段是 json 格式，就无法查看该字段的内容吗？
![image](https://user-images.githubusercontent.com/100185916/169939425-095aa4f9-8659-440e-a109-483810024ef8.png)

在navicat中，是可以点击后展开的
![image](https://user-images.githubusercontent.com/100185916/169939492-e27e5be0-c9e0-4c00-b6ae-cc280592fe18.png)
![image](https://user-images.githubusercontent.com/100185916/169939516-311a7f8b-d555-4369-97d6-3ddd0f59eb67.png)

**Comment by nick2wang** [comment]
点行首的加号就可以切换为json格式
![image](https://user-images.githubusercontent.com/33473924/170161233-0c622206-9cf8-4491-a77a-9fa0f120afd2.png)

**Comment by mrliang97** [comment]
> 点行首的加号就可以切换为json格式 ![image](https://user-images.githubusercontent.com/33473924/170161233-0c622206-9cf8-4491-a77a-9fa0f120afd2.png)

谢谢，我都没注意到。。。
