### ISSUE TITLE
[ 问题咨询 ]admin 账号密码忘记了 不知道怎么找回

### ISSUE THREAD

**Issue by GankGintama** [hhyo/archer#1538]
### 问题描述
admin密码忘记了 现在修改不了普通账号密码

**Comment by nick2wang** [comment]
重置密码
`python3 manage.py changepassword your_username`

**Comment by GankGintama** [comment]
![image](https://user-images.githubusercontent.com/33503325/170163649-4c9a5212-3e27-4ec7-bc11-0dd72bd98641.png)
你好 我想问 为什么找不到django这个模块呢

**Comment by nick2wang** [comment]
> ![image](https://user-images.githubusercontent.com/33503325/170163649-4c9a5212-3e27-4ec7-bc11-0dd72bd98641.png) 你好 我想问 为什么找不到django这个模块呢

手工部署还是docker？

**Comment by GankGintama** [comment]
docker的

**Comment by nick2wang** [comment]
```
docker exec -ti archery /bin/bash
cd /opt/archery
source /opt/venv4archery/bin/activate
python3 manage.py changepassword your_username
```

**Comment by GankGintama** [comment]
修改成功 感谢您的解答 谢谢大佬
