### ISSUE TITLE
sql提交报错：data too long for column workflow_name

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1544]
### 问题描述
提交sql时，报错字段workflow_name超长，是工单标题太长的原因哇？
![image](https://user-images.githubusercontent.com/9590209/170215725-6d652154-de3b-41a3-a4fc-007dc51c49c6.png)

### 版本信息
 - 应用版本/分支：1.8.3  
 - 部署方式：Docker

**Comment by peng19832** [comment]
我看代码里workflow_name=workflow_title

**Comment by peng19832** [comment]
> 我看代码里workflow_name=workflow_title

需要加长数据库里的sql_workflow表的workflow_name字段的长度

**Comment by LeoQuote** [comment]
你的标题是多长? 我看一般情况下应该是够用的

**Comment by peng19832** [comment]
> 你的标题是多长? 我看一般情况下应该是够用的

研发提的工单，应该挺长的，这种错误不记录的。
我复现出来了
解决方法就是，把上面提到的字段加长
