### ISSUE TITLE
[ bug ] 新建实例建表的时候报错, primary key 太长

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/archer#1545]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

https://github.com/hhyo/Archery/blob/master/sql/models.py#L633 config 表的 item 太长了, 导致建表的时候主键太长无法正常运行

建议按需求缩一缩, 或者再设一个 auto increase 的 primary key, 这个varchar primary key 好像有点没必要

### 重现步骤
1. python manage.py migrate

### 期待结果和实际结果
期待结果：

实际结果:

```
Specified key was too long; max key length is 767 bytes
```

### 版本信息
应用版本/分支: master

部署方式：Docker

**Comment by hhyo** [comment]
可以新增个自增主键，前期modal的设计有挺多问题，非自增主键，以及把主键当做有意义的信息

**Comment by LeoQuote** [comment]
@hhyo 现在改有点困难了, 主键要设置默认值, 改表语句不好写, 要做的话要弄个新 model 做 config_v2

**Comment by hhyo** [comment]
```
alter table sql_config add unique index uniq_item(item),drop primary key,
    add id bigint unsigned not null auto_increment primary key first ;
```
