### ISSUE TITLE
[ 功能建议 ]管理后台2FA验证

### ISSUE THREAD

**Issue by jinhaozcp** [hhyo/archer#1546]
目前遇到的问题/使用障碍
目前默认入口已经有2fa验证，可以针对普通员工权限进行管理，但是拥有后台管理权限的超管用户界面登录仍为只需要账号密码方式，由于超管用户权限更高，后台管理危险性大。

希望如何解决/实现它
配套通过后台管理登录界面2FA验证。

**Comment by nick2wang** [comment]
最新代码已经屏蔽django默认的admin登录入口 #1541

**Comment by jinhaozcp** [comment]
> 最新代码已经屏蔽django默认的admin登录入口 #1541

这样就完美了
