### ISSUE TITLE
[ bug ]SQL上线功能 内扫描/影响行数字段数据错误

### ISSUE THREAD

**Issue by dhstime** [hhyo/archer#1547]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

1.提交多条更新SQL
2.扫描/影响行数字段所有sql的影响行数都为提交首行影响的数据行数

### 期待结果和实际结果
期待结果：
每条sql影响行数为当前影响行数
实际结果:
每条sql影响行数不为当前影响行数
### 截图
![image](https://user-images.githubusercontent.com/50047146/170437822-7b352a81-c130-485b-9049-6d8fda32ea21.png)
![image](https://user-images.githubusercontent.com/50047146/170438159-ac403a9a-d18d-4954-a135-a40fef3c7b35.png)

 
### 版本信息
应用版本/分支：
v1.8.5
部署方式：Docker、手工部署

**Comment by nick2wang** [comment]
重复issue #643

**Comment by hhyo** [comment]
goinception预估影响行数，相同指纹的语句，默认是取第一条的结果
