### ISSUE TITLE
[ bug ] 工单已经执行完成但是显示状态不对

### ISSUE THREAD

**Issue by skymoou** [hhyo/archer#1548]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1. 安装v1.8.5
2. 提交sql
3. 审核sql并执行

### 期待结果和实际结果
期待结果：工单完成

实际结果:   sql 已经执行完成，但是操作信息显示 工单执行排队中

### 截图
![image](https://user-images.githubusercontent.com/16809896/170455535-cf121554-286a-4634-901b-072e06a0b293.png)
![image](https://user-images.githubusercontent.com/16809896/170471635-6b58c626-4452-4c4e-976e-2906eb765639.png)

 
### 错误日志
![image](https://user-images.githubusercontent.com/16809896/170455746-a4cd7284-b882-47fb-aa49-1e406b822a22.png)

### 版本信息
应用版本/分支：Release  v1.8.5

部署方式：手工部署

### 进程信息

![image](https://user-images.githubusercontent.com/16809896/170459209-9ce3af8e-b408-44d5-a170-d6b5faef185b.png)

**Comment by skymoou** [comment]
sync: false

**Comment by jeromeji** [comment]
我也是这个问题。。≥
