### ISSUE TITLE
查询授权时间能修改吗

### ISSUE THREAD

**Issue by wqbbs911** [hhyo/archer#1557]
### 问题描述
在使用中觉得（一月、一年）授权时间太长，想把它屏蔽掉

![图片](https://user-images.githubusercontent.com/30170870/170947694-70762408-68f6-4b33-b76c-de82bea4c9f0.png)

### 版本信息
 - 应用版本/分支：Release v1.8.3
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
现在是只能改源码, 欢迎贡献

**Comment by wqbbs911** [comment]
能告知下怎么改吗？现在迫切需要这个改动，谢谢

**Comment by LeoQuote** [comment]
@wqbbs911 你得有点探索精神啊, 这 UI 上的东西都在, 你直接搜, 一天 一月, 一年, 然后照葫芦画瓢就行了

**Comment by wqbbs911** [comment]
好的，已更改，谢谢！
