### ISSUE TITLE
请问建表的时候提示不能创建TEXT类型的，这块有没有方法跳过

### ISSUE THREAD

**Issue by OpenSourceApp-coder** [hhyo/archer#1559]
### 问题描述
请问建表的时候提示不能创建TEXT类型的，这块有没有方法跳过

### 版本信息
 - 应用版本/分支：Release v1.8.4  
 - 部署方式：手工部署

 
![image](https://user-images.githubusercontent.com/67618321/171366328-0180a9f9-84a9-491b-84e7-0c81e300a041.png)

**Comment by LeoQuote** [comment]
这是 goinception 的配置，参考goinception 和inception 的文档吧
