### ISSUE TITLE
[ bug ]ClickHouse SQL上线INSERT语法检查错误

### ISSUE THREAD

**Issue by allen12921** [hhyo/archer#1560]
执行SQL上线进行SQL检测时报错，此语句可以直接在ClickHouse 22.1.3.7上执行成功：

INSERT INTO entries (* EXCEPT (id, recorded_at)) SELECT * REPLACE 'c2' AS customer_5 EXCEPT (id, recorded_at)
FROM entries
WHERE id IN (
    SELECT argMax(id, recorded_at) AS id
    FROM entries
    WHERE customer_id IN ['1','2','3','4','5']
    GROUP BY entry_id
    HAVING argMax(deleted_at, recorded_at) IS NULL
)
实际结果:

### 截图
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/11305195/171369107-6fd25f6b-b845-44fb-ba63-f5bdfdac1849.png">

### 错误日志
无错误日志
-->
### 版本信息
应用版本/分支： v 1.8.3

部署方式：Docker

**Comment by nick2wang** [comment]
明天看一下，应该是正则匹配漏了

**Comment by nick2wang** [comment]
没能复现你的问题
![image](https://user-images.githubusercontent.com/33473924/171539340-0fe0b99e-b2ac-49f9-b788-0eb625696653.png)

**Comment by allen12921** [comment]
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/11305195/171585197-0141ab5f-c916-4f81-9990-0ade9d38ce6b.png">
是需要最新的版本吗？

**Comment by nick2wang** [comment]
先不用美化试下，后面再优化下正则

**Comment by allen12921** [comment]
多谢。
