### ISSUE TITLE
[ 文档补充 ] 开启https配置

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1561]
### 文档补充
1、准备nginx证书；

2、上传证书，到自定义目录下，我是在docker-compse目录下，创建了nginx/cert目录；

3、修改nginx配置，增加443端口监听，并将http重定向至https端口：

>     server{
>         listen 9123; #监听的端口
>         server_name archery;
>         client_max_body_size 20M;
> 
>         proxy_read_timeout 600s;
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-Proto $scheme;
> 
>         return 301 https://$host$request_uri;
>     }
> 
> # Settings for a TLS enabled server.
>     server{
>         listen 443 ssl; #监听的端口
>         client_max_body_size 20M;
>         proxy_read_timeout 600s;
> 
>         ssl_protocols TLSv1.2 TLSv1.3;
>         ssl_certificate /etc/nginx/cert/192.168.1.3_chain.crt; # 配置证书文件地址
>         ssl_certificate_key /etc/nginx/cert/192.168.1.3_key.key; # 配置密钥文件地址
> 
>         location / {
>           proxy_pass http://127.0.0.1:8888;
>           proxy_set_header Host $host;
>           proxy_set_header X-Forwarded-Host  $host:9123;
>           proxy_set_header X-Real-IP $remote_addr;
>           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>           proxy_set_header X-Forwarded-Proto $scheme;
>         }
> 
>         location /static {
>           alias /opt/archery/static;
>         }
> 
>         error_page 404 /404.html;
>             location = /40x.html {
>         }
> 
>         error_page 500 502 503 504 /50x.html;
>             location = /50x.html {
>         }
>     }

3、django配置settings.py中增加安全配置项：
我自己是在内网使用，没有域名，使用了私网ip。
> SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
> SECURE_SSL_REDIRECT = True                           # 将所有非SSL请求永久重定向到SSL
> SESSION_COOKIE_SECURE = True                      # 仅通过https传输cookie
> CSRF_COOKIE_SECURE = True                            # 仅通过https传输cookie
> SECURE_HSTS_INCLUDE_SUBDOMAINS = True # 严格要求使用https协议传输
> SECURE_HSTS_PRELOAD = True
> SECURE_HSTS_SECONDS = 60
> SECURE_CONTENT_TYPE_NOSNIFF = True        # 防止浏览器猜测资产的内容类型
> CSRF_TRUSTED_ORIGINS = ['192.168.1.3']
> CORS_ORIGIN_WHITELIST = (
>     '192.168.1.3',
> )

4、使用新配置，重新运行archery容器：
注意加粗项，把准备好的nginx配置文件和证书，挂进容器。
我这里是在宿主机，上docker-compse目录下，创建了nginx目录，把证书和nginx配置文件，放在这里，方便变更，
所以，挂载 ./nginx/nginx.conf 文件和 ./nginx/cert 证书目录到容器中。
> version: '3'
> 
> services:
>   archery:
>     image: hhyo/archery:v1.8.5
>     container_name: archery
>     restart: always
>     ports:
>       - "9123:9123"
>       - **"443:443"**
>     volumes:
>       - "./archery/settings.py:/opt/archery/archery/settings.py"
>       - "./archery/soar.yaml:/etc/soar.yaml"
>       - "./archery/docs.md:/opt/archery/docs/docs.md"
>       - "./archery/downloads:/opt/archery/downloads"
>       - "./archery/sql/migrations:/opt/archery/sql/migrations"
>       - "./archery/logs:/opt/archery/logs"
>       - "./archery/keys:/opt/archery/keys"
>       **- "./nginx/nginx.conf:/etc/nginx/nginx.conf"
>       - "./nginx/cert:/etc/nginx/cert"**
>     entrypoint: "dockerize -wait tcp://mysql:3306 -wait tcp://redis:6379 -timeout 60s /opt/archery/src/docker/startup.sh"
>     environment:
>       NGINX_PORT: 9123
>     **networks:
>       - "archery-184_default"
> 
> networks:
>   archery-184_default:
>     external: true**

5、清除浏览器cookie，登录验证

**Comment by hhyo** [comment]
可以直接修改这个页面 https://github.com/hhyo/Archery/wiki/docker

**Comment by peng19832** [comment]
> 可以直接修改这个页面 https://github.com/hhyo/Archery/wiki/docker

已补充文档

**Comment by mod196** [comment]
现状：多级代理外层代理卸载 TLS，且同时需要配置 OIDC，导致 Redirect URL 协议是 http。
Archery 本身的 Nginx 需要修改 header X-Forwarded-Proto。
```nginx
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
    default $http_x_forwarded_proto;
    ''      https;
}
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
# proxy_set_header X-Forwarded-For https;
proxy_set_header X-Forwarded-Port 443;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
外层的 TLS_Nginx 必须配置
```nginx
proxy_set_header X-Forwarded-Proto $scheme;
```
