### ISSUE TITLE
定时sql执行，工单完成后定时任务并没有删除

### ISSUE THREAD

**Issue by sona-yuan** [hhyo/archer#1569]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：
![image](https://user-images.githubusercontent.com/78458951/172286934-fc79e6ff-ac86-4d7d-955e-32179e1a3f64.png)

实际结果:
![image](https://user-images.githubusercontent.com/78458951/172286980-ab1ae174-837c-4f3a-8cca-4aa36ddffc71.png)

### 版本信息
应用版本/分支：

部署方式：Docker、手工部署

**Comment by hhyo** [comment]
主动触发执行时会删除已存在的定时执行任务，如果本身定时执行成功的，不会删除任务记录
