### ISSUE TITLE
[ 问题咨询 ]open api页面打开空白 ，尝试过#1554了 没解决！

### ISSUE THREAD

**Issue by dxl3811051** [hhyo/archer#1570]
### 问题描述
我刚部署好最新版本的archery，然后想打开api页面查看下接口，但是打开的是空白页面，F12后也没发现什么问题 没报错！
想问下大佬 是还需要在哪里配置么？我看了几个issues 但是都没有解决！

### 版本信息
 - 应用版本/分支：Release v1.8.5
 - 部署方式：Docker

![1](https://user-images.githubusercontent.com/34296773/172545936-bd602235-9f8e-411c-86c2-c5cb369eb024.png)

**Comment by LeoQuote** [comment]
Duplicate of #1554

**Comment by dxl3811051** [comment]
我之前就尝试过了，还是一样啊 打开空白！ 还有别的解决方法么  ？

**Comment by dxl3811051** [comment]
> Duplicate of #1554

这个我之前就尝试过了，还是一样 打开空白！ 我想问下还有别的解决方法么 ？

**Comment by nick2wang** [comment]
控制台没有报404么？

**Comment by dxl3811051** [comment]
> 控制台没有报404么？

没有啊  就空白  让我抓虾了

**Comment by nick2wang** [comment]
看下有没有这些静态资源加载记录
![image](https://user-images.githubusercontent.com/33473924/172574254-f65733f0-91b8-44d5-9670-8c247a92d3a9.png)

**Comment by dxl3811051** [comment]
> 看下有没有这些静态资源加载记录 ![image](https://user-images.githubusercontent.com/33473924/172574254-f65733f0-91b8-44d5-9670-8c247a92d3a9.png)

我要吐血了  我看了有相应资源加载了的啊  ！  这玩意的日志在哪里 ？ 我现在连哪里有问题都不知道  好歹给我个提示啊 ，哎！
