### ISSUE TITLE
[ bug ]执行oracle 语句报错-TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by 91dream** [hhyo/archer#1573]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：

实际结果:

### 错误日志
[2022-06-09 18:06:40,730][MainThread:140015835297600][task_id:default][oracle.py:487][WARNING]- Oracle 语句执行报错，语句：explain plan for delete
from xxx.test01
where bincode='625132'，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/oracle.py", line 482, in explain_check
    if rows[0] is None:
TypeError: 'NoneType' object is not subscriptable

[2022-06-09 18:10:15,104][MainThread:140015835297600][task_id:default][oracle.py:487][WARNING]- Oracle 语句执行报错，语句：explain plan for delete
from xxx.test01
where bincode='625132'，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/oracle.py", line 482, in explain_check
    if rows[0] is None:
TypeError: 'NoneType' object is not subscriptable

### 版本信息
应用版本/分支：Release v1.8.4

部署方式：Docker

**Comment by 91dream** [comment]
参考：[ bug ]oracle执行语句时报错日志显示TypeError: 'NoneType' object is not subscriptable #766问题，不是权限问题，oracle版本为11g，plsql执行sql语句没有问题。

**Comment by nick2wang** [comment]
用上线实例配置的oracle账号执行这句sql看有没有报错
`select CARDINALITY from SYS.PLAN_TABLE$ where id = 0`

**Comment by 91dream** [comment]
没有报错，执行sql查询没有数据而已。

**Comment by 91dream** [comment]
修改代码482行后，再执行sql检查就不报错了，不确定对其他操作有没有影响？
/opt/archery/sql/engines/oracle.py
    482             #if rows[0] is None:
    483             if rows == None:
    484                 result['rows'] = 0
    485             else:
    486                 result['rows'] = rows[0]
