### ISSUE TITLE
[Bug] v1.8.5, mysql, 创建存过时，检测失败

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1626]
### 问题是否已经被报告?

- [x] 我已经搜索了当前存在的问题

### 重现步骤

创建存过：
```
delimiter  $$
create procedure updateModule(IN mn varchar(20))
begin
......
end $$
delimiter  ;
```

### 预期外的结果

![image](https://user-images.githubusercontent.com/9590209/173796365-848b50a8-1c5f-4f49-86ab-8023b4f43c73.png)

### 日志文本

```shell
line 1 column 37 near "delimiter $$
create procedure updateModule(IN mn varchar(20))
begin
```

### 版本

1.8.5

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库、浏览器、goInception等

MySQL: 8.0.25

**Comment by nick2wang** [comment]
goinception不支持存储过程，只能走线下执行了
