### ISSUE TITLE
展示精度问题

### ISSUE THREAD

**Issue by reason-tech** [hhyo/archer#1640]
### 问题是否已经被报告?

- [ ] 我已经搜索了当前存在的问题

### 重现步骤

查询数据 decimal 类型如果精度小数点后如果超出 7 位就不展示了

### 预期外的结果

预期展示全部精度

### 日志文本

```shell
例如：SELECT 74269679.1621059 * 10001.01; 

展示结果：742771803997.0127
```

### 版本

1.8.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库、浏览器、goInception等

应该是类型精度问题

**Comment by nick2wang** [comment]
该问题已在v1.8.2版本中修复，可以更新代码试试 https://github.com/hhyo/Archery/commit/6e18e9336603e92f464e6f94a78e01bde1adc168
