### ISSUE TITLE
amber_admin超级用户的数据查询历史没有显示用户名

### ISSUE THREAD

**Issue by carlors** [hhyo/archer#1644]
### 问题是否已经被报告?

- [ ] 我已经搜索了当前存在的问题

### 重现步骤

1.用amber_admin超级用户登陆，点击SQL查询-在线查询，选择某个数据库进行查询；
2.查看“查询历史”，可以看到有本次SQL查询记录，但是用户记录显示为空白。

### 预期外的结果

![image](https://user-images.githubusercontent.com/11304925/176139429-9d22f5c0-d915-442b-80ce-43ffe511a3a6.png)

### 版本

1.8.1

### 部署方式

K8S

### 是否还有其他可以辅助定位问题的信息？比如数据库、浏览器、goInception等

Browsers: Chrome

**Comment by nick2wang** [comment]
这里显示的是用户的中文名，检查下是否给超级管理员填写了中文名
![image](https://user-images.githubusercontent.com/33473924/176147161-02428ea9-8f9b-4107-9ad3-1899bb2e5310.png)

**Comment by carlors** [comment]
是的，的确是没有设置中文名的原因，感谢。
