### ISSUE TITLE
pgsql查询结果集中部分字段无法正常解析

### ISSUE THREAD

**Issue by maxianwei** [hhyo/archer#1645]
### 问题是否已经被报告?

- [ ] 我已经搜索了当前存在的问题

### 重现步骤

attr字段的内容无法解析
![image](https://user-images.githubusercontent.com/34542869/176147460-3a23ba7a-0a2b-41d9-bc39-c9cd5ac98868.png)

正常应该是下面这种格式：
![image](https://user-images.githubusercontent.com/34542869/176148010-ba184564-5c63-4c31-baeb-0c9db07a0f38.png)

### 预期外的结果

预期可以如上第二个图那样正常显示。

### 版本

1.8.4

### 部署方式

Docker

**Comment by nick2wang** [comment]
attrs字段的数据类型是什么？
