### ISSUE TITLE
v1.8.5 报错

### ISSUE THREAD

**Issue by 37705109** [hhyo/archer#1654]
### 问题是否已经被报告?

- [ ] 我已经搜索了当前存在的问题

### 重现步骤

v1.8.4 升级 v1.8.5报错 
![image](https://user-images.githubusercontent.com/25220287/177264843-80e4f4e4-112c-4c90-9ac8-2936429e85cb.png)

### 预期外的结果

报错，表不存在 ERROR 1146 (42S02) at line 2: Table 'archery.django_content_type' doesn't exist

### 版本

1.8.5

### 部署方式

Docker

**Comment by hhyo** [comment]
执行什么操作出现该错误？这个是最基础的表没有创建，看起来和升级无关
