### ISSUE TITLE
Windows用户开发使用PyCharm开发工具启动项目的异常

### ISSUE THREAD

**Issue by 0vally1** [hhyo/archer#1681]
### 重现步骤

页面样式显示异常
![image](https://user-images.githubusercontent.com/30279431/178927381-8785dfd1-5681-4f98-b5eb-f21bfbe0855b.png)
没有部署docker，静态资源访问错误，

### 预期外的结果

静态资源访问不到

### 版本

最新master分支代码

### 部署方式

手工部署

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

没有使用Nginx和Docker，Windows用户开发启动

**Comment by 0vally1** [comment]
已解决，DEBUG设置True就好了

**Comment by fengjian1993** [comment]
> 已解决，DEBUG设置True就好了

你好，设置DEBUG=true的原理是什么，这个好像是静态资源找不到 为啥设置一下DEBUG就找到了？
