### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 205: illegal multibyte sequence

### ISSUE THREAD

**Issue by 0vally1** [hhyo/archer#1683]
### 重现步骤

点击菜单 相关文档，报

[UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 205: illegal multibyte sequence]

### 预期外的结果

Archery\sql\views.py

### 版本

1.8.5

### 部署方式

手工部署

**Comment by 0vally1** [comment]
Archery\sql\views.py 
这份文件的451行：
with open(file, 'r') as f:
这行代码  添加个UTF-8的参数  
添加后：
with open(file, 'r', encoding='UTF-8') as f:

**Comment by LeoQuote** [comment]
请首先用master分支的代码重试，问题依然存在可以直接提pr

**Comment by 0vally1** [comment]
> 

tag标签选择的V1.8.5，windows上，我遇见个问题，windows使用goland启动goinception，有几个包拉不下来，inc的参数backup_host。这个是做什么的

**Comment by LeoQuote** [comment]
goinception 不属于本项目，可以去goinception 的issue 区提问
