### ISSUE TITLE
archery版本1.8.5 redis集群模式下执实例连接测试报：module 'redis' has no attribute 'cluster'

### ISSUE THREAD

**Issue by fancy-lee** [hhyo/archer#1699]
### 重现步骤

archery版本1.8.5 redis集群模式下执实例连接测试报：module 'redis' has no attribute 'cluster'  
我看当时提交版本是这样的
![image](https://user-images.githubusercontent.com/23489502/180344940-3524a88a-fc88-4778-b208-0579336f160b.png)
但现在的版本代码是这样的：
![image](https://user-images.githubusercontent.com/23489502/180345298-6ed8c74e-c1f3-4b2b-80e2-7c37ea4c960c.png)

我从pycharm上看了一下redis下确实没有显示有cluster，不知是redis包版本的问题还是修改代码bug?

### 预期外的结果

module 'redis' has no attribute 'cluster'

### 版本

1.8.5

### 部署方式

手工部署

**Comment by nick2wang** [comment]
这个应该是同路径下有和module重名的文件[redis.py](https://github.com/hhyo/Archery/blob/master/sql/engines/redis.py)导致import冲突，可以改下文件名

**Comment by fancy-lee** [comment]
清理所有的包重新安装就不报错了

**Comment by hhyo** [comment]
redis-py的版本太低了，可以在依赖内指定一个版本
