### ISSUE TITLE
archery没有实时获取到新创建的数据库和表

### ISSUE THREAD

**Issue by gitzhuyongfu** [hhyo/archer#1701]
### 重现步骤

1.新建的数据库和表,archery没有实时获取到
2.创建的表在sql查询，下来表结构选项没有
3.退出重新登录也是存在

### 预期外的结果

![image](https://user-images.githubusercontent.com/39439367/180392572-ec5c83be-52b6-4850-8ce5-16b7a91d304e.png)
![image](https://user-images.githubusercontent.com/39439367/180392636-347a13ed-29c0-4908-bec3-7730c5be192e.png)

### 版本

1.8.5

### 部署方式

Docker

**Comment by hhyo** [comment]
#1379
