### ISSUE TITLE
两套Archey  使用相同数据源，处理同一个加了非强制ssl的实例，一个能正常访问一个报错

### ISSUE THREAD

**Issue by OpenSourceApp-coder** [hhyo/archer#1705]
### 重现步骤

archery 版本1.8.1    部署了两套，我自己做的高可用，使用同一个数据库，上层用nginx 做的负载，。今天有个数据库开启了非强制性的ssl，  这两套archery一套可以正常的查询使用；另一套就会报错：3159, 'Connections using insecure transport are prohibited while --require_secure_transport=ON.  这里是有什么参数设置的区别吗？我对比了一下，需要修改的地方也不多啊。
我理解两套应该是一样的，看了社区评论说不支持，但是我这边为啥有一套archery是可以正常访问开通ssl的数据库的，两套尝试访问的是同一个开启ssl的实例，使用程序连接时，只要去掉JDBC URL中的useSSL=true 这个属性就能正常请求，我看了代码报错位置，没有配置，应该可以正常请求，但是有一套就是报错，
 

### 预期外的结果

按照我的理解，两套一样的程序，只能同时支持或同时不支持，是不是我哪个参数配置有遗漏

### 日志文本

```shell
报错的那套Archery报错如下，请指点：
[2022-07-22 16:03:45,627][Thread-66485:139993167156992][task_id:default][mysql.py:164][WARNING]- MySQL语句执行报错，语句：show databases，错误信息Traceback (most recent call last):
  File "/app/Archery-1.8.1/sql/engines/mysql.py", line 146, in query
    conn = self.get_connection(db_name=db_name)
  File "/app/Archery-1.8.1/sql/engines/mysql.py", line 46, in get_connection
    connect_timeout=10)
  File "/app/venv4archery/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/app/venv4archery/lib64/python3.6/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (3159, 'Connections using insecure transport are prohibited while --require_secure_transport=ON.')
```

### 版本

1.8.1

### 部署方式

手工部署

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL: 5.7.33
Browsers: Chrome

**Comment by hhyo** [comment]
可以把两套都重启再看下，获取数据库列表这种是存在缓存的

**Comment by OpenSourceApp-coder** [comment]
> 可以把两套都重启再看下，获取数据库列表这种是存在缓存的

重启了，结果还是一样，一套好使一套不好使，重启了archery和goinception，批处理任务qcluster没有重启，这个我理解应该也没有影响

**Comment by OpenSourceApp-coder** [comment]
> > 可以把两套都重启再看下，获取数据库列表这种是存在缓存的
> 
> 重启了，结果还是一样，一套好使一套不好使，重启了archery和goinception，批处理任务qcluster没有重启，这个我理解应该也没有影响

而且我两套用了相同的redis，缓存的话不是应该也一样吗？

**Comment by hhyo** [comment]
理论上是，目前不支持ssl连接，这一点可以确认

**Comment by OpenSourceApp-coder** [comment]
> 理论上是，目前不支持ssl连接，这一点可以确认

理论上不是缓存，我执行了查询等语句，也是可以顺利执行的。所以说，可用的那一套获取的连接是真实可用的，我重启过，缓存的话理论上也不是

注：我们的ssl并不是开启的强制使用，实际上去掉只要去掉JDBC URL中的useSSL=true/useSSL=false 这个属性就能正常请求(即没有useSSl这项设置即可);我看了咱们获取连接的地方并没有设置这个项，我下午准备再做一些验证测试。
 self.conn = MySQLdb.connect(host=self.host, port=self.port, user=self.user, passwd=self.password,
                                        db=db_name, charset=self.instance.charset or 'utf8mb4',
                                        conv=conversions,
                                        connect_timeout=10)

**Comment by OpenSourceApp-coder** [comment]
已解决，没找到两边区别，但是在报错的服务上在连接上设置ssl=true即可;
另外问题，@[hhyo](https://github.com/hhyo)  咱们这个支持高可用部署吗
