### ISSUE TITLE
init-archery 初始化未创建表archery.sql_instance_tag

### ISSUE THREAD

**Issue by longyinghua** [hhyo/archer#1714]
### 重现步骤

ERROR 1146 (42S02) at line 2: Table 'archery.sql_instance_tag' doesn't exist
![11](https://user-images.githubusercontent.com/79961581/181206023-f60bd902-539c-4cff-b841-ad359ae2c21f.png)

### 预期外的结果

![11](https://user-images.githubusercontent.com/79961581/181205989-e9080f69-1505-458e-bca6-0fd60fdc18b1.png)

### 日志文本

```shell
Warning: Using a password on the command line interface can be insecure.
ERROR 1146 (42S02) at line 2: Table 'archery.sql_instance_tag' doesn't exist
CommandError: "mysql --user=root --password=123456 --host=archery-mysql --port=3306 archery" returned non-zero exit status 1.
```

### 版本

1.8.5

### 部署方式

K8S

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL：8.0.28

**Comment by hhyo** [comment]
看错误是settings配置不正确，数据库表没有正常初始化

**Comment by longyinghua** [comment]
能否指出需要在初始化哪个文件进行更改吗

**Comment by longyinghua** [comment]
通过helm方式部署，在pod内手动执行admin.sh init 进行初始化，并且执行后执行./admin.sh migration ,发现导入sql时报错和通过kubectl logs 看到的报错是一样的，问题就出在导入sql的地方，详细看图
![Uploading 2.png…]()
![Uploading 3.png…]()

**Comment by longyinghua** [comment]
通过helm方式部署，在pod内手动执行admin.sh init 进行初始化，并且执行后执行./admin.sh migration ,发现导入sql时报错和通过kubectl logs 看到的报错是一样的，问题就出在导入sql的地方，详细看图
![2](https://user-images.githubusercontent.com/79961581/181405491-2b310bb5-d3f1-4615-b5ad-a8f493b4e919.png)
![3](https://user-images.githubusercontent.com/79961581/181405506-837f9013-9506-4c3d-ab06-8f76ac59c48d.png)

**Comment by hhyo** [comment]
helm部署方式的配置没有更新，rf相关有缺失，可以参考https://github.com/hhyo/Archery/blob/4d96ac680b1c6bcc0ed3f8a54f793b668402033a/archery/settings.py#L180

**Comment by LeoQuote** [comment]
用最新的镜像吧 hhyo/archery:master

**Comment by longyinghua** [comment]
好的，我试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhyo/Archery"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hhyo/Archery] init-archery 初始化未创建表archery.sql_instance_tag (Issue #1714)





 
用最新的镜像吧 hhyo/archery:latest

**Comment by LeoQuote** [comment]
不好意思, 镜像的tag 有误, 我已经在上面修改了, 最新的镜像是 hhyo/archery:master

**Comment by longyinghua** [comment]
好的，周一我尝试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhyo/Archery"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hhyo/Archery] init-archery 初始化未创建表archery.sql_instance_tag (Issue #1714)





 
不好意思, 镜像的tag 有误, 我已经在上面修改了, 最新的镜像是 hhyo/archery:master
