### ISSUE TITLE
执行sql上线backup失败

### ISSUE THREAD

**Issue by gitzhuyongfu** [hhyo/archer#1732]
### 重现步骤

1.填写sql上线流程并选择备份
2.提交审核
3.审核通过
4.执行sql
5.执行成功，但备份失败

### 预期外的结果

报错为如下：
Backup: ERROR 1045 (28000): Access denied for user
问题核查：
已排查inception的config.toml配置跟系统配置的数据库连接的用户是一致的

### 版本

1.8.5

### 部署方式

Docker

**Comment by danielnanuk** [comment]
同上
1. inception的config.toml的配置和系统配置一样
2. 无论我在系统配置里面怎么配backup_user, 报错始终是: "Backup: ERROR 1045 (28000): Access denied for user 'archery'@'%!'(MISSING) (using password: YES)."

**Comment by gitzhuyongfu** [comment]
可以试下这个：GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'archery'@'%';

**Comment by danielnanuk** [comment]
我统一了以下数据库的用户名和密码, 并且用户名改为"archery"
1. 实例的用户名和密码(实际连接到业务库)
2. goinception在archery上面配置的用户名密码
3. goinception的config.toml里面的用户名和密码
终于可以了
但以上的数据库用户名和密码, 实际连接到的是两个不同的数据库

**Comment by calvin2020** [comment]
> 可以试下这个：GRANT REPLICATION SLAVE, REPLICATION CLIENT ON _._ TO 'archery'@'%';

请教下，这样授权之后，问题解决了吗？
