### ISSUE TITLE
配置PG实例，无法连接

### ISSUE THREAD

**Issue by JaySem** [hhyo/archer#1743]
### 重现步骤

1.新增PG实例: 输入实例名称、实例类型、数据类型PgSQL、实例连接ip地址、端口、只读用户名、密码、数据库名
2.点击测试
3.提示无法连接实例，FATAL:password authencication faild for user "archery_read"

在虚拟机上使用命令，确定密码是正确的。

### 预期外的结果

<img width="397" alt="截屏2022-08-08 下午2 57 09" src="https://user-images.githubusercontent.com/40017841/183358022-8f79548b-73ba-437e-91b1-b8f2586f872c.png">

### 版本

1.8.5

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

PG的数据库版本是13.4
archery版本：1.8.5

**Comment by beebird** [comment]
遇到相同的问题。1.8.5之后有几个fix，但是还没有发布。焦急

**Comment by beebird** [comment]
可以用master，docker部署的话是hhyo/archery:master

**Comment by peng19832** [comment]
> 遇到相同的问题。1.8.5之后有几个fix，但是还没有发布。焦急

你着急的话，可以找到对应的代码替换下，然后用外挂的方式，重新创建下容器
