### ISSUE TITLE
反向解析binlog日志，有个安全隐患

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1759]
### 重现步骤

使用工具插件里的工具，解析binlog，会有安全隐患，后台解析进程里数据库的用户名/密码都是明文的
![image](https://user-images.githubusercontent.com/9590209/184058739-05f3a888-bd2a-44ad-8439-aaba3d79a27c.png)

### 预期外的结果

期望，解析进程里，数据库用户密码隐藏

### 版本

1.8.5

### 部署方式

Docker

**Comment by LeoQuote** [comment]
一般来说如果主机安全都不能保证，这里再怎么隐藏也是没有用的，进程只会存在一会，安全隐患应该是不高的，麻烦确认一下。如果在日志中没有出现的话，这个问题应该是不会去做的。

**Comment by Alceatraz** [comment]
> 一般来说如果主机安全都不能保证，这里再怎么隐藏也是没有用的，进程只会存在一会，安全隐患应该是不高的，麻烦确认一下。如果在日志中没有出现的话，这个问题应该是不会去做的。

LXC和K8S之类的基于进程隔离环境，如果有分析工具开了记录的话还是会被母鸡看到的

个人推荐用类似于JenkinsPipeline用环境变量传递，即使工具不支持，用xargs也可以很方便的隐藏掉某些参数

**Comment by LeoQuote** [comment]
我说的就是包括宿主机在内的主机安全, 你说的这个方法是可以做的, 欢迎 pr https://github.com/hhyo/Archery/blob/master/sql/plugins/my2sql.py

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/6bb36f721481deaff1a29c29c26cd674d02620a3/sql/binlog.py#L141-L163 具体调用是在这里, plugin 加一个入口让调用方可以传递环境变量, 后面就可以加了

**Comment by peng19832** [comment]
明白，谢谢大佬们
