### ISSUE TITLE
pgsql查询时json字段显示为[object Object]

### ISSUE THREAD

**Issue by liujing1087** [hhyo/archer#1792]
### 重现步骤

查询pgsql数据库表，部分字段内容为json格式时，前端显示为[object Object]

### 预期外的结果

![微信截图_20220822182030](https://user-images.githubusercontent.com/32185326/185899350-97ae750a-f4a8-43ee-aaf9-871f9701a1d3.png)
![微信截图_20220822182120](https://user-images.githubusercontent.com/32185326/185899375-4950246f-f08d-4622-83a3-4120f62664f7.png)

### 版本

1.8.5

### 部署方式

Docker

**Comment by carlors** [comment]
+1，我也遇到这样的问题，希望可以解决。
