### ISSUE TITLE
helm 1.8.5部署后  普通用户没有导出sql权限，在可用权限中找不到下载的权限。

### ISSUE THREAD

**Issue by smallhorsegg** [hhyo/archer#1795]
### 重现步骤

![image](https://user-images.githubusercontent.com/49267785/186070199-a6ef0393-dd44-4edc-95b3-7f63e8713b59.png)
![Uploading image.png…]()

### 预期外的结果

之前手动部署1.8.1是可以导出的

### 版本

1.8.5

### 部署方式

K8S

**Comment by nick2wang** [comment]
善用搜索 #1771
