### ISSUE TITLE
my2sql 解析 binlog 无结果

### ISSUE THREAD

**Issue by michael-liumh** [hhyo/archer#1799]
### 重现步骤

1. 打开 my2sql 页面，任意选择一个打开 binlog 的实例，且确认 binlog 格式为 row
2. 不过滤任意库表，输出所有结果
3. 发现解析没有输出结果，但是用 root 账户解析确是正常的

经测试，发现，若密码中存在美元符($)，则 my2sql 会解析不出结果，密码中去除美元符后，则解析正常。
具体原因待进一步分析。

### 预期外的结果

正常解析所有库表的操作，解析无结果，更换其它账户后解析正常，对比发现是 archery 使用的账户密码中存在美元符($)，替换后恢复正常

### 版本

1.8.5

### 部署方式

Docker

**Comment by nick2wang** [comment]
最新代码不能复现该问题，请更新代码后确认问题是否解决
