### ISSUE TITLE
能否开放对某些数据库执行执行sql的权限 比如insert  update

### ISSUE THREAD

**Issue by liuhaixiao** [hhyo/archer#1831]
### 重现步骤

我们这边有点需求就是  比如有个实例添加到平台了 我们想直接可以执行insert  或者update 语句      

当然这个数据库权限只分配给特定的人

### 预期外的结果

预期就是可以在查询方框内 直接 insert 语句

### 日志文本

```shell
Archery (v1.8.5)
```

### 版本

 Archery (v1.8.5)

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

1

**Comment by nick2wang** [comment]
上线和查询是必须要分隔开的，可以给特定人足够的权限，上线时自行审核自行执行
