### ISSUE TITLE
不能连接AWS ElastiCache redis集群

### ISSUE THREAD

**Issue by JCchenxiang** [hhyo/archer#1848]
### 重现步骤

1. 配置好redis连接信息
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/37063302/191182490-366dee1e-75be-4f4f-871d-cd750d53fe4c.png">

2. 在线查询中选择redis实例后报504 
redis引擎版本 5.0.6

### 预期外的结果

aws 的redis开启了传输中加密，是否archery不支持此类型的连接

### 版本

1.8.3

### 部署方式

K8S

**Comment by feiazifeiazi** [comment]
现在Redis支持了SSL。你有没有试一下

**Comment by LeoQuote** [comment]
版本太低了，自己升到master再看
