### ISSUE TITLE
1.9.0版本启动后对于没有权限的页面返回500错误

### ISSUE THREAD

**Issue by 402309718** [hhyo/archer#1884]
### 重现步骤

1.启动1.9.0版本
2.新建非管理员用户test仅给与permission|菜单权限
3test用户尝试访问没有权限的页面
4.报错500
5.后台日志 File "/opt/venv4archery/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/archery/common/utils/permission.py", line 14, in wrapper
    if request.is_ajax():
AttributeError: 'WSGIRequest' object has no attribute 'is_ajax'
(看起来request.is_ajax函数不兼容了)

### 预期外的结果

报错500 internal error
应该提示
![image](https://user-images.githubusercontent.com/7498000/192663193-8fb95cef-0ce0-4739-b6e9-8afb4010fce8.png)

### 版本

1.9.0.

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

无

**Comment by hhyo** [comment]
这个方法在django3.1版本中被移除了，欢迎提个pr修复，参考：https://stackoverflow.com/questions/63629935/django-3-1-and-is-ajax

https://docs.djangoproject.com/zh-hans/3.1/ref/request-response/#django.http.HttpRequest.is_ajax

**Comment by 402309718** [comment]
我改了,但是不知道怎么提pr,求指导
