### ISSUE TITLE
工单日志接口workflow_type 不一致返回500错误

### ISSUE THREAD

**Issue by 402309718** [hhyo/archer#1886]
### 重现步骤

1.查询一个DDL类型的工单流程
2.指定workflow_type=1
3.post查询返回 500
4.错误日志:
py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
sql.models.WorkflowAudit.DoesNotExist: WorkflowAudit matching query does not exist.

### 预期外的结果

![image](https://user-images.githubusercontent.com/7498000/192708935-c05bb539-29f0-4b1d-8756-1e5734b08a19.png)

### 版本

1.9.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

1

**Comment by nick2wang** [comment]
漏了校验，可以在serializers里加一下
