### ISSUE TITLE
修改mysql表中的字段报错

### ISSUE THREAD

**Issue by maxianwei** [hhyo/archer#1889]
### 重现步骤

执行修改表字段中的数据时保错：
执行语句如下：
alter table `scene_action` modify column `value` varchar(500) NOT NULL DEFAULT '' COMMENT '某种触发方式对应的配置值'

### 预期外的结果

语句是
alter table `scene_action` modify column `value` varchar(500) NOT NULL DEFAULT '' COMMENT '某种触发方式对应的配置值'
同样的语句在测试环境上线没问题的，在生产环境报错，不知道是否跟数据量级有关，大概影响10w条数据。
报错如下图：
![image](https://user-images.githubusercontent.com/34542869/192741186-bab038fe-9ea3-4930-b014-bd32b97338b0.png)
![image](https://user-images.githubusercontent.com/34542869/192741290-b3dab9e7-c262-474d-9876-096652f79264.png)

Error copying rows from `vhome_scene`.`scene_action` to `vhome_scene`.`_scene_action_new`: Threads_connected=1726 exceeds its critical threshold 1000
这个1000临界值是pt-online-schema-change的参数吧？应该在哪里调呢？

### 日志文本

```shell
archery没有这条语句相关的日志信息
goinception有报错如下：
time="2022/09/28 14:57:51.841" level=error msg="sh [-c pt-online-schema-change --alter \"MODIFY COLUMN \\`value\\` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '某种触发方式对应的配置值'\"   --set-vars lock_wait_timeout=60 --charset=utf8  --chunk-time 1  --critical-load Threads_connected:1000,Threads_running:80  --max-load Threads_connected:1000,Threads_running:80  --sleep=0 --recurse=1  --check-interval 5  --alter-foreign-keys-method=none --force  --execute  --statistics  --max-lag=3 --no-version-check  --recursion-method=processlist --progress percentage,1  --user=\"dbms_archery\" --password='duv9R1xSU@5akUBk' --host=10.62.1.182 --port=3306 D=vhome_scene,t='scene_action']" file=osc.go func=execCommand line=902
time="2022/09/28 14:57:51.841" level=error msg="exit status 11" file=osc.go func=execCommand line=903
time="2022/09/28 15:28:25.827" level=error msg="sh [-c pt-online-schema-change --alter \"MODIFY COLUMN \\`value\\` VARCHAR(800) NOT NULL DEFAULT '' COMMENT '某种触发方式对应的配置值'\"   --set-vars lock_wait_timeout=60 --charset=utf8  --chunk-time 1  --critical-load Threads_connected:1000,Threads_running:80  --max-load Threads_connected:1000,Threads_running:80  --sleep=0 --recurse=1  --check-interval 5  --alter-foreign-keys-method=none --force  --execute  --statistics  --max-lag=3 --no-version-check  --recursion-method=processlist --progress percentage,1  --user=\"dbms_xxx\" --password='xxx' --host=10.62.1.182 --port=3306 D=vhome_scene,t='scene_action']" file=osc.go func=execCommand line=902
time="2022/09/28 15:28:25.827" level=error msg="exit status 11" file=osc.go func=execCommand line=903
```

### 版本

1.8.4

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL: 5.7.26
Browsers: Chrome

**Comment by maxianwei** [comment]
看起来像是线程连接数超过默认值1000个了，不知道这个要在哪里调整。

**Comment by nick2wang** [comment]
这里是通过goinception来调用pt-osc，goinception相关参数配置参考：[osc_critical_thread_connected](https://hanchuanchuan.github.io/goInception/zh/osc.html)

**Comment by jimsoft1000** [comment]
我也遇到过，调整一下Archery-1.8.5/src/docker-compose/inception/config.toml文件
osc_critical_thread_connected = 3000
osc_critical_thread_running = 1000
osc_max_thread_connected = 3000
osc_max_thread_running = 1000
osc_check_interval = 3600

**Comment by maxianwei** [comment]
好的，谢谢各位大佬，我试下。
