### ISSUE TITLE
连接aws redis5.0.6版本单机失败

### ISSUE THREAD

**Issue by chenyu1st** [hhyo/archer#1906]
### 重现步骤

1.实例管理配置连接aws redis5.0.6版本单机
2.点击测试连接
3.报错

### 预期外的结果

![企业微信截图_16654520381039](https://user-images.githubusercontent.com/43984892/194977555-a5c36b12-4a70-41da-8b54-a317df4bf106.png)

### 日志文本

```shell
[2022-10-11 09:24:05,722][MainThread:139990492428096][task_id:default][redis.py:69][WARNING]- Redis CONFIG GET databases 执行报错，异常信息：unknown command `CONFIG`, with args beginning with: `GET`, `databases`,
```

### 版本

1.9.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

aws redis:5.0.6

**Comment by hhyo** [comment]
看起来Keyspace命令返回结构也改了


有使用场景的的自己fix吧，没有环境，无法修复

**Comment by chenyu1st** [comment]
我帮你们修复了，就是rows的类型问题

https://github.com/hhyo/Archery/commit/e397892f8b23e550ebbcf671c10ee9ef33f5b77c

**Comment by hhyo** [comment]
#1451
