### ISSUE TITLE
union all语句脱敏失效

### ISSUE THREAD

**Issue by dengdalue** [hhyo/archer#1922]
### 重现步骤

对同一张表进行union all查询时可以成功脱敏，但是对不同表进行union all查询时脱敏就失效了，比如：
select code from mem_0
union all
select code from mem_0
可以成功脱敏；

select code from mem_0
union all
select code from mem_1
无法成功脱敏。

### 预期外的结果

对不同表进行union all查询时脱敏就失效了

### 版本

1.8.5

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL: 5.7.38
Browsers: Chrome
goInception: v1.3.0-1-g140054c-dirty
redis: 5

**Comment by nick2wang** [comment]
这个问题之前应该已经修复过了，可以更新最新版本试下
![image](https://user-images.githubusercontent.com/33473924/196594244-d5ad17bf-3950-4f28-a9cc-bc876f159d85.png)
![image](https://user-images.githubusercontent.com/33473924/196594253-b9bda2b8-b7c4-4b20-b43f-b8fada27d689.png)

**Comment by hhyo** [comment]
#1516

**Comment by dengdalue** [comment]
好的，谢谢，我升级看看！

**Comment by dengdalue** [comment]
> #1516
