### ISSUE TITLE
MYSQL8 在线查询功能 报错

### ISSUE THREAD

**Issue by qn2060** [hhyo/archer#1927]
### 重现步骤

1、一个非dba角色用户（主要是不能有查询所有库权限）申请了相关库的权限
2、在相关库执行类似SQL
select term,assist_institution_code,pr_m_amonunt,pr_m_amonunt_total
  FROM 
  (

    select term,
    assist_institution_code 
       ,pr_m_amonunt,ROW_NUMBER() over(partition by term order by pr_m_amonunt  desc) as rn,
       sum(pr_m_amonunt) over (partition by term) pr_m_amonunt_total
    FROM  
    (

    select 
            term,replace(assist_institution_code,'_YKB','')assist_institution_code,SUM(loan_amount)pr_m_amonunt
      from t_order_day
      where 1=1 
      and stat_date >= DATE_FORMAT('2022-10-21','%Y-%m-01')  and stat_date <= '2022-10-21' 
        and DATE_FORMAT('2022-10-21','%Y-%m') = DATE_FORMAT('2022-10-21','%Y-%m')
            group by  term,replace(assist_institution_code,'_YKB','')
    )t_amount
  )t_rn
  where rn = 1

### 预期外的结果

<html>
<body>
<div class="fixed-table-body" style="box-sizing: border-box; overflow: auto; height: 353px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Error
--
无法校验查询语句权限，请联系管理员，错误信息：line 7 column 40 near "(partition by term order by pr_m_amonunt  desc) as rn,        sum(pr_m_amonunt) over (partition by term) pr_m_amonunt_total     FROM     (      select             term,replace(assist_institution_code,'_YKB','')assist_institution_code,SUM(loan_amount)pr_m_amonunt       from t_order_day       where 1=1       and stat_date >= DATE_FORMAT('2022-10-21','%Y-%m-01')  and stat_date <= '2022-10-21'         and DATE_FORMAT('2022-10-21','%Y-%m') = DATE_FORMAT('2022-10-21','%Y-%m')             group by  term,replace(assist_institution_code,'_YKB','')     )t_amount   )t_rn   where rn = 1"

</div><br class="Apple-interchange-newline">
</body>
</html>

### 日志文本

```shell
[2022-10-21 15:40:24,202][MainThread:140379151083328][task_id:default][query_privileges.py:85][ERROR]- 无法校验查询语句权限，PROD-微神马生产MYSQL8-RDS，select term,assist_institution_code,pr_m_amonunt,pr_m_amonunt_total
  FROM
  (

    select term,
    assist_institution_code
       ,pr_m_amonunt,ROW_NUMBER() over(partition by term order by pr_m_amonunt  desc) as rn,
       sum(pr_m_amonunt) over (partition by term) pr_m_amonunt_total
    FROM
    (

    select
            term,replace(assist_institution_code,'_YKB','')assist_institution_code,SUM(loan_amount)pr_m_amonunt
      from t_order_day
      where 1=1
      and stat_date >= DATE_FORMAT('2022-10-21','%Y-%m-01')  and stat_date <= '2022-10-21'
        and DATE_FORMAT('2022-10-21','%Y-%m') = DATE_FORMAT('2022-10-21','%Y-%m')
            group by  term,replace(assist_institution_code,'_YKB','')
    )t_amount
  )t_rn
  where rn = 1，Traceback (most recent call last):
  File "/opt/archery/sql/query_privileges.py", line 69, in query_priv_check
    table_ref = _table_ref(sql_content, instance, db_name)
  File "/opt/archery/sql/query_privileges.py", line 409, in _table_ref
    query_tree = engine.query_print(instance=instance, db_name=db_name, sql=sql_content).get('query_tree')
  File "/opt/archery/sql/engines/goinception.py", line 165, in query_print
    raise RuntimeError(print_info.get('errmsg'))
RuntimeError: line 7 column 40 near "(partition by term order by pr_m_amonunt  desc) as rn,
       sum(pr_m_amonunt) over (partition by term) pr_m_amonunt_total
    FROM
    (

    select
            term,replace(assist_institution_code,'_YKB','')assist_institution_code,SUM(loan_amount)pr_m_amonunt
      from t_order_day
      where 1=1
      and stat_date >= DATE_FORMAT('2022-10-21','%Y-%m-01')  and stat_date <= '2022-10-21'
        and DATE_FORMAT('2022-10-21','%Y-%m') = DATE_FORMAT('2022-10-21','%Y-%m')
            group by  term,replace(assist_institution_code,'_YKB','')
    )t_amount
  )t_rn
  where rn = 1"
```

### 版本

1.8.5

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

mysql8

**Comment by LeoQuote** [comment]
先升最新版再试试
