### ISSUE TITLE
是否支持阿里云的polardb？

### ISSUE THREAD

**Issue by lx308033262** [hhyo/archer#1929]
### 重现步骤

有没有在polardb上面使用archery的

### 预期外的结果

可以使用archery审核polardb

### 版本

v1.8.5

### 部署方式

Docker

**Comment by nick2wang** [comment]
ploardb据说是高度兼容mysql语法的，有人试过可用#1271，可以先当做mysql来配置实例，使用中如果有出现兼容性问题欢迎反馈，一起改进
