### ISSUE TITLE
开启两步验证扫描登陆出现：undefined

### ISSUE THREAD

**Issue by FSerKevin** [hhyo/archer#1963]
### 重现步骤

发现使用火狐浏览器和safari浏览器首次登陆新版本archery时使用两步验证扫描后输入验证码完成验证时出现：undefined，且可登陆成功，但页面没有提示已开启两步验证

### 预期外的结果

不确定是否是bug，还是浏览器的问题，如果出现了：undefined，那么每次登陆archery的时候都会让其扫描二维码验证绑定。
在换谷歌浏览器正常绑定之后 上述问题就没有出现
![WX20221115-104542](https://user-images.githubusercontent.com/79827043/201814479-c9b29415-60e6-4ef3-84ba-f8a5af59bc00.png)

### 版本

1.9.1

### 部署方式

Docker

**Comment by nick2wang** [comment]
火狐浏览器跳转到index的时候会强制打断保存2fa配置的ajax请求，浏览器的策略问题，chrome没有该问题
