### ISSUE TITLE
请对问题进行简要的描述

### ISSUE THREAD

**Issue by database-on-line** [hhyo/archer#1967]
### 重现步骤

执行sql的实例aurora 
备份sql的实例aws rds mysql8.0.28
使用的archery版本：master,1.9.1,1.8.5,1.8.1
遇到的问题：
开启了备份，--backup=1的时候，报错con:36 driver: bad connection.，看起来像是goinception的[goInception](https://github.com/hanchuanchuan/goInception/tree/8e0761f8e8837af7caa74ad62bfe967f57ce861c)/[session](https://github.com/hanchuanchuan/goInception/tree/8e0761f8e8837af7caa74ad62bfe967f57ce861c/session)/conn.go /报错

关闭备份能够正常执行，希望大佬帮忙看下

### 预期外的结果

备份下不能正常执行工单，日志没有结果，希望大佬帮忙看下

### 日志文本

```shell
无
```

### 版本

1.9.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

执行sql的实例aurora 
备份sql的实例aws rds mysql8.0.28
使用的archery版本：master,1.9.1,1.8.5,1.8.1

**Comment by database-on-line** [comment]
已解决，没在config端配置备份库地址，使用了默认地址，只在前端更改了，希望大佬能把这快的报错稍微详细些，或者把官网部署加上inc的部分

**Comment by Belee05** [comment]
这里我也才踩坑了，我用已有的数据库，在前端配置备份数据库后发现执行审批SQL报错con:8 driver: bad connection.后来修改config.toml配置文件才解决。
