### ISSUE TITLE
 SQL上线模块不支持sql中使用变量

### ISSUE THREAD

**Issue by xiang-coco** [hhyo/archer#1969]
### 重现步骤

1.将带有变量的sql 放到SQL上线 中,
例如： 
 SET @userId =  12334;
 SET @mobile= 12333;

2.点击 “SQL检测” 按钮
3.检测结果中 审核状态为 error , 审核信息为 “Not supported statement type.”

### 预期外的结果

 审核状态为pass ,无error

### 版本

1.81

### 部署方式

手工部署

**Comment by nick2wang** [comment]
goinception审核不支持变量
