### ISSUE TITLE
static目录权限是750，导致css等访问403

### ISSUE THREAD

**Issue by xuzheng0017** [hhyo/archer#1970]
### 重现步骤

使用src/charts配置使用helm部署

### 预期外的结果

访问首页，加载css等时返回403，查看/opt/archery/static目录权限是750。需要执行
`chown -R nginx.nginx /opt/archery/static`
才能正常访问，有遇到这种情况的吗？

### 版本

1.9.1

### 部署方式

K8S

**Comment by LeoQuote** [comment]
推荐你参考这里的 helm chart https://github.com/douban/charts/blob/master/charts/archery/values.yaml , 还有就是你的这个错误可能是镜像版本需要更新, 你可以改一个版本号再试试

**Comment by xuzheng0017** [comment]
感谢回答！没再试其他版本和douban的yaml（有点滞后），我直接修改了下 templates/startup.sh，在`python3 manage.py collectstatic -v0 --noinput`之后加了句：`chown -R nginx.nginx /opt/archery/static`
