### ISSUE TITLE
SQLserver 数据库查询语句中distinct无法使用

### ISSUE THREAD

**Issue by pengkang1991** [hhyo/archer#1981]
### 重现步骤

mysql5.7 ，SQLserver 数据库下使用查询功能 distinct ，truncate 语句无法使用，会提示语法错误。详情见下图

### 预期外的结果

![企业微信截图_16692699094192](https://user-images.githubusercontent.com/49478192/203706560-df596e7f-fdf6-4ad1-a947-c432c109834a.png)

### 版本

1.8.5

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL: 5.7.26  SQLserver

**Comment by pengkang1991** [comment]
MySQL: 5.7.26

**Comment by pengkang1991** [comment]
![image](https://user-images.githubusercontent.com/49478192/203715125-4b40a201-ed30-425c-a70f-c02861553a7c.png)
MySQL: 5.7.26 创建表的时候不支持longtxt类型

**Comment by nick2wang** [comment]
参考：
1. #801
2. https://github.com/hanchuanchuan/goInception/issues/529
