### ISSUE TITLE
truncate 无法通过，是否能通过手工审批的方式

### ISSUE THREAD

**Issue by pengkang1991** [hhyo/archer#1984]
### 重现步骤

开发人员想要执行truncate 语句，系统自动驳回，是否能通过人工审批的方式放行类似危险的SQL执行。

### 预期外的结果

系统提示：Drop/truncate 'organ_role_sss' is not allowed, please replace with alter rename statement.
![image](https://user-images.githubusercontent.com/49478192/204230464-4fc5331a-db50-45fa-a470-23ca56123a5b.png)

### 版本

v1.9.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL: 5.7.26

**Comment by nick2wang** [comment]
参考 [#1358](https://github.com/hhyo/Archery/issues/1358#issuecomment-1019933090)
