### ISSUE TITLE
docker-compose部署后登录提示forbidden

### ISSUE THREAD

**Issue by 101536363** [hhyo/archer#1996]
### 重现步骤

您好 我使用docker-compose启动服务后设置完账号密码，登录过程提示forbidden，这个是我这边部署哪里没注意的问题么，还是需要单独开启下管理员登录的权限？

### 预期外的结果

配置及操作
![image](https://user-images.githubusercontent.com/72073965/206621453-e666037a-9b3f-4306-8c9b-a4292c328abe.png)
![image](https://user-images.githubusercontent.com/72073965/206621855-fc725bfb-c3c0-48d0-b042-e5bc49095b36.png)
![image](https://user-images.githubusercontent.com/72073965/206621933-e3e0a201-30b4-45d3-9aa7-e1e8c7aeb274.png)

登录错误
![image](https://user-images.githubusercontent.com/72073965/206621530-a0ad7ab9-8a07-4b6e-9cfc-65db26d25b03.png)

### 版本

1.9.1

### 部署方式

Docker

**Comment by hhyo** [comment]
https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins

还是这个参数配置问题，需要配置客户端访问的地址

**Comment by huoshenyingmu** [comment]
![image](https://user-images.githubusercontent.com/27325498/209101645-bd7f483d-0315-478d-88c2-54544c381fed.png)
感谢，这个怎么办

**Comment by LeoQuote** [comment]
自己看文档啊, 点进去有中文哦

**Comment by jiahuiss** [comment]
有同样的问题请问ip的话怎么填写，必须域名吗
