### ISSUE TITLE
Redis集群模式报错module 'redis' has no attribute 'cluster'

### ISSUE THREAD

**Issue by wybug** [hhyo/archer#1997]
### 重现步骤

1. 配置一个Redis集群模式实例, 配置其中一个节点的IP和端口
2. 在实例列表中，选择新增加实例，点击测试

### 预期外的结果

无法连接实例, module 'redis' has no attribute 'cluster', 在https://demo.archerydms.com/instance/中也同样存在
![图片](https://user-images.githubusercontent.com/29219066/207806559-5239847e-ed39-4d81-8b71-67a358e50484.png)

### 日志文本

```shell
无法连接实例, module 'redis' has no attribute 'cluster'
```

### 版本

1.9.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

无

**Comment by nick2wang** [comment]
高版本redis-py与qcluster依赖冲突，可以先手动升级redis-py #1966

**Comment by chenglei96** [comment]
您说的手动升级redis-py是升级docker-compose里面的那个redis嘛，具体如何升级呢
