### ISSUE TITLE
更新Dockerfile

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#2008]
### 重现步骤

我做了镜像体积精简，用多段构建，但发现也就少了几百M，还是沿用了你们的Dockerfile和Dockerfile-base，没怎么大改
把里面从github下载的几个包，换成了从本地复制，因为github下载实在慢
还有把yum源和pip源换成了清华的
[archery_dockerfile.zip](https://github.com/hhyo/Archery/files/10293585/archery_dockerfile.zip)

### 预期外的结果

镜像精简

### 版本

1.9.1

### 部署方式

Docker

**Comment by LeoQuote** [comment]
请直接提pr

**Comment by peng19832** [comment]
> 请直接提pr

@LeoQuote 
已经提了，但github自检，只base镜像成功了，应用的镜像，怎么都通不过

**Comment by LeoQuote** [comment]
CI 不报错是基本要求, 还请努力完成.

**Comment by peng19832** [comment]
> CI 不报错是基本要求, 还请努力完成.

@LeoQuote 
base镜像是构建成功了，但是应用镜像的dockerfile里，我不明白，怎么引入这个base镜像的tag号，每次构建应用镜像，都报找不到base镜像
![image](https://user-images.githubusercontent.com/9590209/210334259-b614d546-dd3e-46c4-8ff8-6169a76aa78c.png)

**Comment by peng19832** [comment]
> CI 不报错是基本要求, 还请努力完成.

@LeoQuote 
大佬，我这里翻不了墙，改个dockerfile，测试十次，有九次都下不到依赖包，这个应用镜像，不应该在base镜像构建完成，自动引入Dockerfile中么，每次check，第一时间应用镜像就失败
