### ISSUE TITLE
查询结果导出Excel时，数据的美元$符被转换为数字0，

### ISSUE THREAD

**Issue by 0vally1** [hhyo/archer#2012]
### 重现步骤

SQL查询，表中数据有美元$符，对结果进行导出Excel，打开Excel，发现本应出现的$，变成了数字零0

### 预期外的结果

$符正确导出

### 版本

1.8.5

### 部署方式

手工部署

![image](https://user-images.githubusercontent.com/30279431/209599864-30e4ab24-9bd1-4ac6-aa15-c35c54c28023.png)

![image](https://user-images.githubusercontent.com/30279431/209599897-92e2ffe6-45fb-411d-b2df-be4718cfbc3c.png)

**Comment by unknowissue** [comment]
导出成csv，这个格式会比较好

**Comment by 0vally1** [comment]
> 导出成csv，这个格式会比较好

不需要CSV

**Comment by LeoQuote** [comment]
导出功能由前端组件提供, 如有问题还请去前端组件网站提 issue, 导出功能本身就有争议, 很多公司甚至不希望有导出按钮, archery 的主要定位也不是数据导出, 如果有相关方案欢迎 pr.

**Comment by 0vally1** [comment]
> 引导出功能由前端组提供, 如有问题还请去前端组网站提供issue, 引导出功能本身就有争论, 很多公司甚至不希望有引导出按键，射箭的主要定位也不是数据导向，如果有相关方案欢迎pr .

去年12月提出的问题，我最终使用后端导出解决了它，只是今天才有人回复，而回复，明白了啵
