### ISSUE TITLE
my2sql分析binlog时会成为僵尸进程的问题

### ISSUE THREAD

**Issue by tanglu86** [hhyo/archer#2033]
### 重现步骤
进入工具插件-My2sql，点击获取SQL后没有反应，进入服务器查看my2sql会变成僵尸进程，重启服务器后更换my2sql的各个选项进行测试问题依然存在

### 预期外的结果

![1](https://user-images.githubusercontent.com/38269740/211953232-612ac241-915c-4a74-9682-10e8d4effc06.png)
![2](https://user-images.githubusercontent.com/38269740/211953236-a2e755d0-5552-4a9d-ae84-7a9c6cafdfeb.png)

### 版本

1.8.4

### 部署方式

手工部署

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL: 5.7.30
Browsers: Chrome
goInception: v1.3.0-42

**Comment by hhyo** [comment]
#1634

可以升级至最新版本
