### ISSUE TITLE
helm 安装 v1.9.1 无法登录，报 Forbidden

### ISSUE THREAD

**Issue by Spinestars** [hhyo/archer#2053]
### 重现步骤

1. 注释 “django.middleware.csrf.CsrfViewMiddleware” 可以登录 webui，但在 django admin 后台执行用户删除的时候报：CSRF验证失败. 请求被中断.
2. 不注释 “django.middleware.csrf.CsrfViewMiddleware”，则登录 webui 报 Forbidden

### 预期外的结果

无

### 日志文本

```shell
无
```

### 版本

1.9.1

### 部署方式

K8S

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

无

**Comment by devops007** [comment]
.env => CSRF_TRUSTED_ORIGINS='*'

**Comment by devops007** [comment]
9123端口不能映射成其他，换了就跨域了。可以同时把.env里面的NGINX_PORT改一下试试

**Comment by hhyo** [comment]
参考https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins

**Comment by lucas5-code** [comment]
- env:
            - name: CSRF_TRUSTED_ORIGINS
              value: 'http://域名或者是公网IP+端口'
在pod中修改以上配置，就可以解决这个问题，小白好难

**Comment by baofang111** [comment]
> * env:
>   - name: CSRF_TRUSTED_ORIGINS
>   value: '[http://域名或者是公网IP+端口](http://%E5%9F%9F%E5%90%8D%E6%88%96%E8%80%85%E6%98%AF%E5%85%AC%E7%BD%91IP+%E7%AB%AF%E5%8F%A3)'
>   在pod中修改以上配置，就可以解决这个问题，小白好难

我试了一下，好像还是不行

**Comment by baofang111** [comment]
> * env:
>   - name: CSRF_TRUSTED_ORIGINS
>   value: '[http://域名或者是公网IP+端口](http://%E5%9F%9F%E5%90%8D%E6%88%96%E8%80%85%E6%98%AF%E5%85%AC%E7%BD%91IP+%E7%AB%AF%E5%8F%A3)'
>   在pod中修改以上配置，就可以解决这个问题，小白好难

没有注释 jango.middleware.csrf.CsrfViewMiddleware 但是在 env 配置了 公网可访问的 CSRF_TRUSTED_ORIGINS ，登录的时候还是报 403 Forbidden

**Comment by a1198457636** [comment]
我也是这个错误，你好，你是怎么解决的？
