### ISSUE TITLE
mongodb通过sql审核插入数据或是创建索引，执行都成功了，但实际上数据没插入，索引也没创建成功

### ISSUE THREAD

**Issue by liebao520** [hhyo/archer#2055]
### 重现步骤

标题

### 预期外的结果

![企业微信截图_16765402342842](https://user-images.githubusercontent.com/65648834/219327216-f6f8741c-b2d1-4dd6-9555-b64c8e651d24.png)
![企业微信截图_16765402725406](https://user-images.githubusercontent.com/65648834/219327259-9678a753-fd52-4c10-8187-13f0a782f742.png)

### 日志文本

```shell
日志没有报错
```

### 版本

1.8.5

### 部署方式

手工部署

**Comment by liebao520** [comment]
安装mongo，已解决

**Comment by liebao520** [comment]
安装mongo，已解决

**Comment by lizhiyoumai** [comment]
> 安装mongo，已解决

安装mongo指的是安装mongo驱动么

**Comment by liebao520** [comment]
部署archery的服务器上安装mongo，并设置好环境变量就可以了




bjf101
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhyo/Archery"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 晚上7:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hhyo/Archery] mongodb通过sql审核插入数据或是创建索引，执行都成功了，但实际上数据没插入，索引也没创建成功 (Issue #2055)





  
安装mongo，已解决
  
安装mongo指的是安装mongo驱动么
