### ISSUE TITLE
通过docker运行的archery和goinception配置ssh隧道时，执行sql或sql语法检查时，会出现审核不通过

### ISSUE THREAD

**Issue by hmtiannan** [hhyo/archer#2058]
### 重现步骤

通过docker运行的archery和goinception配置ssh隧道时，执行sql或sql语法检查时，会出现审核不通过
![image](https://user-images.githubusercontent.com/20086500/220257689-fc91c242-8944-4b9e-96ff-b54cbec14980.png)
已找到问题所在
![image](https://user-images.githubusercontent.com/20086500/220258135-8e27b142-616e-4885-b020-519b3c0b3af0.png)
传递给goinception的host是127.0.0.1导致goinception连接不上隧道端口
如果将传给goinception的host改为容器名‘archery’则正常
![image](https://user-images.githubusercontent.com/20086500/220258362-6846e084-1db9-45e6-8b98-07b78bd6901c.png)
请修复一下该bug

### 预期外的结果

![image](https://user-images.githubusercontent.com/20086500/220257689-fc91c242-8944-4b9e-96ff-b54cbec14980.png)

### 版本

1.9.1

### 部署方式

Docker

**Comment by hhyo** [comment]
这个信息应该需要做成配置项加载，毕竟不能判断是通过什么方式部署的

**Comment by Leif160519** [comment]
按照这个改就成功了：https://github.com/hhyo/Archery/wiki/FAQ#%E9%85%8D%E7%BD%AEssh%E9%9A%A7%E9%81%93%E5%90%8E%E6%97%A0%E6%B3%95%E8%BF%9E%E6%8E%A5

**Comment by hhyo** [comment]
#1362
