### ISSUE TITLE
helm部署时init-mysql失败 

### ISSUE THREAD

**Issue by yinmin2020** [hhyo/archer#2067]
### 重现步骤

1使用helm部署
2.版本是1.9.1
3.mysql、redis都是默认的参数什么都没有改动
4.mysql、redis的pod正常
5.archery在init的时候报mysql连接不上
6.使用工具连接mysql是正常的

### 预期外的结果

![image](https://user-images.githubusercontent.com/65068467/221801960-de994bc9-9e5b-46da-b4a7-292fa151a449.png)

### 版本

1.9.1

### 部署方式

K8S

**Comment by LeoQuote** [comment]
helm 安装可以参考这个文档： https://github.com/hhyo/Archery/wiki/k8s

以及helm 安装需要最新的版本，tag需要改成master，其他的tag我都没有测试过

**Comment by yinmin2020** [comment]
已经找到问题了，Archery的pod要去连接sf的mysql的话，在configmap里要配置完整的mysql的svc的地址才可以。希望可以帮助到其他人

**Comment by GodFan1995** [comment]
补充下吧，修改deploy中init容器的命令，将mysql的地址补全就行了
![image](https://github.com/hhyo/Archery/assets/60922431/aec65607-dbb3-448e-a711-584ba5448a91)

**Comment by Dravening** [comment]
我遇到了同样的问题，将mysql的连接方式修改成clusterIP后，pod可以运行了，但是初始化仍未成功。

django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'archery-mysql.guwave-prod1.svc.cluster.local' (111)")
ERROR 2003 (HY000): Can't connect to MySQL server on 'archery-mysql.XXXX.svc.cluster.local' (111)
CommandError: "mysql --user=root --host=archery-mysql.XXXX.svc.cluster.local --port=3306 --default-character-set=utf8mb4 archery" returned non-zero exit status 1.

**Comment by Dravening** [comment]
补充，问题已解决：

配置跨域后，自动重启了pod，mysql成功初始化。。。

配置跨域方式如下：
env:
- name: CSRF_TRUSTED_ORIGINS
value: '[http://域名或者是公网IP+端口]'

**Comment by cslingjun** [comment]
> 补充下吧，修改deploy中init容器的命令，将mysql的地址补全就行了 ![image](https://private-user-images.githubusercontent.com/60922431/298508525-aec65607-dbb3-448e-a711-584ba5448a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODQzOTYsIm5iZiI6MTcxNDk4NDA5NiwicGF0aCI6Ii82MDkyMjQzMS8yOTg1MDg1MjUtYWVjNjU2MDctZGJiMy00NDhlLWE3MTEtNTg0YmE1NDQ4YTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA4MjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYWQ2NTkxNDUwNjA0NTNmNWU1NzY4NjI3NGEwZWUxZjIxYzVjYzMwOWU3ZWI3ZGE4YmQwZWNkOTljYTlmNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CDei8nH88ke0eCTVGgjanB2-jm5L9TSCniP6G0V_I3Q)

哥们，这样调整后 ，初始化库的时候还是报错呀 ，都是用的archery-mysql，
