### ISSUE TITLE
dml免审核失效

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#2080]
### 重现步骤

我期望，数据运营人员，可以免DBA审核，执行自己的dml，但偶尔还是会走到DBA这里，为什么呢？
1、在配置中配置了只审核ddl；
2、权限中，授予可执行自己的sql；
![image](https://user-images.githubusercontent.com/9590209/225271353-768425d9-990a-4dc6-b856-fe766a2e84e8.png)

### 预期外的结果

![image](https://user-images.githubusercontent.com/9590209/225269743-4a2ff125-26c8-4271-a88a-ef40e12b2cb2.png)

### 日志文本

```shell
日志中无相关错误
```

### 版本

1.8.5

### 部署方式

Docker

**Comment by hhyo** [comment]
可以看是不是影响行数超限制了

**Comment by peng19832** [comment]
> 可以看是不是影响行数超限制了

影响行数限制？这个没地方配置呀，我以为是超过了最大更新数，结果发现并没有超

**Comment by hhyo** [comment]
> > 可以看是不是影响行数超限制了
> 
> 影响行数限制？这个没地方配置呀，我以为是超过了最大更新数，结果发现并没有超

最大更新行数是指工单内所有SQL的总影响行数

**Comment by peng19832** [comment]
> > > 可以看是不是影响行数超限制了
> > 
> > 
> > 影响行数限制？这个没地方配置呀，我以为是超过了最大更新数，结果发现并没有超
> 
> 最大更新行数是指工单内所有SQL的总影响行数

@hhyo 
请问大佬，这个影响行数，是有地方设定呢，还是代码里限制了呢？

**Comment by hhyo** [comment]
https://github.com/hhyo/archery/wiki/configuration#max_update_rows

**Comment by peng19832** [comment]
对了
