### ISSUE TITLE
导出top表空间数据不全

### ISSUE THREAD

**Issue by gaoqiang-0327** [hhyo/archer#2092]
### 重现步骤

再对top表空间列表数据导出时，选择导出Excel，记录只能导出14条。修改每页显示条数后，导出后依然是14条。

### 预期外的结果

希望导出所有数据

### 版本

1.9.1

### 部署方式

手工部署

**Comment by nick2wang** [comment]
bootstrap-table-export在server端分页时不能自定义导出
