### ISSUE TITLE
使用archery导出sql语句的null是字符串'(null)'有问题

### ISSUE THREAD

**Issue by bardyang** [hhyo/archer#2096]
### 重现步骤

1，业务根据SQL查询执行sql查询出来的数据导出sql语句后，标识符null是'(null)'
2，然后研发把数据插入到字符串的字段中后的数据是(null)，不是null，希望是标识符null

### 预期外的结果

![image](https://user-images.githubusercontent.com/13637514/228204151-3441a11d-b0a9-4ea2-9a26-33b745a15ee7.png)
这个是查询的数据是(null)，然后导出的insert sql语句中是字符串，然后把数据插入到字符串的字段中数据变为了(null)
![image](https://user-images.githubusercontent.com/13637514/228205645-84325bc7-1c2e-496a-8cef-cd254bf79e9c.png)

### 版本

1.7.2

### 部署方式

手工部署

**Comment by LeoQuote** [comment]
自己手工替换下不就好了 

参考下 :
* https://github.com/hhyo/Archery/issues/401 
* https://github.com/hhyo/Archery/issues/488
* https://github.com/hhyo/Archery/commit/9042b9d722e1723dfe997f02377fbf8f260eb50f

**Comment by bardyang** [comment]
> 自己手工替换下不就好了
> 
> 参考下 :
> 
> * [[ 问题咨询 ]在线查询null值显示为 -，有些字段值本身为 - 。 #401](https://github.com/hhyo/Archery/issues/401)
> * [[ bug ]  V1.3.7跟1.3.8 有一个查询显示问题，跟导出成sql 文件无非正确展示null问题 #488](https://github.com/hhyo/Archery/issues/488)
> * [9042b9d](https://github.com/hhyo/Archery/commit/9042b9d722e1723dfe997f02377fbf8f260eb50f)
手动替换没问题，主要是数据导出sql后不会做到全面的check一方面耗时另外一方面会忘记，这个人工去做校验风险太大，所以希望在导出的时候是正确的null

**Comment by LeoQuote** [comment]
请参考下我列出的两个issue，有不同的需求在这里，有人希望能显示为空，但实际上有可能和空字符串混淆，也有人想显示为 null，但是也有可能和字符串 null 混淆，最后我们的方案是 (null) 并置为灰色。

另外是archery本身的行为就不是一个数据导出工具，而是简简单单一个查询工具，本来就不应该依赖这里提供的数据导出功能。

关于这个问题欢迎提出具体的方案，也欢迎pr。
