### ISSUE TITLE
mongo审批单SQL执行结束，但没有创建出集合

### ISSUE THREAD

**Issue by ghost** [hhyo/archer#2099]
### 重现步骤

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58808248/228447743-3676f9b7-91b6-4d61-ac9c-23884ab56f5a.png">

### 预期外的结果

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58808248/228447899-c7ad4410-1a38-46c4-91b8-7640f70f7c34.png">

### 版本

1.9.1

### 部署方式

Docker

**Comment by nick2wang** [comment]
你创建的test01，但是是往test插入数据，mongo集合没有数据的话就不会被创建

**Comment by ghost** [comment]
> 你创建的test01，但是是往test插入数据，mongo集合没有数据的话就不会被创建

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/58808248/228467217-bf3a1e3f-4cfe-45e1-b5d6-a01161a9e4d4.png">
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/58808248/228467318-18d7dd29-2d14-4eb7-abec-56fba9358b29.png">

**Comment by nick2wang** [comment]
> > 你创建的test01，但是是往test插入数据，mongo集合没有数据的话就不会被创建
> 
> <img alt="image" width="1265" src="https://user-images.githubusercontent.com/58808248/228467217-bf3a1e3f-4cfe-45e1-b5d6-a01161a9e4d4.png">
> 
> <img alt="image" width="1219" src="https://user-images.githubusercontent.com/58808248/228467318-18d7dd29-2d14-4eb7-abec-56fba9358b29.png">

参考文档安装mongo驱动
https://github.com/hhyo/archery/wiki/manual
