### ISSUE TITLE
django 使用4.1.3版本出现：'WSGIRequest' object has no attribute 'is_ajax'的问题

### ISSUE THREAD

**Issue by lushou** [hhyo/archer#2100]
### 重现步骤

1. 没有权限的人进行配置config问题出现如下报错：'WSGIRequest' object has no attribute 'is_ajax'

### 预期外的结果

修改common/utils/permission.py 中的 if request.is_ajax() 字段修改成if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':即可

### 日志文本

```shell
修改common/utils/permission.py 中的 if request.is_ajax() 字段修改成if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':即可
```

### 版本

1.9.1

### 部署方式

K8S

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

修改common/utils/permission.py 中的 if request.is_ajax() 字段修改成if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':即可

**Comment by LeoQuote** [comment]
请直接提 pr ,谢谢

**Comment by nick2wang** [comment]
该问题已经修复过，请尝试最新版本 #1896
