### ISSUE TITLE
mysql8 建表报 Unknown character set: 'utf8mb3'

### ISSUE THREAD

**Issue by gnufree** [hhyo/archer#2101]
### 重现步骤

通过archery 提交建表语句，执行sql检测报Unknown character set: 'utf8mb3'

mysql 8 实例默认是utf8mb3，已经修改为utf8mb4 ，执行还是报这个错误，修改了goinception-config 配置文件，内容如下
support_charset="utf8,utf8mb3,utf8mb4"  问题依旧

### 预期外的结果

![image](https://user-images.githubusercontent.com/6280167/228743570-8d281a7d-003e-46f5-81d9-0642774f2a7d.png)

### 版本

1.9.0

### 部署方式

K8S

**Comment by gnufree** [comment]
goinception 版本太低导致，升级到1.3.0-68 以上，问题解决。

**Comment by ssklkmije07** [comment]
> goinception 版本太低导致，升级到1.3.0-68 以上，问题解决。

请问具体的升级操作是怎样的，我是docker安装的

**Comment by FSerKevin** [comment]
> goinception 版本太低导致，升级到1.3.0-68 以上，问题解决。

同样问题，已按照提供方法解决 抱拳

**Comment by FSerKevin** [comment]
> goinception 版本太低导致，升级到1.3.0-68 以上，问题解决。

我发现升级goinception解决了建表的utf8mb3问题，但是在修改表内容的检测时也出现了utf8mb3报错，请问有遇到吗？

**Comment by caicai19900921** [comment]
1.3.0-68的镜像在哪里下载到的呢？
