### ISSUE TITLE
archery listen unix socket file already in use

### ISSUE THREAD

**Issue by hawkwean** [hhyo/archer#2124]
### 重现步骤

1、在archery上对大表执行 “alter table xx.xx engine=innodb”, 后面被人终止（而非暂停）
2、再次创建工单执行 alter table xx.xx engine=innodb ， 提示  listen unix socket file already in use

### 预期外的结果

![image](https://user-images.githubusercontent.com/40604332/232950757-90a56c15-6ccf-45c0-9ff3-b056191dd969.png)

### 版本

1.8.5

### 部署方式

手工部署

**Comment by hhyo** [comment]
可以升级goinception试试，历史版本对于这个文件清理存在问题
