### ISSUE TITLE
v1.9.1更改域名后 sql审核时报CSRF cookie not set

### ISSUE THREAD

**Issue by smallhorsegg** [hhyo/archer#2169]
### 重现步骤

v1.9.1 更改域名后 sql检测时报CSRF cookie not set

但是已经加了环境变量CSRF_TRUSTED_ORIGINS=xxx  以及修改local_setting.py中的CSRF_TRUSTED_ORIGINS值为新域名

### 预期外的结果

sql检测异常
![image](https://github.com/hhyo/Archery/assets/49267785/61ed2f36-2f2a-4672-86e1-25e87fe1c5a9)

### 版本

1.9.1

### 部署方式

K8S

**Comment by peng19832** [comment]
https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins
@smallhorsegg 
你应该遇到的这个问题吧

**Comment by jingj38765** [comment]
老哥你配置域名后第一次登录没有报forbidden吗。我一直都报错
