### ISSUE TITLE
v1.9.1配置域名访问登录后报403

### ISSUE THREAD

**Issue by jingj38765** [hhyo/archer#2174]
### 重现步骤

1.ng配置
![image](https://github.com/hhyo/Archery/assets/131346123/eefda100-fb1a-4af2-86ae-79d225eacb3b)
![image](https://github.com/hhyo/Archery/assets/131346123/b49059b1-3e04-4ae4-a125-6e4a44997a0d)

2.settings.py已经添加如下配置
![image](https://github.com/hhyo/Archery/assets/131346123/c67da3a3-b840-4fca-989d-be38d3bd454a)

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/131346123/5529ab42-a8cd-4598-9b88-cf40c8cdbff3)

### 日志文本

```shell
无报错
ng有报403
"POST /authenticate/ HTTP/1.1" 403 619 "https://sql-uat.haiermoney.com/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
```

### 版本

1.9.1

### 部署方式

Docker

**Comment by Zerek-Cheng** [comment]
```conf
server {
    listen 80;
    if ($scheme = http ) {
      return 301 https://$host$request_uri;
    }
    location / {
        add_header Access-Control-Allow-Origin *;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Connection Keep-Alive;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:9123$request_uri;
    }
}
```
没写setting.py, 用起来一切正常

**Comment by hbzhu** [comment]
@jingj38765 我的情况和你类似，修改下和docker-compose.yml同级的 .env文件里配置

CSRF_TRUSTED_ORIGINS=http://127.0.0.1:9123  这个修改为你的域名即可

**Comment by cqqxx** [comment]
我和你的问题一样，你解决了吗？跪求解决方式

**Comment by hbzhu** [comment]
@cqqxx 我是修改了，docker-compose.yml同级的 .env文件里配置

把这个配置  CSRF_TRUSTED_ORIGINS=http://127.0.0.1:9123/   修改为你Archery的域名

**Comment by Axm11** [comment]
> @cqqxx 我是修改了，docker-compose.yml同级的 .env文件里配置
> 
> 把这个配置 CSRF_TRUSTED_ORIGINS=http://127.0.0.1:9123/ 修改为你Archery的域名

请问下修改了后如何生效呢，我docker-compose重启了查看容器的env，还是用的127.0.0.1:9123
