### ISSUE TITLE
项目大佬啥时出新版本呢，特别是对mongo 的支持

### ISSUE THREAD

**Issue by liujiashun0520** [hhyo/archer#2185]
### 重现步骤

项目大佬啥时出新版本呢，特别是对mongo 的支持

### 预期外的结果

项目大佬啥时出新版本呢，特别是对mongo 的支持

### 版本

1.8.4

### 部署方式

Docker

**Comment by fancy-lee** [comment]
需要什么方面的支持？

**Comment by ghost** [comment]
> 需要什么方面的支持？

mongodb创建索引失败，mongodb添加注释后无法提交工单

**Comment by fancy-lee** [comment]
mongo什么版本创建索引失败？发自我的 iPhone在 2023年7月4日，14:56，ysk1017 ***@***.***> 写道：﻿

需要什么方面的支持？

mongodb创建索引失败，mongodb添加注释后无法提交工单

**Comment by linhuih** [comment]
#2403   mongodb添加注释 （即标准的// 开头的注释）提交，工单检查已经做了处理了。可以正常提交
