### ISSUE TITLE
mysql工单执行没有备份信息

### ISSUE THREAD

**Issue by solon-liu** [hhyo/archer#2186]
### 重现步骤

执行MYSQL的修改数据SQL工单，选择了备份，最后工单执行完成没有备份信息，如图所示。

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/24712997/12b4a88c-73aa-44e4-a471-cb7647d4999f)

![image](https://github.com/hhyo/Archery/assets/24712997/3795ae05-9bcc-4157-a556-7db46deea79f)

### 日志文本

```shell
无报错信息
```

### 版本

1.9.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MYSQL版本：5.7
binlog为ROW模式

**Comment by solon-liu** [comment]
![image](https://github.com/hhyo/Archery/assets/24712997/36a96442-06f5-4676-998c-3c29feddc55a)
mysql有这个报错有关系吗，但是我看mysql实例是正常的，SQL平台其他功能也是正常使用。就是mysql的工单没有找不到回滚信息

**Comment by solon-liu** [comment]
目标端数据库用户权限为gran all超级权限，binlog相关参数设置检查都满足条件row+full，archery/goinception/mysql日志都没有报错，为啥就是没有生产回滚的脚本信息呢。。。大佬救命呀

**Comment by hhyo** [comment]
问题可复现吗？参考文档看看库里面是否有相关信息https://hanchuanchuan.github.io/goInception/zh/backup.html#%E5%A4%87%E4%BB%BD%E5%8A%9F%E8%83%BD%E5%86%99%E5%85%A5%E8%A7%84%E5%88%99

**Comment by solon-liu** [comment]
可复现，我每次提交的工单都没有回滚信息。

数据库里有相关的库和表：
mysql> select database();
+------------------------+
| database()             |
+------------------------+
| 10_28_8_231_3306_dbmgr |
+------------------------+
1 row in set (0.00 sec)

mysql> show tables;
+------------------------------------+
| Tables_in_10_28_8_231_3306_dbmgr   |
+------------------------------------+
| $_$inception_backup_information$_$ |
| u1                                 |
+------------------------------------+
2 rows in set (0.00 sec)

备份表里有最新的SQL执行信息：
mysql> select * from $_$inception_backup_information$_$  order by time  desc limit 1\G
*************************** 1. row ***************************
        opid_time: 1687080185_4107833_00000001
start_binlog_file: 
 start_binlog_pos: 0
  end_binlog_file: 
   end_binlog_pos: 0
    sql_statement: update u1 set remark=\'16\' where id = 1
             host: 10.28.8.231
           dbname: dbmgr
        tablename: u1
             port: 3306
             time: 2023-06-18 17:23:05
             type: UPDATE

这里面没有生成回滚信息：
mysql> select * from u1;
+----+---------------------------------------------------------------+-----------------------------+
| id | rollback_statement                                            | opid_time                   |
+----+---------------------------------------------------------------+-----------------------------+
|  1 | DROP TABLE `dbmgr`.`U1`;                                      | 1686386798_4034339_00000001 |
|  2 | ALTER TABLE `dbmgr`.`u1` MODIFY COLUMN `REMARK` varchar(100); | 1686387180_4034385_00000001 |
+----+---------------------------------------------------------------+-----------------------------+
2 rows in set (0.00 sec)

**Comment by hhyo** [comment]
可以调整goinception的日志等级为debug试试，会有相关备份信息输出

**Comment by solon-liu** [comment]
![image](https://github.com/hhyo/Archery/assets/24712997/180f082e-c615-4713-badc-f83bdea6e2fa)
这里面可以看出来有效的信息吗

**Comment by solon-liu** [comment]
![image](https://github.com/hhyo/Archery/assets/24712997/84335821-db74-4371-841e-942d854196bd)
没有回滚信息的是这种debug信息

**Comment by solon-liu** [comment]
![image](https://github.com/hhyo/Archery/assets/24712997/d86ccd0b-5360-43fd-ba28-b2d71f4e3542)
已找到原因，配置文件里指定复制库，新建的库没有写binlog。。。
