### ISSUE TITLE
archery不支持goinception开启认证？

### ISSUE THREAD

**Issue by lx308033262** [hhyo/archer#2196]
### 重现步骤

把goinception打开认证后（不做认证有安全风险）

### 预期外的结果

archery连接goinception失败，archery里面没有配置goinception用户名密码的地方

### 日志文本

```shell
我手动修改了源文件，后续踩坑的人请照此修改

/opt/archery/common/check.py  52行添加用户名密码
/opt/archery/sql/engines/goinception.py  30和36行添加用户名密码
```

### 版本

v1.8.5

### 部署方式

Docker

**Comment by LeoQuote** [comment]
麻烦提个pr 吧, 谢谢

**Comment by calvin2020** [comment]
你好，你改了之后在哪里配置呢？我不想升级，按照你的方法改了，但是页面上没看到对应配置项

**Comment by calvin2020** [comment]
> 麻烦提个pr 吧, 谢谢

能帮忙确认改了哪些地方吗？改动大吗？

**Comment by calvin2020** [comment]
改动地方:/opt/archery/common/check.py 
/opt/archery/sql_api/views.py
/opt/archery/common/templates/config.html
/opt/archery/sql/engines/goinception.py
我的版本是1.8.1
