### ISSUE TITLE
不支持无用户密码的 redis 实例

### ISSUE THREAD

**Issue by kdyq007** [hhyo/archer#2223]
### 重现步骤

创建无用户密码的 redis 实例

### 预期外的结果

打开任何相关页面就会弹窗：
int() argument must be a string, a bytes-like object or a number, not 'list'

### 版本

1.9.1

### 部署方式

Docker

**Comment by ouyangxudu** [comment]
我的有密码的一些redis 实例也有类似问题，有些实例不会。V 1.9.1 Docker 方式部署
<img width="426" alt="image" src="https://github.com/hhyo/Archery/assets/22606068/f290f148-d475-4dad-b26c-2b15fdbf0a1c">
