### ISSUE TITLE
PG数据库查询jsonb字段不展示数据

### ISSUE THREAD

**Issue by wang-fu-jie** [hhyo/archer#2234]
### 重现步骤

1、SQL查询在线查询
2、select * from test;
3、其中test表中 jsonb 类型的字段数据不展示，显示均未[object, object]

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/36260353/79fefbd2-e6ab-4c93-a24a-b332cf585f4c)

### 版本

1.9.1

### 部署方式

手工部署

**Comment by wuxingwang1997** [comment]
楼主解决了吗
