### ISSUE TITLE
Archery中sql上线语句无法识别事务执行

### ISSUE THREAD

**Issue by a8159236** [hhyo/archer#2235]
### 重现步骤

1、sql语句中通过事务执行会报错，提示不支持的语法类型。

### 预期外的结果

1、sql语句中通过事务执行会报错，提示不支持的语法类型。
![事务](https://github.com/hhyo/Archery/assets/32159630/e33ce0c7-7641-4897-9121-5c83d7e3eebc)

### 版本

1.9.1

### 部署方式

Docker

**Comment by ahululu** [comment]
遇到了同样的问题，咋解决的
