### ISSUE TITLE
在线体验新版本 需要google 二段验证,如何输入otp 验证码

### ISSUE THREAD

**Issue by thomasgogo** [hhyo/archer#2237]
### 重现步骤

在线体验新版本 需要google 二段验证,如何输入otp 验证码

### 预期外的结果

<img width="472" alt="image" src="https://github.com/hhyo/Archery/assets/3013733/2bea085c-6f2f-4c06-8553-d0b7d0e47473">

### 版本

1.9.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

请问一下,如何解决? 谢谢.

**Comment by fansi404** [comment]
我也同样遇到该问题，在线体验账号密码都是 archer，在线体验地址是：[https://demo.archerydms.com/](https://demo.archerydms.com/)

**Comment by hhyo** [comment]
已处理
