### ISSUE TITLE
从1.9.1升级到1.10.0pg数据库无法使用

### ISSUE THREAD

**Issue by leon1208** [hhyo/archer#2251]
### 重现步骤

按步骤从1.9.1升级到1.10.0

### 预期外的结果

原有配置可用的pg数据库实例全部都不能使用

### 版本

1.10.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

默认setting文件里的ENABLED_ENGINES和AVAILABLE_ENGINES变量中的pgsql写错了，写成了pqsql。

**Comment by LeoQuote** [comment]
~~麻烦提个 pr 吧~~ 谢谢, pr 已提, 同时你可以自己修改 settings.py , 或者使用 docker-compose 文件夹中的 archery/settings.py 文件, 覆盖错误的配置

**Comment by feiazifeiazi** [comment]
擦。 预期是pgsql, 结果写成了 pqsql。 我说呢。咋连不上PG。
