### ISSUE TITLE
使用oracle数据库的在线查询报错 bind variables are not supported in DDL statements

### ISSUE THREAD

**Issue by leon1208** [hhyo/archer#2252]
### 重现步骤

1.选择在线查询
2.选择一个oracle实例
3.选择任何一个schema报错

### 预期外的结果

cx_Oracle.DatabaseError: DPI-1059: bind variables are not supported in DDL statements
ALTER SESSION SET CURRENT_SCHEMA = 'xxxx' 属于DDL语句，不支持bind variables

### 版本

1.10.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

oracle.py中的594和673行

**Comment by LeoQuote** [comment]
如果知道修正方式的话, 欢迎 pr

**Comment by SoHuDrgon** [comment]
俺也遇到了，求大佬解决一下！

**Comment by SoHuDrgon** [comment]
我把oracle.py中的594和673行的配置改成下面的：
" ALTER SESSION SET CURRENT_SCHEMA = my_db_name "
我就能查了，不知道啥原理！啊哈哈哈哈！

**Comment by tonyhu214** [comment]
@SoHuDrgon @leon1208 @LeoQuote  我们可以使用connection.current_schema=db_name代替 cursor.execute(f' ALTER SESSION SET CURRENT_SCHEMA = "{db_name}" ')

**Comment by tonyhu214** [comment]
@LeoQuote

**Comment by SoHuDrgon** [comment]
好的，谢谢大佬！

**Comment by SoHuDrgon** [comment]
@tonyhu214 不行啊大佬，改了还是报错！
![截屏2023-08-24 11 28 01](https://github.com/hhyo/Archery/assets/11847516/c0ca8121-6f66-441d-932d-be0140fb460f)
下面是报错：
![截屏2023-08-24 11 27 33](https://github.com/hhyo/Archery/assets/11847516/75bd3a11-3825-4b79-b32e-0eae4217a886)
注释的就可以运行！

**Comment by tonyhu214** [comment]
@SoHuDrgon  oracle.py 文件里面有2行该内容

**Comment by SoHuDrgon** [comment]
@tonyhu214 对啊，我两个都改了的，但是还是不行的。
![截屏2023-08-25 14 24 49](https://github.com/hhyo/Archery/assets/11847516/39f06d71-1166-44a4-8eab-feb1c066e6be)
![截屏2023-08-25 14 25 14](https://github.com/hhyo/Archery/assets/11847516/f0143a26-6495-4c84-a012-6f1a3f2766d1)
这我肯定不是骗你的啊！
![截屏2023-08-25 14 26 24](https://github.com/hhyo/Archery/assets/11847516/647205aa-9180-4277-8436-9a1c082ee08d)

**Comment by SoHuDrgon** [comment]
@tonyhu214  我使用archery 1.9.1和1.10.0两个镜像测试都是不能查询的。

**Comment by tonyhu214** [comment]
@SoHuDrgon  docker 部署的吗？docker部署的话需要重启容器生效。如果不是docker部署，或许可能是cx-Oracle包的版本问题。pip list installed 看下版本。我的是7.3.0的

**Comment by SoHuDrgon** [comment]
@tonyhu214 
[root@6ad46cb19670 archery]# cd /opt/archery
[root@6ad46cb19670 archery]# source /opt/venv4archery/bin/activate
(venv4archery) [root@6ad46cb19670 archery]# pip3 list installed
Package                       Version
----------------------------- -----------

**### cx-Oracle                     7.3.0**

**Comment by SoHuDrgon** [comment]
@tonyhu214 麻烦问一下，docker启动的archery加载的oracle.py文件是镜像里面的么，还是从外部挂载的？

**Comment by SoHuDrgon** [comment]
好了，谢谢大佬！

**Comment by hsjz81** [comment]
**Archery-1.10.0报错解决**

**1、django对应错误**
[2024-01-22 18:21:05,903][Thread-5203:140229134350080][task_id:default][oracle.py:700][WARNING]- Oracle 语句执行报错，语句：SELECT table_name 
        FROM all_tables 
        WHERE nvl(tablespace_name, 'no tablespace') NOT IN ('SYSTEM', 'SYSAUX') 
        AND OWNER = :db_name AND IOT_NAME IS NULL 
        AND DURATION IS NULL order by table_name，错误信息Traceback (most recent call last):
  File "/app/Archery-1.10.0/sql/engines/oracle.py", line 672, in query
    cursor.execute(
cx_Oracle.DatabaseError: DPI-1059: bind variables are not supported in DDL statements

2024-01-22 18:21:05,903 - default - WARNING - Oracle 语句执行报错，语句：SELECT table_name 
        FROM all_tables 
        WHERE nvl(tablespace_name, 'no tablespace') NOT IN ('SYSTEM', 'SYSAUX') 
        AND OWNER = :db_name AND IOT_NAME IS NULL 
        AND DURATION IS NULL order by table_name，错误信息Traceback (most recent call last):
  File "/app/Archery-1.10.0/sql/engines/oracle.py", line 672, in query
    cursor.execute(
cx_Oracle.DatabaseError: DPI-1059: bind variables are not supported in DDL statements

**2、修改Archery-1.10.0/sql/engines/oracle.py**
注释掉
                 cursor.execute(
                     f" ALTER SESSION SET CURRENT_SCHEMA = :db_name ",
                     {"db_name": db_name},
                 )
增加conn.current_schema=db_name
测试验证问题已解决，感谢楼上大侠

具体行数位置


 586     def explain_check(self, db_name=None, sql="", close_conn=False):
 587         # 使用explain进行支持的SQL语法审核，连接需不中断，防止数据库不断fork进程的大批量消耗
 588         result = {"msg": "", "rows": 0}
 589         try:
 590             conn = self.get_connection()
 591             cursor = conn.cursor()
 592             if db_name:
 593                 #cursor.execute(
 594                 #    f" ALTER SESSION SET CURRENT_SCHEMA = :db_name ",
 595                 #    {"db_name": db_name},
 596                 #)
 597                 #解决cx_Oracle.DatabaseError: DPI-1059: bind variables are not supported in DDL statements报错
                        conn.current_schema=db_name

 658     def query(
 659         self,
 660         db_name=None,
 661         sql="",
 662         limit_num=0,
 663         close_conn=True,
 664         parameters=None,
 665         **kwargs,
 666     ):
 667         """返回 ResultSet"""
 668         result_set = ResultSet(full_sql=sql)
 669         try:
 670             conn = self.get_connection()
 671             cursor = conn.cursor()
 672             if db_name:
 673                 #cursor.execute(
 674                 #    " ALTER SESSION SET CURRENT_SCHEMA = :db_name ",
 675                 #    {"db_name": db_name},
 676                 #)
 677                 #解决cx_Oracle.DatabaseError: DPI-1059: bind variables are not supported in DDL statements报错
 678                 conn.current_schema=db_name
 679             sql = sql.rstrip(";")

**Comment by xkyang1** [comment]
good !
