### ISSUE TITLE
从页面导出大量数据会卡死

### ISSUE THREAD

**Issue by xiangshen123** [hhyo/archer#2255]
### 重现步骤

执行sql后点击导出

### 预期外的结果

浏览器直接会卡很久

### 版本

1.9.1

### 部署方式

Docker

**Comment by h31105** [comment]
确实，部分情况下换格式**可能可以**解决

**Comment by houyuelong15** [comment]
请问下这个如何解决？

**Comment by Belee05** [comment]
1.11.3遇到同样的问题
