### ISSUE TITLE
执行修改视图报错

### ISSUE THREAD

**Issue by caicai19900921** [hhyo/archer#2259]
### 重现步骤

使用如下语句修改视图报错
ALTER VIEW test_all_info AS
SELECT
  `info`.`id` AS `id`,
  `info`.`title` AS `title`,
  `info`.`sppic` AS `sppic`,
  `info`.`spprice` AS `spprice`,
  `info`.`link` AS `link`,
  `info`.`pinpai` AS `pinpai`,
  `info`.`pinpaiid` AS `pinpaiid`,
  `info`.`fenlei` AS `fenlei`,
  `info`.`fenleiid` AS `fenleiid`,
  `info`.`spuid` AS `spuid`,
  `info`.`spbh` AS `spbh`,
  `info`.`current_price` AS `current_price`,
  `info`.`act_type` AS `act_type`,
  `info`.`act_url` AS `act_url`,
  `info`.`act_info` AS `act_info`,
  `info`.`act_price` AS `act_price`,
  `info`.`act_dis_info_Json` AS `act_dis_info_Json`,
  `info`.`act_starttime` AS `act_starttime`,
  `info`.`act_endtime` AS `act_endtime`,
  `info`.`is_presale` AS `is_presale`,
  `info`.`presale_starttime` AS `presale_starttime`,
  `info`.`sources` AS `sources`,
  `info`.`sourcesLink` AS `sourcesLink`,
  `info`.`tjyy` AS `tjyy`,
  `info`.`sale_type` AS `sale_type`,
  `info`.`grade` AS `grade`,
  `info`.`count_view` AS `count_view`,
  `info`.`count_comment` AS `count_comment`,
  `info`.`count_click` AS `count_click`,
  `info`.`count_zhi` AS `count_zhi`,
  `info`.`count_buzhi` AS `count_buzhi`,
  `info`.`count_qzsort` AS `count_qzsort`,
  `info`.`insert_time` AS `insert_time`,
  `info`.`modify_time` AS `modify_time`,
  `info`.`tag_price` AS `tag_price`,
  `info`.`tag_shop_openshop_time` AS `tag_shop_openshop_time`,
  `info`.`tag_shop_fans` AS `tag_shop_fans`,
  `info`.`tag_shop_score` AS `tag_shop_score`,
  `info`.`tag_pinpai` AS `tag_pinpai`,
  `info`.`tag_sku_comment` AS `tag_sku_comment`,
  `info`.`tag_sku_score` AS `tag_sku_score`,
  `info`.`tag_site_type` AS `tag_site_type`,
  `info`.`tag_youhui_type` AS `tag_youhui_type`,
  `info`.`tag_presale_type` AS `tag_presale_type`,
  `info`.`tag_activity_channel` AS `tag_activity_channel`,
  `info`.`tag_member` AS `tag_member`,
  `info`.`tag_salecount_d30` AS `tag_salecount_d30`,
  `info`.`tag_salecount_h24` AS `tag_salecount_h24`,
  `info`.`order_quantity` AS `order_quantity`,
  `info`.`order_money` AS `order_money`,
  `info`.`RecommendUserName` AS `RecommendUserName`,
  `info`.`Level` AS `Level`,
  `info`.`IsConvertUrl` AS `IsConvertUrl`,
  `info`.`SuggestLevel` AS `SuggestLevel`,
  `info`.`qgmCount` AS `qgmCount`,
  `info`.`Type` AS `Type`,
  `info`.`update_zhekouid` AS `update_zhekouid`,
  `info`.`update_sqkid` AS `update_sqkid`,
  `info`.`update_count_datetime` AS `update_count_datetime`,
  `info`.`Platform` AS `Platform`,
  `info`.`Operator` AS `Operator`,
  `info`.`OperatorStatus` AS `OperatorStatus`,
  `info`.`Status` AS `Status`,
  `info`.`SiteId` AS `SiteId`,
  `info`.`RecommendTime` AS `RecommendTime`,
  `info`.`CollectSource` AS `CollectSource`,
  `info`.`RedirectUrl` AS `RedirectUrl`,
  `info`.`CreatedTime` AS `CreatedTime`,
  `info`.`Is_Fanli` AS `Is_Fanli`,
  `info`.`Is_Qsk` AS `Is_Qsk`,
  `info`.`SiteName` AS `SiteName`,
  `info`.`ShopId` AS `ShopId`,
  `info`.`webTags` AS `webTags`,
  `info`.`OperationTags` AS `OperationTags`,
  `info`.`PublishUser` AS `PublishUser`,
  `info`.`PriceApprove` AS `PriceApprove`,
  `info`.`SourceType` AS `SourceType`,
  `info`.`IsApprove` AS `IsApprove`,
  `info`.`ProductCount` AS `ProductCount`,
  `info`.`is_Allowance_Show` AS `is_Allowance_Show`,
  `info`.`HistoryLevel` AS `HistoryLevel`,
  `info`.`HistoryLevelInfo` AS `HistoryLevelInfo`,
  `info`.`IsCabbagePriceTag` AS `IsCabbagePriceTag`,
  `info`.`FinalLevel` AS `FinalLevel`,
  `info`.`navTag` AS `navTag`,
  `info`.`InitialLevel` AS `InitialLevel`,
  `info`.`SourceTag` AS `SourceTag`,
  `info`.`channelLv` AS `channelLv`,
  `info`.`card_link` AS `card_link`,
  `info`.`updateTime` AS `updateTime`,
  `info`.`startTime` AS `startTime`,
  `info`.`rating_worthy_num` AS `rating_worthy_num`,
  `info`.`rating_unworthy_num` AS `rating_unworthy_num`,
  `info`.`is_xbqr` AS `is_xbqr`,
  `info`.`couponlist` AS `couponlist`,
  `info`.`spbh_old` AS `spbh_old`,
  `info`.`disCount` AS `disCount`,
  `info`.`HistoryPriceInfo` AS `HistoryPriceInfo`,
  `info`.`disCount_v2` AS `disCount_v2`,
  `info`.`webTags_json` AS `webTags_json`,
  `info`.`Commission` AS `Commission`,
  `info`.`extra_mkt_id` AS `extra_mkt_id`,
  `info`.`is_delete` AS `is_delete`,
  `extension`.`is_auto_grant_hot_reward` AS `is_auto_grant_hot_reward`,
  `extension`.`is_auto_add_audit_reward` AS `is_auto_add_audit_reward`,
  `extension`.`is_auto_global_convert_link` AS `is_auto_global_convert_link`,
  `extension`.`is_show_app` AS `is_show_app`,
  `extension`.`is_show_pc` AS `is_show_pc`,
  `extension`.`is_show_mobile` AS `is_show_mobile`,
  `extension`.`video_image` AS `video_image`,
  `extension`.`video` AS `video`,
  `extension`.`buy_quantity` AS `buy_quantity`,
  `extension`.`float_image` AS `float_image`,
  `extension`.`mini_program_appid` AS `mini_program_appid`,
  `extension`.`mini_program_username` AS `mini_program_username`,
  `extension`.`mini_program_link` AS `mini_program_link`,
  `extension`.`order_image` AS `order_image`,
  `extension`.`modify_user` AS `modify_user`,
  `extension`.`push_user` AS `push_user`,
  `extension`.`audit_time` AS `audit_time`,
  `extension`.`push_time` AS `push_time`,
  `extension`.`origin_type` AS `origin_type`,
  `extension`.`origin_channel` AS `origin_channel`,
  `extension`.`presale_end_time` AS `presale_end_time`,
  `extension`.`is_bybt` AS `is_bybt`,
  `extension`.`pic_focus` AS `pic_focus`,
  `extension`.`is_first` AS `is_first`,
  `extension`.`product_describe` AS `product_describe`,
  `extension`.`push_source` AS `push_source`,
  `extension`.`is_tjyy_step_baoliao` AS `is_tjyy_step_baoliao`,
  `extension`.`vest_by` AS `vest_by`
FROM
  (
    `test_info` `info`
    LEFT JOIN `test_extension` `extension` ON ((`info`.`id` = `extension`.`id`))
  )

### 预期外的结果

SQL检测时报如下错误
line 1 column 38 near "VIEW test_all_info AS
SELECT
`info`.`id` AS `id`,
`info`.`title` AS `title`,
`info`.`sppic` AS `sppic`,
`info`.`spprice` AS `spprice`,
`info`.`link` AS `link`,
`info`.`pinpai` AS `pinpai`,
`info`.`pinpaiid` AS `pinpaiid`,
`info`.`fenlei` AS `fenlei`,
`info`.`fenleiid` AS `fenleiid`,
`info`.`spuid` AS `spuid`,
`info`.`spbh` AS `spbh`,
`info`.`current_price` AS `current_price`,
`info`.`act_type` AS `act_type`,
`info`.`act_url` AS `act_url`,
`info`.`act_info` AS `act_info`,
`info`.`act_price` AS `act_price`,
`info`.`act_dis_info_Json` AS `act_dis_info_Json`,
`info`.`act_starttime` AS `act_starttime`,
`info`.`act_endtime` AS `act_endtime`,
`info`.`is_presale` AS `is_presale`,
`info`.`presale_starttime` AS `presale_starttime`,
`info`.`sources` AS `sources`,
`info`.`sourcesLink` AS `sourcesLink`,
`info`.`tjyy` AS `tjyy`,
`info`.`sale_type` AS `sale_type`,
`info`.`grade` AS `grade`,
`info`.`count_view` AS `count_view`,
`info`.`count_comment` AS `count_comment`,
`info`.`count_click` AS `count_click`,
`info`.`count_zhi` AS `count_zhi`,
`info`.`count_buzhi` AS `count_buzhi`,
`info`.`count_qzsort` AS `count_qzsort`,
`info`.`insert_time` AS `insert_time`,
`info`.`modify_time` AS `modify_time`,
`info`.`tag_price` AS `tag_price`,
`info`.`tag_shop_openshop_time` AS `tag_shop_openshop_time`,
`info`.`tag_shop_fans` AS `tag_shop_fans`,
`info`.`tag_shop_score` AS `tag_shop_score`,
`info`.`tag_pinpai` AS `tag_pinpai`,
`info`.`tag_sku_comment` AS `tag_sku_comment`,
`info`.`tag_sku_score` AS `tag_sku_score`,
`info`.`tag_site_type` AS `tag_site_type`,
`info`.`tag_youhui_type` AS `tag_youhui_type`,
`info`.`tag_presale_type` AS `tag_presale_type`,
`info`.`tag_activity_channel` AS `tag_activity_channel`,
`info`.`tag_member` AS `tag_member`,
`info`.`tag_salecount_d30` AS `tag_salecount_d30`,
`info`.`tag_salecount_h24` AS `tag_salecount_h24`,
`info`.`order_quantity` AS `order_quantity`,
`info`.`order_money` AS `order_money`,
`info`.`Recom" (total length 5725)

goinception容器报错如下

### 版本

1.9.1

### 部署方式

Docker

**Comment by caicai19900921** [comment]
goinception的日志截图
![image](https://github.com/hhyo/Archery/assets/32893009/7dc56aa9-8b1d-415f-bdb6-e3927588e5ba)

**Comment by LeoQuote** [comment]
不属于archery错误如有需要请去goinception 提issue
