### ISSUE TITLE
工单对oracle 建表不成功

### ISSUE THREAD

**Issue by tonyhu214** [hhyo/archer#2262]
### 重现步骤

1. oracle 建表建表sql如下
create table TEST (id NUMBER(22))，SQL检测功能不报错。无检测结果。
sql执行不报错，无表生成

### 预期外的结果

修复bug

### 日志文本

```shell
archery.log：[2023-08-24 11:28:08,813][MainThread:140489988859712][task_id:default][oracle.py:1068][WARNING]- Oracle 语句执行报错，第1个SQL：create table TEST (id NUMBER(22))，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/oracle.py", line 875, in execute_check
    if result_set["rows"] > 1000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

### 版本

1.10.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

cx-oracle：7.3.0
goInception: v1.2.5

**Comment by SoHuDrgon** [comment]
@tonyhu214 我依照你的修复代码修改了，但是还是建表不成功。
![截屏2023-08-25 14 41 56](https://github.com/hhyo/Archery/assets/11847516/785c8649-6abb-4b73-9165-f156125cb541)
![截屏2023-08-25 14 42 55](https://github.com/hhyo/Archery/assets/11847516/ca4b6374-cf78-4901-8630-910ca0e828c0)
![截屏2023-08-25 14 43 18](https://github.com/hhyo/Archery/assets/11847516/2761ddd9-9545-4178-a165-c45c4d46d836)
![截屏2023-08-25 14 40 43](https://github.com/hhyo/Archery/assets/11847516/654e7f85-4ff2-4fb4-9ff6-019296613a24)
![截屏2023-08-25 14 41 00](https://github.com/hhyo/Archery/assets/11847516/41e61838-52a6-47e4-bf67-80f2b823fb37)
![截屏2023-08-25 14 41 32](https://github.com/hhyo/Archery/assets/11847516/d7cb63bb-bc9a-40d1-81e1-ac3079921eaa)

**我的oracle版本是11.2.0.4**

**Comment by SoHuDrgon** [comment]
报错信息如下：
`[2023-08-25 14:40:31,101][MainThread:139725906945856][task_id:default][oracle.py:1010][WARNING]- Oracle 语句执行报错，第1个SQL：create table AGENT_RECON_ADAPTOR (ID VARCHAR2(32) not null,
                                                  TRANS_DATE CHAR(8) not null,
                                                                     MER_ID VARCHAR2(20) not null,
                                                                                         TXN_TYPE VARCHAR2(4) not null,
                                                                                                              PAY_TYPE VARCHAR2(8) not null,
                                                                                                                                   DC_TYPE VARCHAR2(8),
                                                                                                                                           TXN_AMT NUMBER(15),
                                                                                                                                                   TXN_CNT NUMBER(15),
                                                                                                                                                           FEE_AMT NUMBER(15),
                                                                                                                                                                   CHANNEL_COST NUMBER(15),
                                                                                                                                                                                SETT_AMT NUMBER(15),
                                                                                                                                                                                         PROFIT NUMBER(15),
                                                                                                                                                                                                INSTALMENT_FEE NUMBER(15),
                                                                                                                                                                                                               CLEAR_STAT CHAR(1),
                                                                                                                                                                                                                          REMARK VARCHAR2(128));，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/oracle.py", line 836, in execute_check
    if result_set["rows"] > 1000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

[2023-08-25 14:40:45,652][MainThread:139725906945856][task_id:default][oracle.py:1010][WARNING]- Oracle 语句执行报错，第1个SQL：create table AGENT_RECON_ADAPTOR (ID VARCHAR2(32) not null,
                                                  TRANS_DATE CHAR(8) not null,
                                                                     MER_ID VARCHAR2(20) not null,
                                                                                         TXN_TYPE VARCHAR2(4) not null,
                                                                                                              PAY_TYPE VARCHAR2(8) not null,
                                                                                                                                   DC_TYPE VARCHAR2(8),
                                                                                                                                           TXN_AMT NUMBER(15),
                                                                                                                                                   TXN_CNT NUMBER(15),
                                                                                                                                                           FEE_AMT NUMBER(15),
                                                                                                                                                                   CHANNEL_COST NUMBER(15),
                                                                                                                                                                                SETT_AMT NUMBER(15),
                                                                                                                                                                                         PROFIT NUMBER(15),
                                                                                                                                                                                                INSTALMENT_FEE NUMBER(15),
                                                                                                                                                                                                               CLEAR_STAT CHAR(1),
                                                                                                                                                                                                                          REMARK VARCHAR2(128));，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/oracle.py", line 836, in execute_check
    if result_set["rows"] > 1000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'`

**Comment by tonyhu214** [comment]
@SoHuDrgon  你看你的报错内容
File "/opt/archery/sql/engines/oracle.py", line 836, in execute_check
**if result_set["rows"] > 1000:**  -- 这里不是新的代码哈
TypeError: '>' not supported between instances of 'NoneType' and 'int'`
是不是docker部署的，是的话需要重新启动容器

**Comment by SoHuDrgon** [comment]
都重新启动了容器了的！我也纳闷为啥是836行！

**Comment by tonyhu214** [comment]
或许check /opt/archery/sql/engines/oracle.py 下，然后docker container  stop archery 等2分钟 docker container   start archery

**Comment by SoHuDrgon** [comment]
好了，谢谢大佬！

**Comment by yangjule126** [comment]
将sql/engines/oracle.py 866行及895号改为：
if result_set["rows"] is not None and result_set["rows"] > 1000:

再重启项目

**Comment by LeoQuote** [comment]
> 将sql/engines/oracle.py 866行及895号改为： if result_set["rows"] is not None and result_set["rows"] > 1000:
> 
> 再重启项目

如果master 还有此 bug ,还请直接提一个pr, 谢谢
