### ISSUE TITLE
可执行时间范围不应该短于60分钟

### ISSUE THREAD

**Issue by Ramboooooooo** [hhyo/archer#2263]
### 重现步骤

1、点击 SQL 上线 + 提交 SQL
2、输入工单标题并选择资源、数据库实例和数据库
3、贴入需要升级的 SQL 脚本
4、选择可执行时间范围
5、点击 SQL 检查，弹出"可执行时间范围不应该短于60分钟"

<img width="1177" alt="image" src="https://github.com/hhyo/Archery/assets/95686017/9d2a6ca8-ef50-4cf5-9822-ff074c62a493">

### 预期外的结果

设置合理的时间成功

### 版本

1.10.1

### 部署方式

Docker

**Comment by hhyo** [comment]
更换谷歌浏览器试试

**Comment by Ramboooooooo** [comment]
经过测试：
正常 -> Chrome - Version：版本 116.0.5845.110（正式版本） (x86_64) 
正常 -> Firefox - Version：116.0.3 (64 位) 
**异常 -> Safari - Version：版本13.1.3 (15609.4.1)**
