### ISSUE TITLE
在执行ddl操作的时候，ghost卡着不动，不迁移数据

### ISSUE THREAD

**Issue by The0necc** [hhyo/archer#2272]
### 重现步骤
![image](https://github.com/hhyo/Archery/assets/31816266/2a351f91-c5df-4091-9d68-4fc5b90ea6d1)

### 预期外的结果

状态是在迁移的状态，但是9分钟了，迁移数据很少

### 日志文本

```shell
无
```

### 版本

1.9

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

无

**Comment by hhyo** [comment]
blacklog队列满了，表本身变更过多或者因为goinception和目标数据库网络延迟过大，增量日志应用不过来
