### ISSUE TITLE
打开系统配置项里面的注册功能，登录页面不显示

### ISSUE THREAD

**Issue by baiyi404** [hhyo/archer#2286]
### 重现步骤

1、登录系统，点击系统管理，选择配置项管理
2、滑到系统配置最下面
3、SIGN_UP_ENABLED设置ON
4、退出登录后，再刷新看不到注册按钮
版本1.10.0

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/72370222/6f809437-8e1b-45ea-82a5-05ff7009ac34)
![image](https://github.com/hhyo/Archery/assets/72370222/5b8df81b-cec6-4650-9173-c6ac50f1f693)

### 日志文本

```shell
日志无，不报错
```

### 版本

1.10.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL8.0

**Comment by LeoQuote** [comment]
确实, 我这边也复现了, 我有空帮你看看, 应该是 https://github.com/hhyo/Archery/pull/2241 误删了,  你要是比较急的话, 可以自己手动改一下, docker 部署的话, 可以改启动脚本, 启动前把提前挂载的文件拷贝过去就行.

**Comment by gaoqiang-0327** [comment]
这新版本前端问题一大堆了已经

**Comment by LeoQuote** [comment]
欢迎pr哈 @gaoqiang-0327

**Comment by baiyi404** [comment]
1.10.0前端还是有问题的，权限申请，点击提交，无法提交，我暂时还是回退了旧版本

**Comment by irisrain** [comment]
一样，请问有解决办法吗
