### ISSUE TITLE
SQL检测 扫描/影响行数 有问题与实际不符

### ISSUE THREAD

**Issue by a8159236** [hhyo/archer#2294]
### 重现步骤

SQL检测 扫描/影响行数 有问题，实际上只有两行数据修改，但是检测结果却显示影响行数有1111行？

### 版本

1.9.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

archery版本 [Release v1.10.0]
安装方式： docker安装
数据库版本：Mysql8.0

**Comment by LeoQuote** [comment]
影响行数完全是 goinception 的返回, 你可以去 goinception 项目提问
