### ISSUE TITLE
普通用户无法查询分区表

### ISSUE THREAD

**Issue by viper-sina-info** [hhyo/archer#2310]
### 重现步骤

select * from user_wallet_log partition(p10);

Error
无法校验查询语句权限，请联系管理员，错误信息：You have an error in your SQL syntax, near 'partition(p10)' at line 1

1.我安装了1.8.3，无法查询分区表
2.看到issue说升级到最新版本试试，然后升级到最新的版本1.10.0，发现还是无法查询

### 预期外的结果

admin和DBA组可以查询分区表

普通用户如果授予
sql | permission | 可查询所在资源组内的所有实例
或者
sql | permission | 可查询所有实例
权限， 就可以查询分区表。

但是普通用户的查询是需要审核才可以查询。不能给这两个权限

### 版本

1.10.0

### 部署方式

手工部署

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL: 5.7.31
Browsers: Chrome
goInception: v1.2.4

**Comment by LeoQuote** [comment]
Duplicate of https://github.com/hhyo/Archery/discussions/1928
