### ISSUE TITLE
审核流配置问题

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#2312]
### 重现步骤

1. A用户，关联A、B、C资源组，给与审核上线sql权限，是A资源组实例的管理员；
2. B用户，也关联有A资源组，有审核上线SQL权限，是B资源组实例的管理员；
3. 各实例所在资源组，都配有审核流。

### 预期外的结果

结果，A可以审核B资源组的上线sql，B也可以A资源组的sql，权限出现了越界呢？
这个审核流，能否有什么方式，让用户只能审核自己管理的实例？
目前，我想到的临时方式是，给每个资源组，各自建立自己的权限组，但这样有点麻烦呢

### 日志文本

```shell
无
```

### 版本

1.8.5

### 部署方式

Docker

**Comment by LeoQuote** [comment]
archery 不存在"资源组的管理员"这个概念, 审批流配置时, 是一个线性的审批流, 审批流的每个节点是一个用户组.

在审批流上的每个用户组都需要有审核上线 SQL 的权限, 这是一个全局权限.

是的, 只有你说的方法可行. 各个资源组建立各自的用户组. 

欢迎 pr

**Comment by lanheader** [comment]
我是给每个资源组创建了一个用户组，定时根据实例列表批量刷新用户组

**Comment by peng19832** [comment]
> archery 不存在"资源组的管理员"这个概念, 审批流配置时, 是一个线性的审批流, 审批流的每个节点是一个用户组.
> 
> 在审批流上的每个用户组都需要有审核上线 SQL 的权限, 这是一个全局权限.
> 
> 是的, 只有你说的方法可行. 各个资源组建立各自的用户组.
> 
> 欢迎 pr

"资源组的管理员"：我的意思是资源组的审核人员
