### ISSUE TITLE
执行一批索引更改语句,提示一直在执行中

### ISSUE THREAD

**Issue by larzwow** [hhyo/archer#2320]
### 重现步骤

执行的很久,并且一直显示在执行中,但我自己去需要执行的库中看,已经是执行完毕了的

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/144202560/be11c4f2-b978-45b7-a33f-20d551fca034)
![image](https://github.com/hhyo/Archery/assets/144202560/13d1fa3c-91d4-4394-be74-bd5c85e6126a)

### 日志文本

```shell
[2023-10-10 09:01:04,538][MainThread:140169163118400][task_id:django-q][signals.py:28][ERROR]- return hook sql.utils.execute_sql.execute_callback failed on [sqlreview-execute-80] because 'errcode'
[2023-10-10 09:15:16,368][MainThread:140169163118400][task_id:django-q][signals.py:28][ERROR]- return hook sql.utils.execute_sql.execute_callback failed on [sqlreview-execute-81] because 'errcode'
```

### 版本

1.10.0

### 部署方式

手工部署

**Comment by larzwow** [comment]
使用python3 manage.py qmonitor 提示:

redis.exceptions.ResponseError: unknown command 'KEYS', with args beginning with: 'django_q:archery:cluster:*'

**Comment by larzwow** [comment]
从archery 数据库发现  sql_workflow 表的workid已经到82, 但是 djanao_q_task 的id 只有81
![image](https://github.com/hhyo/Archery/assets/144202560/62a9ee2f-a888-4185-a8e3-dbe3292cec69)

**Comment by woshiyanghai** [comment]
你的表很大么？

**Comment by larzwow** [comment]
> 你的表很大么？

哪个表呢?

**Comment by larzwow** [comment]
> 你的表很大么？

执行修改索引的表的记录数都是低于50W条以下的

**Comment by woshiyanghai** [comment]
你这种情况我也遇到过，我了解下

**Comment by woshiyanghai** [comment]
从你的描述来看，你和我遇到的问题还不是一样，我是表太大了，长时间更新，最终导致没有更新状态。

**Comment by larzwow** [comment]
> 从你的描述来看，你和我遇到的问题还不是一样，我是表太大了，长时间更新，最终导致没有更新状态。

嗯呢, 我这个后面发现只是页面状态上 显示执行中, 实际已经完成了.

**Comment by woshiyanghai** [comment]
你看看这一行的完整信息
![image](https://github.com/hhyo/Archery/assets/87959621/40f50d1d-7480-4516-af24-24d2a7fcbce9)
这里沟通太慢了

**Comment by woshiyanghai** [comment]
一批sql语句是多少个alter？

**Comment by larzwow** [comment]
> 你看看这一行的完整信息 ![image](https://user-images.githubusercontent.com/87959621/273820249-40f50d1d-7480-4516-af24-24d2a7fcbce9.png) 这里沟通太慢了
![image](https://github.com/hhyo/Archery/assets/144202560/538d5d82-b13c-407c-a9ef-7d8a8dabd0ec)
没有什么有效的信息.

**Comment by larzwow** [comment]
> Contributor



> 一批sql语句是多少个alter？

一个实例。不同的库 每个库3到-6条 一共700个

**Comment by woshiyanghai** [comment]
![image](https://github.com/hhyo/Archery/assets/87959621/5758f454-8fb1-401f-bf6f-12489039f7f4)
 这里查看下然后截图

**Comment by larzwow** [comment]
> ![image](https://user-images.githubusercontent.com/87959621/273827163-5758f454-8fb1-401f-bf6f-12489039f7f4.png) 这里查看下然后截图
![image](https://github.com/hhyo/Archery/assets/144202560/683c449e-5a58-4fa6-841f-9bde5e39060c)
没有82这个audit id的记录

**Comment by woshiyanghai** [comment]
![image](https://github.com/hhyo/Archery/assets/87959621/88bd271b-8e0a-48d9-9089-7c0b1452b1fd)

**Comment by larzwow** [comment]
> ![image](https://user-images.githubusercontent.com/87959621/273829473-88bd271b-8e0a-48d9-9089-7c0b1452b1fd.png)
现在他是已经执行了,但是没有更改sql_workflow对应id的状态,也没有记录日志

**Comment by hbzhu** [comment]
我也遇到类似的情况，执行update数据，一直显示确认中，实际已执行完毕了
