### ISSUE TITLE
release的程序包下不到了

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#2321]
### 重现步骤

release里的v1.10版本下不到了，提示not found

### 预期外的结果

release里的v1.10版本下不到了，提示not found

### 日志文本

```shell
无
```

### 版本

1.10.0

### 部署方式

Docker

**Comment by LeoQuote** [comment]
未复现

**Comment by peng19832** [comment]
> 未复现

@LeoQuote 
大佬，我打开是这样的
![image](https://github.com/hhyo/Archery/assets/9590209/9e3fd3aa-b259-484d-9751-f45b1da0a31d)

**Comment by LeoQuote** [comment]
非 archery 问题, 如有需要请咨询GitHub的支持
