### ISSUE TITLE
v1.10.0存在任意文件读取漏洞

### ISSUE THREAD

**Issue by xiaognag4344** [hhyo/archer#2346]
### 重现步骤

1. POST /sql_analyze/analyze/ HTTP/1.1
![image](https://github.com/hhyo/Archery/assets/38749807/6ec33a4e-e895-465d-8b3b-bd05962fed2f)

### 预期外的结果

存在任意文件读取漏洞

### 版本

v1.10.0

### 部署方式

Docker

**Comment by LeoQuote** [comment]
这块逻辑我看了下, 是前端上传文件, 上传结束后, 后端返回文件地址, 前端再用文件地址请求有 bug 的 api, 这个逻辑是有问题的, 不过修起来需要修前端, 我这边不太熟, 建议你先把功能禁用, 或者直接删除view.

**Comment by LeoQuote** [comment]
看了下, 是 soar 这边既可接受 sql 语句又可接受文件路径导致的, 这块如果说过滤请求, 不是特别好判断是不是真正的 SQL 语句, 我这边做了一个针对性修复, 针对你说的读取文件的bug 做了修复
