### ISSUE TITLE
pgsql实例无法连接

### ISSUE THREAD

**Issue by tatuke** [hhyo/archer#2350]
### 重现步骤

升级1.10.0版本后，创建pgsql实例。无法连接，提示pgsql engine not supported 。1.9.0版本能正常连接的postgresql 也无法正常连接，admin权限没有看到相关配置项。请问是否已去掉pgsql的支持？还是需要在哪里额外配置？

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/46305821/b66ca2bf-fca0-42c6-a352-304a61b76105)

### 日志文本

```shell
engine pgsql not enabled or not supported
```

### 版本

1.10.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

postgresql 14

**Comment by woshiyanghai** [comment]
登录容器，看看你最新的archery/setting 中是否包含了 ENABLED_ENGINES=(
        list,
        [
            "mysql",
            "clickhouse",
            "goinception",
            "mssql",
            "redis",
            "pgsql",
            "oracle",
            "mongo",
            "phoenix",
            "odps",
            "cassandra",
        ],
    ),
配置

**Comment by woshiyanghai** [comment]
部署容器的机器是否写了本地的setting？

**Comment by LeoQuote** [comment]
Duplicate of #2251

换成 master 分支的镜像再试一次

**Comment by wqbbs911** [comment]
遇到同样的问题
![image](https://github.com/hhyo/Archery/assets/30170870/7ceabe77-3d95-4181-933c-3b013e8cbdbc)

用的这个镜像： docker pull hhyo/archery:v1.10.0

**Comment by wqbbs911** [comment]
换成master可以了，但申请权限时报错：
![image](https://github.com/hhyo/Archery/assets/30170870/a82e564e-3a24-4d64-94db-883e402d4df1)
