### ISSUE TITLE
oidc登录https协议出现无效参数redrect_uri

### ISSUE THREAD

**Issue by imhun** [hhyo/archer#2392]
### 重现步骤

系统通过https访问，https通过反向代理到archery
oidc登陆时，源地址是https://xxx.com，服务端获取到的重定向地址是http://xxx.com:9123/xxx，导致出现：无效参数 redirect_uri的错误，无法正常登录

进过排查，发现是archery 内置的nginx代理没有正确配置参数导致，如下图
X-Forwarded-Host 不应该配置nginx_port，以便正确获取上游host
X-Forwarded-Proto 不应该直接取$scheme，而应该从上游代理转发的变量获取：$http_X_Forwarded_Proto
这样可以正确获取到上游的源地址https://xxx.com
<img width="636" alt="image" src="https://github.com/hhyo/Archery/assets/4082111/61b0a3ea-2f14-4f0c-865f-03ea0d082f09">
经过直接修改容器内的nginx.conf的配置，已确认问题修复

### 预期外的结果

oidc正常登录

### 版本

1.10.0

### 部署方式

Docker

**Comment by LeoQuote** [comment]
这个你可能有些误解, 请看一下这段代码 https://github.com/hhyo/Archery/blob/559791196c1c907e628a03f7c4b40ee131078b81/src/docker/startup.sh#L10-L14 

启动的时候会自动替换这个端口, 只要你不设置 nginx-port 环境变量, 就不会有这样的问题

默认的 docker-compose 是设置了这个环境变量的, 你可以把这个环境变量删除, 即可解决问题
