### ISSUE TITLE
1.8.5升级到1.10.0之后【自动审核不通过】的工单逻辑发生了变化，一直在【待办列表】无法处理

### ISSUE THREAD

**Issue by qingmengxinghe** [hhyo/archer#2395]
### 重现步骤

1、升级之后发现，自动审核不通过的工单状态为【待审核】，之前是【已完成】
然后就会有待在【待办列表】里面状态，显示未审核，点击【未审核】按钮进入审核见面，但是却没有任何操作权限
所以【自动审核不通过】的工单就会一直是未审核状态

2、对比了数据库里存的值，发现升级前【自动审核不通过】的工单信息 workflow_audit表里面current_audit | next_audit | current_status 这三个字段的值和之前版本的值都有区别，后面4行数据是新版本的。

workflow_type	b_current_audit	b_next_audit	b_current_status
1	-1	-1	1
1	-1	-1	1
1	-1	-1	1
1	-1	-1	1
1	-1	-1	1
2	3	-1	0
2	3	-1	0
2	10	3	0
2	10	3	0

### 预期外的结果

【自动审核不通过】的工单应该直接结束，不应该是未审核状态，请修复这个bug

### 版本

1.10.0

### 部署方式

手工部署

**Comment by LeoQuote** [comment]
hi, 最新的 master 分支已修复, 可以用 master 自己尝试一下

**Comment by qingmengxinghe** [comment]
> hi, 最新的 master 分支已修复, 可以用 master 自己尝试一下

我尝试了最新的代码，还是不行，请问是改了这里吗

/Archery-master/sql_api/serializers.py


 # 有时候提交后自动审批通过, 在这里改写一下 workflow 状态
        if auditor.audit.current_status == WorkflowStatus.PASSED:
            auditor.workflow.status = "workflow_review_pass"
            auditor.workflow.save()
【自动审核不通过】 的状态还是【未审核】

**Comment by qingmengxinghe** [comment]
> hi, 最新的 master 分支已修复, 可以用 master 自己尝试一下

看起来是这里 
./sql/utils/workflow_audit.py  234行 这里没有判断自动审核未通过的情况，把状态都设置为了【待审核】
自动审核未通过的状态应该为【审核未通过】才对
 self.audit.current_status = WorkflowStatus.WAITING

**Comment by LeoQuote** [comment]
谢谢, 可以顺手提一个 pr

**Comment by LeoQuote** [comment]
谢谢反馈, 我正在处理, 应该是再加一个逻辑即可. 如果你有好的方案也可以提pr

**Comment by qingmengxinghe** [comment]
> 谢谢反馈, 我正在处理, 应该是再加一个逻辑即可. 如果你有好的方案也可以提pr

能力有限，就不提了吧， 多谢关注

**Comment by qingmengxinghe** [comment]
> 谢谢反馈, 我正在处理, 应该是再加一个逻辑即可. 如果你有好的方案也可以提pr

谢谢大佬
