### ISSUE TITLE
mssql无法显示表结构

### ISSUE THREAD

**Issue by pengkang1991** [hhyo/archer#2402]
### 重现步骤

SQL查询菜单，选择在线查询，数据库选择mssql，查询表结构无法显示表结构，只能显示类型。如下图：

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/49478192/755adf9c-4ead-4a15-a644-122bf2d5d995)

### 版本

1.10.0

### 部署方式

Docker

**Comment by LeoQuote** [comment]
大佬看一下这个 https://github.com/hhyo/Archery/issues/2378#issuecomment-1820321443 , 我这边无环境, 不方便测试, 如果方便的话还请麻烦改一下提交一下 PR, 谢谢
