### ISSUE TITLE
v1.10.0版本中企业微信不能向个人发送工单消息

### ISSUE THREAD

**Issue by flfps** [hhyo/archer#2408]
### 重现步骤

升级到最新版后，发现企业微信的自建应用无法收到消息，查看代码发现发送至自建应用的相关代码已经被移除，是为什么呢？
![image](https://github.com/hhyo/Archery/assets/19426506/2364fe1b-3d71-4fa4-99b9-791c32dc75b5)

### 预期外的结果

无法发送消息至企业微信自建应用

### 版本

1.10.0

### 部署方式

手工部署

**Comment by LeoQuote** [comment]
辛苦试一下最新版 master 的镜像, 这部分有重构, 可以看 commit

**Comment by flfps** [comment]
查看了master的代码，确实没有向企业微信自建应用发送消息的源代码

**Comment by LeoQuote** [comment]
@flfps 发现确实遗漏了, 我这边提了 pr, 辛苦拉我的代码测一下看看能不能修复, 如有建议可以在 pr 内回复, 谢谢反馈!
