### ISSUE TITLE
配置了一个实例查询不到所有的database

### ISSUE THREAD

**Issue by magicxiexiaodong** [hhyo/archer#2427]
### 重现步骤

1、创建了一个实例
![image](https://github.com/hhyo/Archery/assets/46348633/4b4a74e3-7eb4-4328-a74e-62239b915038)

2、在数据库里面查询不到我的 test库 是为什么，哪里需要配置吗
<img width="1437" alt="image" src="https://github.com/hhyo/Archery/assets/46348633/ae4ff3bd-ccf7-4784-8ad7-25f29202b7df">

### 预期外的结果

按理讲他是可以查询到我的所有数据库database的，发现test是查询不到的

### 日志文本

```shell
略
```

### 版本

1.10.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL 8.0

**Comment by LeoQuote** [comment]
看一下代码, 过滤掉了 test 库

**Comment by magicxiexiaodong** [comment]
> 看一下代码, 过滤掉了 test 库

请问下 有社区群吗，微信 钉钉 或者qq的群吗？因为我是java程序员 可能就不太能把整个源码都看一下

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/fd0c974b499c6beee2b1a7b6463867ec0f23ea1b/sql/engines/mysql.py#L189

代码在这，你可以改改看
