### ISSUE TITLE
Archery (v1.10.0)注册按钮不见了

### ISSUE THREAD

**Issue by SoHuDrgon** [hhyo/archer#2465]
### 重现步骤

注册按钮不见了
![截屏2023-12-22 14 51 28](https://github.com/hhyo/Archery/assets/11847516/bd6494ee-af0f-4b2e-b18e-c69f01732b73)
系统设置里面是开启的：
![截屏2023-12-22 14 51 47](https://github.com/hhyo/Archery/assets/11847516/0aa9842d-bfe9-43b3-becc-64dac363d680)

### 预期外的结果

请问如何才能将注册功能显示出来？

### 版本

1.10.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL: 5.7.26
Browsers: Chrome

**Comment by LeoQuote** [comment]
Duplicate of #2286
