### ISSUE TITLE
docker快速部署，登录报错403Forbidden

### ISSUE THREAD

**Issue by wux9530** [hhyo/archer#2478]
### 重现步骤

1、使用官网提供的docker部署方式：mysql、redis、archery、goinception完全使用内置的镜像,未使用外部
2、修改了docker-compose.yml archery映射端口为8081，其余没有任何修改
3、docker启动完成后，访问页面，使用创建的超管用户登录报错403 Forbidden，无法登入系统

### 预期外的结果

docker启动完成后，访问页面，使用创建的超管用户登录报错403 Forbidden，无法登入系统

### 日志文本

```shell
登录报错403，以上日志文件未打印任何日志信息
```

### 版本

1.9.1

### 部署方式

Docker

**Comment by GDFboy** [comment]
一样的问题，有解决吗，百度到说是添加一条配置CSRF_TRUSTED_ORIGINS = ['http://xxx.xxx.com'],但是我这边试了没有用

**Comment by GDFboy** [comment]
![image](https://github.com/hhyo/Archery/assets/53328161/26f6023a-3ed8-416e-846b-988913ec96bd)
登录到容器里面，修改settings.py文件，按照图片的配置，将多余的CSRF_TRUSTED_ORIGINS配置注释掉，添加一条，后面写上自己的访问地址，重启容器就好了
