### ISSUE TITLE
"在线查询"页面，选择实例下拉框 无法显示postgresql实例

### ISSUE THREAD

**Issue by dmanbu** [hhyo/archer#2481]
### 重现步骤

升级v1.10.0版本后，发现在 选择实例 的下拉框中，无法显示postgresql实例
但通过 /group/user_all_instances/ 接口查询，却有postgresql实例，只是页面无法显示

### 预期外的结果

现已回滚至v1.9.1版本后，一切正常

### 日志文本

```shell
archery.log
qcluster.log
supervisord.log
docker logs --tail 1000 -f archery
并无相关报错
```

### 版本

1.10.0

### 部署方式

Docker

**Comment by LeoQuote** [comment]
重复, 已解决

**Comment by dmanbu** [comment]
> 复, 已解决

请问有issues链接么？我没找到

**Comment by LeoQuote** [comment]
Duplicate of #2251 

很难搜到吗？搜pg就能搜到啊
