### ISSUE TITLE
多个mysql语句不支持

### ISSUE THREAD

**Issue by pengkang1991** [hhyo/archer#2490]
### 重现步骤

SQL上线执行语句：purge binary logs to  mysql-bin.@03890';
SQL上线执行语句：ALTER DATABASE lsag CHARACTER SET utf8mb4’ COLLATE utf8mb4 general ci'

### 预期外的结果
![企业微信截图_17062336263219](https://github.com/hhyo/Archery/assets/49478192/43483427-05a6-4b8a-b829-c931d7a8179b)
![image](https://github.com/hhyo/Archery/assets/49478192/a31f3a8e-4a75-4f3a-bb8d-a0db29fc2b90)

报错如下：line 2 column 6 near "purge binary logs to 'mysql-bin.003090""
报错如下：error

### 版本

1.10.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

MySQL5.7

**Comment by LeoQuote** [comment]
非 archery bug, 语法检查, 执行相关请查看goinception 文档和 issue区
