### ISSUE TITLE
從1.9.1 升級至1.10.0，網頁出現Server Error (500)

### ISSUE THREAD

**Issue by dearsiang** [hhyo/archer#2533]
### 重现步骤

1.按照升級步驟：https://github.com/hhyo/archery/wiki/upgrade
2.登入Archery 後，點選SQL審核出現Server Error (500)

### 预期外的结果

<img width="1507" alt="Snipaste_2024-03-14_11-04-46" src="https://github.com/hhyo/Archery/assets/107904775/b2ab93a6-dc64-44e4-9b29-8589a83fd795">

### 日志文本

```shell
1.logs 路徑沒有archery.log
2.logs 路徑沒有qcluster.log
3.docker logs archery -f --tail=10
  File "/opt/venv4archery/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'sql_instance.is_ssl' in 'field list'")
2024-03-14 11:04:22,971 - django.request - WARNING - Not Found: /404.html
```

### 版本

1.10.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

mysql:5.7
Browsers: Chrome
goInception: hanchuanchuan/goinception:latest

**Comment by lanheader** [comment]
你的数据库sql_instance 确少is_ssl字段，升级的时候是不是没有同步数据库呢？

**Comment by dearsiang** [comment]
1. 請問怎麼做同步數據庫？
2. 对比 src/docker-compose 文件夹, 按照最新配置进行调整, 注意务必更新 settings.py 文件, 否则可能无法启动, 确认配置没问题后使用 docker compose -f docker-compose.yml up -d 启动新版本服务

這一段描述不太懂，是把Archery1.10.0的docker-compose這個資料夾覆蓋到Archery1.9.1嗎？還有更新Settings.py 是指Archery 1.10.0的src/docker-compose/archery這個路徑下的settings.py ，更新到Archery1.9.1的src/docker-compose/archery嗎？

在請解惑，謝謝。

**Comment by dearsiang** [comment]
還有這邊發現，1.10.0的docker-compose.yaml 裡面寫的archery tag是1.9.1

**Comment by lanheader** [comment]
https://github.com/hhyo/archery/wiki/upgrade 
同步数据库步骤看下Docker 安装部分，sql在src/init_sql/v1.10.0.sql

**Comment by dearsiang** [comment]
執行python manage.py dbshell < src/init_sql/v1.10.0.sql ，出現以下錯誤
2024-03-14 12:07:11,208 - environ.environ - INFO - /opt/archery/.env not found - if you're not configuring your environment separately, check this.
ERROR 1060 (42S21) at line 2: Duplicate column name 'db_name'
CommandError: "mysql --user=root --host=mysql --port=3306 --default-character-set=utf8mb4 archery" returned non-zero exit status 1.

**Comment by lanheader** [comment]
/opt/archery/.env not found - if you're not configuring your environment separately, check this.看这个报错

**Comment by dearsiang** [comment]
這邊將原本/opt/archery/.env.list 複製成.env , 也不知道對不對

重新執行同步數據庫，少了.env 錯誤訊息
python manage.py dbshell < src/init_sql/v1.10.0.sql 
ERROR 1060 (42S21) at line 2: Duplicate column name 'db_name'
CommandError: "mysql --user=root --host=mysql --port=3306 --default-character-set=utf8mb4 archery" returned non-zero exit status 1.

**Comment by dearsiang** [comment]
這升級不太好升～＾＾

**Comment by LeoQuote** [comment]
我建议你用 master 分支的代码升, 你试一下, 发版的时候种种原因吧里边有些偏差, 1.10.0 那个位置还有好些bug 没修

**Comment by dearsiang** [comment]
好的，謝謝

**Comment by peng19832** [comment]
其实，要不要代码都可以升，docker方式，主要是替换镜像，和数据库脚本，手工都可以完成。
compose脚本里，自己修改下镜像版本，手工执行下增量的sql，单独down、up一下archery容器就好了
