### ISSUE TITLE
docker启动，初始化数据报错

### ISSUE THREAD

**Issue by mpv945** [hhyo/archer#2535]
### 重现步骤

1 下载官网最新master分支代码
2 执行docker compose up -d 启动
3 doc#表结构初始化
cd /opt/archery
source /opt/venv4archery/bin/activate
python3 manage.py makemigrations sql  
python3 manage.py migrate
#数据初始化
python3 manage.py dbshell<sql/fixtures/auth_group.sql
<img width="583" alt="微信图片_20240229102846" src="https://github.com/hhyo/Archery/assets/20806691/4a920979-c435-4269-ad12-afd1ab5bc5d4">
ker exec -ti archery /bin/bash

### 预期外的结果

出现错误，无法数据初始化
<img width="583" alt="微信图片_20240229102846" src="https://github.com/hhyo/Archery/assets/20806691/bd233e13-9e6d-4c5f-b3d9-f616e0700501">

### 版本

1.10.0

### 部署方式

Docker

**Comment by mpv945** [comment]
图片传错了，应该是这个
![Uploading 企业微信截图_17104977164284.jpg.png…]()

**Comment by mpv945** [comment]
不好意思图片传错了，应该是下面这个
<img width="497" alt="企业微信截图_17104977164284 jpg" src="https://github.com/hhyo/Archery/assets/20806691/7886513a-f8ec-49d4-b118-ff2b53f495f7">

**Comment by Grain-Yu** [comment]
python3 manage.py makemigrations sql
python3 manage.py migrate
这两步是否有报错？或者登入mysql，检查表结构是否正常
