### ISSUE TITLE
sql查询页面不显示mysql所有库的test表

### ISSUE THREAD

**Issue by Grain-Yu** [hhyo/archer#2537]
### 重现步骤

mysql> use abc;

mysql> create table test(id int,name varchar(5));

mysql> create table aaa(id int,name varchar(5));

mysql> use abc;

mysql> show tables;
+---------------+
| Tables_in_abc |
+---------------+
| aaa           |
| test          |
+---------------+

### 预期外的结果

然而选择界面上却看不到test表：
![image](https://github.com/hhyo/Archery/assets/70142140/d8f419bb-7201-4134-8cac-82b819e02037)

### 版本

1.10.0

### 部署方式

Docker

**Comment by LeoQuote** [comment]
看代码，应该是显式过滤了 test db
