### ISSUE TITLE
使用docker方式启动，执行初始化命令报错，操作系统Windows11，Docker version 25.0.3

### ISSUE THREAD

**Issue by mpv945** [hhyo/archer#2538]
### 重现步骤

1 下载最新releases包，
2 cd src\docker-compose 执行 docker compose -f docker-compose.yml up -d
3 切到容器：docker exec -ti archery /bin/bash
                     #表结构初始化
                     cd /opt/archery && source /opt/venv4archery/bin/activate
                     python3 manage.py migrate 这一步执行最后有报错

### 预期外的结果

出现初始化很多错误
<img width="479" alt="屏幕截图 2024-03-18 102159" src="https://github.com/hhyo/Archery/assets/20806691/58663bad-a326-48c8-b9ae-bc63d04abf77">

### 版本

1.9.1

### 部署方式

Docker

**Comment by Grain-Yu** [comment]
source /opt/venv4archery/bin/activate是否生效？

**Comment by mpv945** [comment]
> source /opt/venv4archery/bin/activate是否生效？

生效，目前找到问题，，手动创建archery数据库，并指定为utf-8格式
