### ISSUE TITLE
sql优化--无法选择我加入的postgres 数据库

### ISSUE THREAD

**Issue by mpv945** [hhyo/archer#2539]
### 重现步骤

1 服务已经安装好
2 登录平台，添加postgres数据库
3 sql优化模块，无法找到上面添加的postgres数据库

### 预期外的结果

无法对postgres查询进行性能分析

### 版本

1.9.1

### 部署方式

Docker

**Comment by Grain-Yu** [comment]
优化的功能都是对于mysql做的，其他的没有
