### ISSUE TITLE
工单按全部维度筛选显示NaN

### ISSUE THREAD

**Issue by ocpeng** [hhyo/archer#2542]
### 重现步骤

- 第一步：当标签在【全部】
- 第二部：再选择【自定义】

如下
![image](https://github.com/hhyo/Archery/assets/43569914/21b9d377-71bf-4940-9b1a-420f6871b654)

### 预期外的结果

时间筛选出现NaN，如下
![image](https://github.com/hhyo/Archery/assets/43569914/d3de99a0-29ef-4a7c-8d42-4a7cf8cc63ca)

### 日志文本

```shell
无需关注日志
```

### 版本

1.10

### 部署方式

手工部署

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

1. 修复过程，修改两处，如下

```
vim sqlworkflow.html               
                 if (start.isValid() && end.isValid() && start.dayOfYear()!=1) {
......
                    "全部": [moment({ year: 1970 }),moment()],
```

1. 效果如下，当选择了【全部】，从1970开始，如下：

![image](https://github.com/hhyo/Archery/assets/43569914/98a493a7-7803-4b49-9f04-893891e17cf3)

**Comment by LeoQuote** [comment]
欢迎pr
