### ISSUE TITLE
archery-1.10.0版本平台SQL审核--SQL上线--提交SQL进行检测时，只支持一条SQL语句的检测，提交多条SQL无法检测，也无报错 

### ISSUE THREAD

**Issue by lixingtao6234** [hhyo/archer#2561]
### 重现步骤

1、docker安装好后，进行配置、计入实例、资源组等等；
2、SQL审核--SQL上线--提交SQL；
3、如果提交的是一条SQL语句，点击SQL检测，则正常，如果提交的是2条SQL及多条SQL，点击SQL检测，则页面弹出异常，检测结果什么都不显示；

### 预期外的结果

![1712057934051](https://github.com/hhyo/Archery/assets/165788161/a0d8fa57-9b13-405d-9d16-6fb3d3ef3571)
这个图片是一次性提交3条SQL，SQL检测异常，弹出异常框，但是不显示异常内容；
![1712058001676](https://github.com/hhyo/Archery/assets/165788161/be270329-973e-4331-b2e7-4d33886f1cc6)
这个图片是上述页面弹出异常的时候，浏览器的报错；
![1712058030137](https://github.com/hhyo/Archery/assets/165788161/c5d0e4d3-222f-4064-913b-527cb951e90c)
这个图片是只提交一条SQL的时候，SQL检测正常，检测结果显示正常，也能正常的执行。

### 日志文本

```shell
日志内无异常报错
```

### 版本

1.10.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

![1712058302355](https://github.com/hhyo/Archery/assets/165788161/8eb66576-46bb-4208-8760-44efc6b4451d)

**Comment by LeoQuote** [comment]
重复
