### ISSUE TITLE
IP可以正常登录，域名不可以

### ISSUE THREAD

**Issue by EverCooling** [hhyo/archer#2563]
### 重现步骤

![image](https://github.com/hhyo/Archery/assets/30490402/44dac686-03bf-42fe-bbd1-d49835557fc7)
IP可以正常登录，但是域名登陆提示报错

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/30490402/d3b8f5a1-b824-404d-8dbe-7dccd34f636f)

### 版本

1.10.1

### 部署方式

Docker

**Comment by EverCooling** [comment]
这个被关闭是啥意思

**Comment by Grain-Yu** [comment]
> 这个被关闭是啥意思

看起来已经超出archery范畴了。是否有进一步报错信息？

**Comment by bcyt** [comment]
我也遇到同样的问题，好像是被nginx 拦截了，在nginx 的access.log 日志提示403。看了之前的一些解决问题的 改CSRF_TRUSTED_ORIGINS 配置，都改了，还是403

**Comment by psychiche** [comment]
看了好几个同类型的 issue，我也常事改了下面的，但是还是 403 Forbidden。。。
我下面改的正确吗，这样改完之后访问是example.com:9123 吗？

```
local_settings.py: |-
        # -*- coding: UTF-8 -*-
        # override your configs here
        CSRF_TRUSTED_ORIGINS = ["https://*.example.com"]
```

**Comment by jifeilong9** [comment]
> 看了好几个同类型的 issue，我也常事改了下面的，但是还是 403 Forbidden。。。 我下面改的正确吗，这样改完之后访问是example.com:9123 吗？
> 
> ```
> local_settings.py: |-
>         # -*- coding: UTF-8 -*-
>         # override your configs here
>         CSRF_TRUSTED_ORIGINS = ["https://*.example.com"]
> ```

最后改好了吗
