### ISSUE TITLE
archery limit 分页查询失效

### ISSUE THREAD

**Issue by howieqdd** [hhyo/archer#2566]
### 重现步骤

select * from table limit 21,20 不生效 应该展示的是第21条开始的后20条数据，但是返回的还是1-20条数据

### 预期外的结果

select * from table limit 21,20 不生效 应该展示的是第21条开始的后20条数据，但是返回的还是1-20条数据

### 版本

v1.7.9

### 部署方式

K8S

**Comment by feiazifeiazi** [comment]
你的sql需要加order by排序。 
你在数据库直接执行看看结果是咋样的。

**Comment by howieqdd** [comment]
> 你的sql需要加order by排序。 你在数据库直接执行看看结果是咋样的。

sql 中是带order by 的，执行出来的结果是一样的

**Comment by te87037** [comment]
> > 你的sql需要加order by排序。 你在数据库直接执行看看结果是咋样的。
> 
> sql 中是带order by 的，执行出来的结果是一样的

在SQL執行的結果跟archery一致不就代表正常沒問題?
可以請您描述詳細一些嗎?

**Comment by howieqdd** [comment]
> > > 你的sql需要加order by排序。 你在数据库直接执行看看结果是咋样的。
> > 
> > 
> > sql 中是带order by 的，执行出来的结果是一样的
> 
> 在SQL執行的結果跟archery一致不就代表正常沒問題? 可以請您描述詳細一些嗎?

select * from table order by date desc limit 21,20 不生效, 应该展示的是第21条开始的后20条数据，但是返回的还是1-20条数据

**Comment by hhyo** [comment]
#1172
