### ISSUE TITLE
自提自审设置项的效果反了

### ISSUE THREAD

**Issue by patrickering** [hhyo/archer#2567]
### 重现步骤

1、在设置SQL上线是否自己可以审核自己的情况、配置了[系统管理]-[配置项管理]中的BAN_SELF_AUDIT是OFF的时候，是可以自己审核自己，设置为ON的是否反而不行

### 预期外的结果

![off](https://github.com/hhyo/Archery/assets/54468334/c792ff32-ee63-4714-a13d-b0de6c1a779b)
![on](https://github.com/hhyo/Archery/assets/54468334/fcad100f-8ade-493f-9925-939f873688e8)

### 版本

1.10.0

### 部署方式

Docker

**Comment by LeoQuote** [comment]
中文和英文描述不符, 文案问题, 可以顺手提一下pr , 谢谢

**Comment by feiazifeiazi** [comment]
@LeoQuote 我来改一下

**Comment by feiazifeiazi** [comment]
> 中文和英文描述不符, 文案问题, 可以顺手提一下pr , 谢谢

我来改一下

**Comment by patrickering** [comment]
有时间了，结果没有机会提pr了

**Comment by LeoQuote** [comment]
@patrickering 有空可以看看项目里打了 help wanted label的issue ，帮忙修复或者实现一下

https://github.com/hhyo/Archery/labels/help%20wanted
