### ISSUE TITLE
doris和starrocks报错

### ISSUE THREAD

**Issue by xiehaitang** [hhyo/archer#2589]
### 重现步骤

查询starrocks 点击查看表结构出现的异常
![image](https://github.com/hhyo/Archery/assets/74036543/ccc9230e-75ca-46d8-95a9-14543ec39110)
查询doris点击查看表结构出现的异常
![image](https://github.com/hhyo/Archery/assets/74036543/575207f5-9d7d-430c-b003-ab29324d505d)

### 预期外的结果

正常应该和mysql一样不报错

### 版本

1.10.0

### 部署方式

Docker

**Comment by Grain-Yu** [comment]
请问实例创建的时候，数据库类型是MySQL还是doris？

**Comment by xiehaitang** [comment]
1、我数据库类型使用的是doris。
第一个图是starrocks 报错的内容，starrocks 使用的是3的版本
第二个图是doris报错的内容，doris版本是1.13

2、我在1.8.5的时候，使用的是mysql，只是我更改query_privileges.py文件：if instance.db_type == 'mysql' and instance.instance_name != 'doris':
