### ISSUE TITLE
接口504 Gateway Timeout

### ISSUE THREAD

**Issue by boldmanQ** [hhyo/archer#2615]
### 重现步骤

填写上线工单时，上传7.6MB SQL文件，数据库为PostgreSQL。
点击“SQL检测”按钮后，60秒会超时，接口为/api/v1/workflow/sqlcheck/

![image](https://github.com/hhyo/Archery/assets/27854445/129f8cc7-e80d-4d96-8b1d-6442f55a0d60)
![image](https://github.com/hhyo/Archery/assets/27854445/24fde6fd-cd61-4a9f-a0c9-3d4e25f16ede)
![image](https://github.com/hhyo/Archery/assets/27854445/c0155bab-ddd7-4501-9787-963ba558ff6a)

链路为Kubernetes Ingress nginx controller——> Archery-Docker (ENTRYPOINT startup.sh: nginx + gunicorn)
超时参数设置：
Ingress Nginx Controller：
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 600s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 600s
    nginx.ingress.kubernetes.io/proxy-send-timeout: 600s
![image](https://github.com/hhyo/Archery/assets/27854445/63497e6f-c316-4d24-a522-5b1e74ccc24f)

Archery Docker：
    nginx.conf:
          proxy_connect_timeout   300s;
          proxy_read_timeout      300s;
          proxy_send_timeout      300s;
![image](https://github.com/hhyo/Archery/assets/27854445/34f9adb3-7143-4eab-99d7-af5c45cb05c8)

系统配置项：
  MAX_EXECUTION_TIME： 300

过程中Nginx error log 未产出超时相关日志记录，疑似是后端内部的超时控制
调试过程中，django_q会产出UserWarning，但看起来好像与本问题无关，尝试在Q_CLUSTER中增加timeout设置未消除：
![image](https://github.com/hhyo/Archery/assets/27854445/de14055a-01a2-4f44-ba9e-db9976e50457)

### 预期外的结果

不应该有60秒的必现超时

### 版本

1.9.1

### 部署方式

K8S

**Comment by LeoQuote** [comment]
你看一下 gunicorn 的配置和文档, 是否有超时配置

**Comment by boldmanQ** [comment]
> 你看一下 gunicorn 的配置和文档, 是否有超时配置

https://github.com/hhyo/Archery/blob/master/src/docker/startup.sh
gunicorn的超时是600s

当不使用gunicorn，直接用python mananager runserver启动时，也60s超时，是不是就能排除gunicorn的问题了？

**Comment by LeoQuote** [comment]
那有可能是请求goinception 的时候超时了，你检查下客户端和服务端的配置，是否能修改配置

**Comment by boldmanQ** [comment]
> 那有可能是请求goinception 的时候超时了，你检查下客户端和服务端的配置，是否能修改配置

![image](https://github.com/hhyo/Archery/assets/27854445/5b017d33-cc7d-4048-8db9-8aed0cefc64f)
没有设置goinception，它会导致这个问题吗？

**Comment by boldmanQ** [comment]
通过Debug sql_api/api_workflow.py  ExecuteCheck类post方法
![image](https://github.com/hhyo/Archery/assets/27854445/01a61ea9-ffa6-4005-aaa9-b50bab337925)
![image](https://github.com/hhyo/Archery/assets/27854445/84f33193-6803-4873-98a0-5d4daa84ba71)

我这个整体SQL检查过程耗时89秒，但浏览器上的页面在60秒就报错了

**Comment by LeoQuote** [comment]
哦哦, 是 pg 啊, pg 是自己实现的检查 https://github.com/hhyo/Archery/blob/18214bc13cc99a5fd60acbaa0a5ef2cbe9cb9485/sql/engines/pgsql.py#L238 , 和 goinception 无关, 我看到你已经加了一些日志, 你可以再多加一些日志看看是哪里的问题, 如果方便的话请提一个 pr, 谢谢~

**Comment by boldmanQ** [comment]
![image](https://github.com/hhyo/Archery/assets/27854445/70e45e41-ec58-4c80-ae3d-41143d2de063)
前端，sql/templates/sqlsubmit.html文件
ajax增加超时参数，timeout设置为100s，但在浏览器的debug工具里看接口还是60秒就超时了..
（浏览器已经清了缓存、archery使用manage.py runserver启动、nginx关闭了static静态路由的情况下）

**Comment by LeoQuote** [comment]
应该不是前端问题, 你试一下去掉 nginx, 去掉 gunicorn, 用 runserver 起, 看看是哪里的问题

**Comment by boldmanQ** [comment]
> 哦哦, 是 pg 啊, pg 是自己实现的检查
> 
> https://github.com/hhyo/Archery/blob/18214bc13cc99a5fd60acbaa0a5ef2cbe9cb9485/sql/engines/pgsql.py#L238
> 
> , 和 goinception 无关, 我看到你已经加了一些日志, 你可以再多加一些日志看看是哪里的问题, 如果方便的话请提一个 pr, 谢谢~

我现在没太多思路了，目前分不清是后端还是前端的超时，我的debug日志看88秒就能够完成sql检查任务，它没有在60秒时中断，似乎说明后端没问题，是前端的超时？

**Comment by boldmanQ** [comment]
解决了，问题在于上面最外层ingress nginx的annotation配置，“600s”不生效，用“600”就好了，它是无单位的seconds

**Comment by LeoQuote** [comment]
👍 我帮你整理一下最后一次的评论
