### ISSUE TITLE
用户修改密码提供没有权限

### ISSUE THREAD

**Issue by firehalt** [hhyo/archer#2623]
### 重现步骤

用户修改密码提升没有权限，后台没有找到对应的权限
![修改密码错误](https://github.com/hhyo/Archery/assets/29405113/4cd23dec-8575-4096-94cb-99dcc655168e)

用户的权限设置如下
![权限1](https://github.com/hhyo/Archery/assets/29405113/1e36297b-5cd2-4235-8d92-a84fba2d8a1a)
![权限2](https://github.com/hhyo/Archery/assets/29405113/f31fab5f-4431-459b-8dfc-f1432851b950)
![权限3](https://github.com/hhyo/Archery/assets/29405113/d56b1a6f-8025-44fc-9a02-6956be905d45)

### 预期外的结果

设置权限，让用户可以自行修改密码

### 版本

1.10.0

### 部署方式

Docker

**Comment by firehalt** [comment]
> ### 重现步骤
> 用户修改密码提升没有权限，后台没有找到对应的权限 ![修改密码错误](https://private-user-images.githubusercontent.com/29405113/328844721-4cd23dec-8575-4096-94cb-99dcc655168e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjIzODcsIm5iZiI6MTcxNTIyMjA4NywicGF0aCI6Ii8yOTQwNTExMy8zMjg4NDQ3MjEtNGNkMjNkZWMtODU3NS00MDk2LTk0Y2ItOTlkY2M2NTUxNjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAyMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YjY2NGU4MGQyZjRlMzliMGUxNDMzM2RlZDliZTFmOGFjNGI1NTEzNzRlNTIzNjI0OGE4NmMwMDg2ODU5NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUhD3cok51YlbhUcWlOqg47GUG-iaDEhBhAYSS6qbmo)
> 
> 用户的权限设置如下 ![权限1](https://private-user-images.githubusercontent.com/29405113/328844375-1e36297b-5cd2-4235-8d92-a84fba2d8a1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjIzODcsIm5iZiI6MTcxNTIyMjA4NywicGF0aCI6Ii8yOTQwNTExMy8zMjg4NDQzNzUtMWUzNjI5N2ItNWNkMi00MjM1LThkOTItYTg0ZmJhMmQ4YTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAyMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNGE5YjNlMGYzNmVjMzNlMGE3YzcyYzkxMWNiZWFhMjU1YWQ3MGNlMWNjNGQ5ZmE3OWRmNzE5YzBiZmViNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YCpS87qtmhCuf3SltqXlSfGuzdOOa5VeJ7ObaKa1g6c) ![权限2](https://private-user-images.githubusercontent.com/29405113/328844395-f31fab5f-4431-459b-8dfc-f1432851b950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjIzODcsIm5iZiI6MTcxNTIyMjA4NywicGF0aCI6Ii8yOTQwNTExMy8zMjg4NDQzOTUtZjMxZmFiNWYtNDQzMS00NTliLThkZmMtZjE0MzI4NTFiOTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAyMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNjQ4MWFmYzQ3OTc4MThjZDZjNWZhZjA1OTgyMTkwODQyMzkwYjliMDIyYTJhNjI4NTQyZDFiNmJhMmM5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UZG-ZPryioidrEccSlitK9RYAewMft9aiTj5Yokv4aw) ![权限3](https://private-user-images.githubusercontent.com/29405113/328844406-d56b1a6f-8025-44fc-9a02-6956be905d45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjIzODcsIm5iZiI6MTcxNTIyMjA4NywicGF0aCI6Ii8yOTQwNTExMy8zMjg4NDQ0MDYtZDU2YjFhNmYtODAyNS00NGZjLTlhMDItNjk1NmJlOTA1ZDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAyMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3Njg3ZGY2NjlmNTRiODk5OTUyYzIzYmMyMTBiYmI2NjRkYTQ0MjAyNjE2ZTdiMzYyMTliMjE3MGU5ZGI1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3JOn0VrRuBNp1h9lsQfKa4-Kb5tAlcXoFz-w8as9Yo)
> 
> ### 预期外的结果
> 设置权限，让用户可以自行修改密码
> 
> ### 日志文本
> _No response_
> 
> ### 版本
> 1.10.0
> 
> ### 部署方式
> Docker
> 
> ### 是否还有其他可以辅助定位问题的信息？比如数据库版本等
> _No response_

**Comment by xyhhttwan** [comment]
怎么解决的 ？

**Comment by zhengbucuo** [comment]
> 怎么解决的 ？

创建用户时候，把【工作人员状态】勾上就好了
