### ISSUE TITLE
下载最新Release v1.11.1显示版本为v1.10.0

### ISSUE THREAD

**Issue by yyr03gy** [hhyo/archer#2625]
### 重现步骤

1. 从https://github.com/hhyo/Archery/releases/tag/v1.11.1下载包。
2. 按照docker安装部署指引（https://github.com/hhyo/archery/wiki/docker）成功安装并启动。
3. 登录后查看版本信息为v1.10.0
<img width="1219" alt="image" src="https://github.com/hhyo/Archery/assets/36121946/487b2d4c-7a66-4b0b-b9e9-debd31868161">

### 预期外的结果

显示的版本为v1.11.1

### 版本

v1.11.1

### 部署方式

Docker

**Comment by yyr03gy** [comment]
镜像已经使用最新的镜像 hhyo/archery:v1.11.1

**Comment by LeoQuote** [comment]
谢谢反馈, 由于不是特别严重的问题, 将随下个版本发布修复, 如有更好的方案欢迎 pr

**Comment by DspringL** [comment]
docker exec -it archery bash
cat /opt/archery/archery/__init__.py

version = (1, 10, 0)
display_version = ".".join(str(i) for i in version)


修改这个文件中的版本号即可
![image](https://github.com/hhyo/Archery/assets/29829184/a7f85ff0-093d-4066-95b2-4c55d4d46d60)
![image](https://github.com/hhyo/Archery/assets/29829184/ee121c9f-56a5-4c13-8886-41ebda948499)
