### ISSUE TITLE
最新两个版本docker 镜像会报错

### ISSUE THREAD

**Issue by Keeyuu** [hhyo/archer#2628]
### 重现步骤

1. 原1.10.0 没有问题
2. 新版 1.11.0 1.11.1 一样的步骤就会报错
3. 内容如下 failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "dockerize": executable file not found in $PATH: unknown

### 预期外的结果

ERROR: for archery-miya-staging2-archery  Cannot start service archery: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "dockerize": executable file not found in $PATH: unknown

ERROR: for archery  Cannot start service archery: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "dockerize": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.

### 日志文本

```shell
ERROR: for archery-miya-staging2-archery  Cannot start service archery: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "dockerize": executable file not found in $PATH: unknown

ERROR: for archery  Cannot start service archery: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "dockerize": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.
```

### 版本

1.10.0

### 部署方式

Docker

**Comment by LeoQuote** [comment]
请遵循 https://github.com/hhyo/archery/wiki/upgrade 升级, 特别请更新最新的 docker-compose 文件, 如果更新完毕还有问题请继续回复

**Comment by Keeyuu** [comment]
已解决 docker-compose 改了这行entrypoint: "bash /opt/archery/src/docker/startup.sh"
