### ISSUE TITLE
ck sql上线会自动把表名转为小写

### ISSUE THREAD

**Issue by Keeyuu** [hhyo/archer#2636]
### 重现步骤

1. 原ck的表是有大写字母的
2. 使用sql上线的时候发现表不存在,仔细看了之后发现会把大写的表面自动转为小写
3. 报错 表 sv_import_advertisingcosts 不存在！实际表名是sv_import_advertisingCosts
4. 尝试了阿里云的ck和自己起的ck 是一样的结果

### 预期外的结果

1

### 日志文本

```shell
1
```

### 版本

1.11.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

clilckhouse:21.8.3
archery:1.11.1

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/b61bdf0aa4d4ec0b462d1cc8c95a8ec6388207de/sql/engines/clickhouse.py#L423 请看一下这里的逻辑, 是用了 sqlparse 切分了语句, 你可以测试看看是不是 sqlparse 导致的, 欢迎 pr
