### ISSUE TITLE
执行mongo报错Json decode failed

### ISSUE THREAD

**Issue by herohhhhabc** [hhyo/archer#2654]
### 重现步骤

archery执行mongo语句检测成功，审核完报错：Json decode failed.执行结果Json解析失败, 请联系管理员
mongo语句如下：db.test.insert({name:"zhangsan"})

### 预期外的结果

![11](https://github.com/hhyo/Archery/assets/170307951/5a50d36f-e8d2-48ea-b29c-14fb41248052)

### 版本

1.10.1

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

云数据库mongodb 版本4.2

**Comment by herohhhhabc** [comment]
archery版本1.10.0，写错了

**Comment by lanheader** [comment]
看 #2648

**Comment by herohhhhabc** [comment]
> 看 #2648

我看了一下有执行那个脚本吗，我是用docker部署的，在容器里启动？

**Comment by zhixiangjoy** [comment]
v1.10.0 mongo 执行mongo工单遇到一样的问题哦，因为有一些低版本的mongo，降级了pymongo到3.x的版本，查询可以，但无法执行mongo语句。

**Comment by huangsijun17** [comment]
应该是Mongosh版本/部署问题。
详见：https://github.com/hhyo/Archery/discussions/2969
