### ISSUE TITLE
升级1.10.0版本后，创建pgsql实例。无法连接，提示engine pgsql not enabled or not supported，admin权限没有看到相关配置项。请问是否已去掉pgsql的支持？还是需要在哪里额外配置？

### ISSUE THREAD

**Issue by lixingtao6234** [hhyo/archer#2655]
### 重现步骤

1、添加实例；
2、实例管理中，点击测试连通性，报错：engine pgsql not enabled or not supported

### 预期外的结果

![1716201954955](https://github.com/hhyo/Archery/assets/165788161/8c488086-db60-4b84-b096-e60350fc829f)

### 日志文本

```shell
无日志输出
```

### 版本

1.10.0

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

PostgreSQL 13.2,   archery的日志里面没有任何日志输出，

**Comment by LeoQuote** [comment]
Duplicate of #2251

**Comment by kakashuiyue** [comment]
vi archery/settings.py 将两处的pqsql 替换为pgsql，再重启下archery
