### ISSUE TITLE
如何修改Archery默认SQl审核的排序规则

### ISSUE THREAD

**Issue by firehalt** [hhyo/archer#2667]
### 重现步骤

我们数据库使用的排序规则为utf8mb4_unicode_ci，现在提交sql上线的时候报错，如下修改这个排序规则
sql预计如下：

DROP TABLE IF EXISTS `pro_group`;
CREATE TABLE `pro_group`  (
  `id` bigint(0) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `promotion_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL COMMENT '活动组名称',
  `promotion_name_error` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `product_count` int(0) NOT NULL COMMENT '活动组内产品数',
  `status` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NULL DEFAULT NULL COMMENT '状态(字典)',
  `avc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NULL DEFAULT NULL COMMENT 'AVC账号',
  `vc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'vc邮箱名称',
  `vc_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'vc账号',
  `company_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL COMMENT '公司名',
  `created_at` bigint(0) NOT NULL COMMENT '创建时间',
  `updated_at` bigint(0) NULL DEFAULT NULL COMMENT '更新时间',
  `deleted_at` bigint(0) NULL DEFAULT NULL COMMENT '删除时间',
  `error_msg` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '错误消息',
  `tenant_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL COMMENT '创建者id',
  `detail_url` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NULL COMMENT '详情excel文件地址',
  `promotion_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Amazon返回活动组code',
  `vendor_code` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `vendor_code_error` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `collected` int(0) NULL DEFAULT NULL COMMENT '是否已领完',
  `error_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '错误类型，亚马逊和aplus',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 366 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '活动组' ROW_FORMAT = DYNAMIC;

![sql上线问题](https://github.com/hhyo/Archery/assets/29405113/d38aaea1-0d6a-42f6-894b-e1112de94943)

### 预期外的结果

正常提sql

### 版本

1.10.0

### 部署方式

Docker

**Comment by nick2wang** [comment]
mysql的审核是由goinception处理的，参考：**https://hanchuanchuan.github.io/goInception/zh/options.html#variables列表**
![image](https://github.com/hhyo/Archery/assets/33473924/679df917-cd74-44cf-99c0-a530117af6a0)
![image](https://github.com/hhyo/Archery/assets/33473924/5750e5e7-2859-4e00-b057-0df8f552ba4b)
