### ISSUE TITLE
【Archery 1.11.1】数据库初始化报错Specified key was too long

### ISSUE THREAD

**Issue by tanglu86** [hhyo/archer#2670]
### 重现步骤

手动部署
Archery版本：1.11.1
数据库版本：mysql 5.7
数据库已经配置innodb_large_prefix=ON
执行python3 manage.py makemigrations sql 成功
执行python3 manage.py migrate失败报错

### 预期外的结果

![微信截图_20240528145455](https://github.com/hhyo/Archery/assets/38269740/6445b7d6-4ac2-4000-b0ce-26a5aacb0a05)

### 版本

1.11.1

### 部署方式

手工部署

**Comment by LeoQuote** [comment]
Duplicate of #2428

**Comment by Jefflu57** [comment]
解决方法：https://github.com/gregbaker/django-cas-ng/commit/132b2da79f84c1859f168f9dcbbe73cbe0b31be6#diff-e860047dbfcc91886af90a8917f2239a548961aa66434becba5c210d5e6146b5
