### ISSUE TITLE
module redis has no attribute cluster

### ISSUE THREAD

**Issue by moyanach** [hhyo/archer#2673]
### 重现步骤

reids 集群模式提示没有 cluster 模块， 跳转到源码确实没有，后面指定 redis 版本
![image](https://github.com/hhyo/Archery/assets/50991182/5451bdeb-d08c-430f-aff1-5a7eb0a267f1)
出现下面的依赖冲突
![image](https://github.com/hhyo/Archery/assets/50991182/0e8196ba-778e-456e-90de-49ac8252e907)

### 预期外的结果

![image](https://github.com/hhyo/Archery/assets/50991182/cc3c08d6-2304-4674-ad1d-2ccde95b7202)

### 版本

1.10

### 部署方式

Docker

**Comment by LeoQuote** [comment]
可以强行装的, 你找找方法, 然后是有提过把 django-q 替换掉, 但是暂时没人没空做 #2338 欢迎pr

**Comment by moyanach** [comment]
好的  知道了  有时间 但实力不够 哈哈哈 换个组件 里面涉及的地方全都要替换一遍 还要重头测试一遍 想想工程量巨大 
提个小小的建议 前后端分离一下
