### ISSUE TITLE
自动审核不通过，但是在待审核工单列表中依然可以看到工单

### ISSUE THREAD

**Issue by woshiyanghai** [hhyo/archer#2699]
### 重现步骤

1.配置工单禁止提交drop操作
2.提交一个drop工单，自动审核不通过
3.但是在待审核工单list中还是可以看到这个单子

### 预期外的结果

在待审核list中看到了自动审核不通过的单子

### 版本

1.11.1

### 部署方式

手工部署

**Comment by woshiyanghai** [comment]
尝试复现问题

**Comment by LeoQuote** [comment]
这个是存在的bug, 一致没来得及修来着

**Comment by woshiyanghai** [comment]
ok，我看看
