### ISSUE TITLE
升级版本到1.11.0 镜像内没有mysql 无法执行数据库升级脚本

### ISSUE THREAD

**Issue by jiahuiss** [hhyo/archer#2702]
### 重现步骤
![image](https://github.com/hhyo/Archery/assets/142789122/c0cb2c94-2faa-4323-b9cd-b2331f6d8569)

### 预期外的结果

无

### 版本

1.8.5

### 部署方式

Docker

**Comment by LeoQuote** [comment]
Duplicate of #2659

**Comment by jiahuiss** [comment]
![image](https://github.com/hhyo/Archery/assets/142789122/f57efb85-c098-48c4-a704-8c66c520bb9e)
是没有合并么 ，容器里还是没有mysql客户端需要自己手动安装么？
