### ISSUE TITLE
docker安装archery v1.11.1 报错

### ISSUE THREAD

**Issue by jiaping0424** [hhyo/archer#2742]
### 重现步骤

在docker安装archery v1.11.1过程中遇到如下错误：
(venv4archery) root@71088e873436:/opt/archery# python3 manage.py dbshell<sql/fixtures/auth_group.sql
2024-07-26 17:41:28,635 - environ.environ - INFO - /opt/archery/.env not found - if you're not configuring your environment separately, check this.
CommandError: You appear not to have the 'mysql' program installed or on your path.
(venv4archery) root@71088e873436:/opt/archery# 

MYSQL数据库已经启来了。
数据库相关的连接是在/otp/archery/archery/settings.py 里修改对吗？我修改后还是报这个错。
还有第一行说缺少.env文件。

### 预期外的结果

希望无报错，正常安装。

### 版本

V1.11.1

### 部署方式

Docker

**Comment by sunweiai** [comment]
我也是相同的报错，有没有相关解决方案？

**Comment by hhyo** [comment]
#2659

**Comment by Eric-3A** [comment]
用另一个类似的平台吧，这个太垃圾了

**Comment by LeoQuote** [comment]
@Eric-3A 欢迎贴出自己推荐的产品链接，另外，本项目是开源项目，欢迎提出PR或建议，或者fork 项目在本项目内帮助到其他人，这种情绪性的发言由于没有价值所以我暂时隐藏，感谢理解。
