### ISSUE TITLE
配置的pgsql无法连接，提示engine pgsql not enabled or not supported, please contact admin

### ISSUE THREAD

**Issue by YuanPeter** [hhyo/archer#2776]
### 重现步骤

使用的是docker-compose安装方式，本地已经购买了华为云的mysql、redis中间件
1、安装docker-compose(按照网上步骤)
2、编辑docker的deamon.json里面的registry-mirrors为：https://dockermirror.hxxhouse icu
3、下载release的archive-1.11.3版本souceCode 并且解压到/data下面，重命名为archery
4、编辑解压缩后的/data/archery/src/docker-compose/里面docker-compose文件内容如下：
![image](https://github.com/user-attachments/assets/3f329528-e555-442c-b89c-70856acc6753)

5、再编辑/data/archery/src/docker-compose/archery/下的setting.py文件。内容如下：
![image](https://github.com/user-attachments/assets/06fc169e-7fad-47de-8e1b-471f0ab0901d)

6、执行docker compose -f docker-compose.yml up -d
7、等待安装完成后 根据https://archerydms.com/home/ 命令 分别进去执行了页面上的语句
![image](https://github.com/user-attachments/assets/c8ab4d86-0687-4969-9c10-dcb835967c91)
8、完成后进入页面进行数据库实例的配置。其中mysql配置完成后都是没问题的。但是pgsql配置好了以后 就报错

### 预期外的结果

![image](https://github.com/user-attachments/assets/88c62c9c-6881-4ccf-a47b-17022f7d1dee)

### 版本

1.11.3

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

pgsql:14.0版本

**Comment by kakashuiyue** [comment]
vi archery/settings.py 有两处pqsql 替换为pgsql，重启archery
