### ISSUE TITLE
提示-不允许创建或使用视图

### ISSUE THREAD

**Issue by haomiemie** [hhyo/archer#2838]
### 重现步骤

大佬，您好：

我写了个执行创建视图的sql，在sql上线时，sql检测提示不允许创建或使用视图xxx。
如果我把创建视图的sql直接在navicat中执行，这条sql是可以正常工作的。

我的数据库是：mysql，版本：8.0.31
Archery版本是v1.11.3，以docker形式部署。

期待您的回复

### 预期外的结果

![image](https://github.com/user-attachments/assets/87215735-94fa-46af-bf9b-75ad800cc4c6)

### 版本

1.11.3

### 部署方式

Docker

### 是否还有其他可以辅助定位问题的信息？比如数据库版本等

mysql，版本：8.0.31

**Comment by LeoQuote** [comment]
Duplicate of https://github.com/hhyo/Archery/discussions/2802
