### ISSUE TITLE
MySQL8 WITH子句（也称为公共表表达式，CTE）不支持

### ISSUE THREAD

**Issue by duguwo** [hhyo/archer#2862]
### 重现步骤

![1](https://github.com/user-attachments/assets/eb5335ed-8907-46cc-b053-929ec48518e9)

### 预期外的结果

如题，在archery1.8.4查询mysql8.0.37带有with子句时，校验不通过

### 版本

1.8.4

### 部署方式

手工部署

**Comment by LeoQuote** [comment]
请注意 archery 的审核引擎是完全使用的外部 goinception, 这也在项目 readme 中有表达, 如有需要可以去 goinception 项目提交 issue https://github.com/hanchuanchuan/goInception/issues/274
